// ABB Robotic Assembly Cell Configuration

export const abbRoboticCellComponents = [
  {
    id: "6axis-robot-arm",
    name: "6-Axis Heavy Payload Robot Arm",
    subsystem: "ABB IRB 6700 Articulated Robot Arm",
    partNumber: "ABB-IRB6700-235/2.65 Articulated Arm",
    healthScore: 92,
    status: "HEALTHY",
    temperature: 48.5,
    pressure: "N/A",
    rpm: "3,100 RPM",
    vibration: 1.4,
    current: "52.0 A",
    rulHours: 11800,
    failureProbability: 1.8,
    lastMaintenanceDate: "2026-03-22",
    nextMaintenanceDate: "2026-08-22",
    maintenanceStatus: "Axis 1-6 Gearbox Lubrication Nominal",
    position3d: [0, 0.6, 0],
    cameraOffset: [0.8, 1.4, 2.6],
    explodedOffset: [0, 1.8, 0],
    aiDiagnosis: "6-Axis kinematic repeatability 0.03 mm. Servo joint backlash within ISO Class 2 limit.",
    aiRecommendation: "Check Axis 2 reducer grease condition at next quarterly check.",
    failureState: {
      healthScore: 44,
      status: "CRITICAL",
      temperature: 88.0,
      vibration: 8.4,
      current: "78.0 A",
      rulHours: 40,
      failureProbability: 80.0,
      aiDiagnosis: "Axis 2 RV reducer tooth pitting causing position overshoot alarm.",
      aiRecommendation: "Replace Axis 2 RV gearbox reducer and perform arm zero-position calibration.",
    },
    maintenanceHistory: [
      { id: "WO-ABB-201", date: "2026-03-22", type: "Preventive", technician: "ABB Field Ops", cost: "€1,450", details: "Robot arm RV reducer grease flushing & seal kit check." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 48.5,
      vibration: 1.4,
      health: 92,
    })),
  },
  {
    id: "end-effector-tooling",
    name: "End-Effector Tooling",
    subsystem: "Automatic Tool Changer & Servo Gripper",
    partNumber: "SCHUNK-EGP-64 Mechatronic Gripper",
    healthScore: 96,
    status: "HEALTHY",
    temperature: 36.2,
    pressure: "6.0 bar",
    rpm: "N/A",
    vibration: 0.6,
    current: "12.0 A",
    rulHours: 16500,
    failureProbability: 0.8,
    lastMaintenanceDate: "2026-04-05",
    nextMaintenanceDate: "2026-10-05",
    maintenanceStatus: "Gripper Jaw Parallelism 0.01 mm",
    position3d: [1.4, 1.2, 0],
    cameraOffset: [2.0, 1.8, 2.2],
    explodedOffset: [2.6, 2.2, 0],
    aiDiagnosis: "Schunk servo gripper gripping force 850 N steady with 100% part retention.",
    aiRecommendation: "Inspect gripper finger wear pads every 90 days.",
    failureState: {
      healthScore: 58,
      status: "WARNING",
      temperature: 64.0,
      vibration: 4.2,
      rulHours: 180,
      failureProbability: 38.0,
      aiDiagnosis: "Gripper linear guide rail friction increase causing slight gripping force drop.",
      aiRecommendation: "Clean gripper linear guide rail & apply synthetic grease.",
    },
    maintenanceHistory: [
      { id: "WO-ABB-202", date: "2026-04-05", type: "Inspection", technician: "M. Vance", cost: "€320", details: "End-effector automatic tool changer locking pin inspection." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 36.2,
      vibration: 0.6,
      health: 96,
    })),
  },
  {
    id: "base-spindle",
    name: "Base Swivel Spindle",
    subsystem: "Axis 1 Rotation Base",
    partNumber: "ABB-BASE-SWIVEL High-Rigidity Swivel Bearing",
    healthScore: 95,
    status: "HEALTHY",
    temperature: 41.0,
    pressure: "N/A",
    rpm: "1,200 RPM",
    vibration: 0.9,
    current: "24.0 A",
    rulHours: 19000,
    failureProbability: 0.7,
    lastMaintenanceDate: "2025-12-10",
    nextMaintenanceDate: "2026-12-10",
    maintenanceStatus: "Base Swivel Runout 0.008 mm",
    position3d: [0, -0.4, 0],
    cameraOffset: [0.8, 0.4, 2.4],
    explodedOffset: [0, -1.2, 0],
    aiDiagnosis: "Robot base swivel bearing vibration low. Foundation bolt torque verified.",
    aiRecommendation: "Torque check base mounting bolts annually.",
    failureState: {
      healthScore: 62,
      status: "WARNING",
      temperature: 68.0,
      vibration: 4.5,
      rulHours: 350,
      failureProbability: 32.0,
      aiDiagnosis: "Base swivel bearing grease degradation causing elevated torque requirement.",
      aiRecommendation: "Purge base swivel bearing grease & re-torque mounting bolts.",
    },
    maintenanceHistory: [
      { id: "WO-ABB-203", date: "2025-12-10", type: "Preventive", technician: "ABB Field Ops", cost: "€780", details: "Base swivel bearing re-greasing & laser leveling." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 41.0,
      vibration: 0.9,
      health: 95,
    })),
  },
  {
    id: "servo-joint-drives",
    name: "Servo Joint Drives 1-6",
    subsystem: "Multi-Axis Synchronous Servo Drives",
    partNumber: "ABB-SERVO-PACK-IRB6700 6-Axis Drives",
    healthScore: 94,
    status: "HEALTHY",
    temperature: 46.5,
    pressure: "N/A",
    rpm: "3,100 RPM",
    vibration: 1.1,
    current: "48.0 A",
    rulHours: 14500,
    failureProbability: 1.2,
    lastMaintenanceDate: "2026-02-14",
    nextMaintenanceDate: "2026-08-14",
    maintenanceStatus: "Servo Drive Encoders Calibrated",
    position3d: [-0.8, 0.6, 0],
    cameraOffset: [0, 1.2, 2.4],
    explodedOffset: [-1.6, 0.6, 0],
    aiDiagnosis: "All 6 joint servo resolver feedback clean with zero signal loss.",
    aiRecommendation: "Perform routine brake holding torque check.",
    failureState: {
      healthScore: 50,
      status: "CRITICAL",
      temperature: 82.0,
      vibration: 7.0,
      rulHours: 50,
      failureProbability: 72.0,
      aiDiagnosis: "Joint 3 servo motor thermal overload causing joint axis fault trip.",
      aiRecommendation: "Inspect Joint 3 motor cooling fan & verify mechanical arm counter-weight balance.",
    },
    maintenanceHistory: [
      { id: "WO-ABB-204", date: "2026-02-14", type: "Inspection", technician: "M. Vance", cost: "€540", details: "6-Axis brake test & absolute encoder calibration." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 46.5,
      vibration: 1.1,
      health: 94,
    })),
  },
  {
    id: "safety-light-curtain",
    name: "Safety Light Curtain",
    subsystem: "Optoelectronic Safety Perimeter Barrier",
    partNumber: "SICK-deTec4-Core Safety Light Curtain",
    healthScore: 99,
    status: "HEALTHY",
    temperature: 30.0,
    pressure: "N/A",
    rpm: "N/A",
    vibration: 0.1,
    current: "1.5 A",
    rulHours: 25000,
    failureProbability: 0.1,
    lastMaintenanceDate: "2025-08-15",
    nextMaintenanceDate: "2026-08-15",
    maintenanceStatus: "Safety Interlock Dual Channel Closed",
    position3d: [-1.8, 0.8, 1.2],
    cameraOffset: [-1.0, 1.4, 2.6],
    explodedOffset: [-2.8, 0.8, 2.0],
    aiDiagnosis: "SICK safety light curtain optical beam response latency under 10 ms.",
    aiRecommendation: "Wipe optical lenses with soft anti-static cloth.",
    failureState: {
      healthScore: 80,
      status: "WARNING",
      temperature: 44.0,
      vibration: 1.0,
      rulHours: 900,
      failureProbability: 16.0,
      aiDiagnosis: "Optical receiver lens dust accumulation causing intermittent safety trips.",
      aiRecommendation: "Clean optical light curtain transmitter & receiver glass.",
    },
    maintenanceHistory: [
      { id: "WO-ABB-205", date: "2025-08-15", type: "Safety", technician: "Safety Dept", cost: "€250", details: "Annual SIL3 safety circuit audit & response time check." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 30.0,
      vibration: 0.1,
      health: 99,
    })),
  },
  {
    id: "teach-pendant",
    name: "Teach Pendant",
    subsystem: "ABB FlexPendant Operator Interface",
    partNumber: "ABB-FlexPendant-DSQC679 Touch Terminal",
    healthScore: 97,
    status: "HEALTHY",
    temperature: 32.0,
    pressure: "N/A",
    rpm: "N/A",
    vibration: 0.2,
    current: "2.0 A",
    rulHours: 20000,
    failureProbability: 0.3,
    lastMaintenanceDate: "2026-01-20",
    nextMaintenanceDate: "2027-01-20",
    maintenanceStatus: "RobotWare 6.12 Active",
    position3d: [2.2, 0.4, 1.0],
    cameraOffset: [2.8, 1.0, 2.4],
    explodedOffset: [3.4, 0.4, 1.8],
    aiDiagnosis: "ABB FlexPendant touchscreen and emergency stop button dual circuit nominal.",
    aiRecommendation: "Inspect teach pendant cable strain relief boot.",
    failureState: {
      healthScore: 84,
      status: "WARNING",
      temperature: 46.0,
      vibration: 1.1,
      rulHours: 850,
      failureProbability: 18.0,
      aiDiagnosis: "FlexPendant communication cable outer jacket abrasion.",
      aiRecommendation: "Replace FlexPendant 10m umbilical cable assembly.",
    },
    maintenanceHistory: [
      { id: "WO-ABB-206", date: "2026-01-20", type: "Firmware", technician: "ABB Automation", cost: "€420", details: "RobotWare OS patch update & E-stop switch check." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 32.0,
      vibration: 0.2,
      health: 97,
    })),
  },
  {
    id: "pneumatic-valve-manifold",
    name: "Pneumatic Valve Manifold",
    subsystem: "End-Effector Air & Vacuum Distribution",
    partNumber: "FESTO-VUVG Valve Terminal Cluster",
    healthScore: 93,
    status: "HEALTHY",
    temperature: 38.0,
    pressure: "8.0 bar",
    rpm: "N/A",
    vibration: 0.5,
    current: "8.5 A",
    rulHours: 13500,
    failureProbability: 1.5,
    lastMaintenanceDate: "2026-04-18",
    nextMaintenanceDate: "2026-10-18",
    maintenanceStatus: "Air Manifold Pressure 8.0 bar Nominal",
    position3d: [1.2, 0.2, -0.6],
    cameraOffset: [1.8, 0.8, 1.8],
    explodedOffset: [2.0, -0.4, -1.2],
    aiDiagnosis: "FESTO solenoid valve switching response time 8 ms.",
    aiRecommendation: "Check pneumatic filter bowl for condensate drain.",
    failureState: {
      healthScore: 54,
      status: "WARNING",
      temperature: 62.0,
      vibration: 3.8,
      pressure: "4.8 bar",
      rulHours: 140,
      failureProbability: 40.0,
      aiDiagnosis: "Solenoid valve station 4 spool seal wear causing pneumatic leakage.",
      aiRecommendation: "Replace solenoid valve spool cartridge & purge air filter bowl.",
    },
    maintenanceHistory: [
      { id: "WO-ABB-207", date: "2026-04-18", type: "Preventive", technician: "K. Meier", cost: "€280", details: "Pneumatic manifold pressure regulator zero & filter bowl drain." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 38.0,
      vibration: 0.5,
      health: 93,
    })),
  },
  {
    id: "control-cabinet-irc5",
    name: "IRC5 Control Cabinet",
    subsystem: "ABB IRC5 Robot Controller Main Cabinet",
    partNumber: "ABB-IRC5-MAIN Controller Drive Cabinet",
    healthScore: 96,
    status: "HEALTHY",
    temperature: 35.5,
    pressure: "N/A",
    rpm: "N/A",
    vibration: 0.3,
    current: "38.5 A",
    rulHours: 21000,
    failureProbability: 0.4,
    lastMaintenanceDate: "2026-02-01",
    nextMaintenanceDate: "2027-02-01",
    maintenanceStatus: "IRC5 Main Computer Active",
    position3d: [2.5, 0.6, 0],
    cameraOffset: [3.2, 1.2, 2.4],
    explodedOffset: [3.8, 0.6, 0],
    aiDiagnosis: "IRC5 controller main CPU temperature 35.5°C. Drive cooling blower fans clear.",
    aiRecommendation: "Clean cabinet air filter mat during annual shutdown.",
    failureState: {
      healthScore: 78,
      status: "WARNING",
      temperature: 58.0,
      vibration: 1.4,
      current: "52.0 A",
      rulHours: 650,
      failureProbability: 22.0,
      aiDiagnosis: "IRC5 drive cabinet internal heat sink dust buildup.",
      aiRecommendation: "Blow out controller heat sink fins using dry compressed air.",
    },
    maintenanceHistory: [
      { id: "WO-ABB-208", date: "2026-02-01", type: "Preventive", technician: "ABB Automation", cost: "€650", details: "IRC5 controller backup battery swap & fan filter cleaning." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 35.5,
      vibration: 0.3,
      health: 96,
    })),
  },
];

export const abbRoboticCellData = {
  id: "ABB-ROB-CELL-04",
  name: "ABB Robotic Assembly Cell",
  category: "Robotics & Assembly",
  location: "Robotic Cell Bay 4",
  manufacturer: "ABB",
  plant: "Stuttgart",
  serialNumber: "ABB-IRB6700-9940",
  status: "Running",
  healthScore: 92,
  runningHours: 11800,
  lastMaintenance: "2026-03-22",
  nextMaintenance: "2026-08-22",
  criticalAlerts: 0,
  components: abbRoboticCellComponents,
  sensors: {
    temperature: { value: 48.5, unit: "°C", baseline: 45.0, status: "NOMINAL" },
    rpm: { value: 3100, unit: "RPM", nominal: 3100, status: "NOMINAL" },
    vibration: { value: 1.4, unit: "mm/s", baseline: 1.2, status: "NOMINAL" },
    voltage: { value: 400.0, unit: "V AC", nominal: 400.0, status: "NOMINAL" },
    current: { value: 52.0, unit: "A", status: "NOMINAL" },
    power: { value: 38.5, unit: "kW", status: "NOMINAL" },
    pressure: { value: "8.0 bar", status: "NOMINAL" },
    efficiency: { value: 96.5, unit: "%", status: "OPTIMAL" },
    rulHours: 11800,
    healthScore: 92,
  },
  aiDiagnosis: {
    summary: "ABB IRB 6700 6-Axis Robot operating with 0.03 mm repeatability. RV reducer grease nominal.",
    recommendation: "Inspect Axis 2 reducer grease condition at next quarterly check window.",
    confidence: 97.1,
  },
  hotspots: [
    { id: "6axis-robot-arm", name: "6-Axis Robot Arm", status: "HEALTHY", temp: "48.5°C", vibration: "1.4 mm/s", position3d: [0, 0.6, 0] },
    { id: "end-effector-tooling", name: "End-Effector Tooling", status: "HEALTHY", temp: "36.2°C", vibration: "0.6 mm/s", position3d: [1.4, 1.2, 0] },
    { id: "base-spindle", name: "Base Swivel Spindle", status: "HEALTHY", temp: "41.0°C", vibration: "0.9 mm/s", position3d: [0, -0.4, 0] },
    { id: "teach-pendant", name: "Teach Pendant", status: "HEALTHY", temp: "32.0°C", vibration: "0.2 mm/s", position3d: [2.2, 0.4, 1.0] },
    { id: "control-cabinet-irc5", name: "IRC5 Control Cabinet", status: "HEALTHY", temp: "35.5°C", vibration: "0.3 mm/s", position3d: [2.5, 0.6, 0] },
  ],
  maintenanceHistory: [
    { id: "WO-ABB-201", date: "2026-03-22", type: "Preventive", technician: "ABB Field Ops", cost: "€1,450", details: "Robot arm RV reducer grease flushing & seal kit check." },
    { id: "WO-ABB-204", date: "2026-02-14", type: "Inspection", technician: "M. Vance", cost: "€540", details: "6-Axis brake test & absolute encoder calibration." },
  ],
  documents: [
    { id: "DOC-ABB-301", title: "ABB IRB 6700 Technical Reference Manual (Rev 5.1)", fileType: "PDF", size: "24.5 MB" },
    { id: "DOC-ABB-302", title: "IRC5 Controller Maintenance & Troubleshooting Guide", fileType: "PDF", size: "12.8 MB" },
  ],
};
