// Automotive Welding Cell Configuration

export const automotiveWeldingCellComponents = [
  {
    id: "weld-robot-arm",
    name: "KR500 Spot Welding Robot Arm",
    subsystem: "KUKA Heavy Payload Spot Welding Arm",
    partNumber: "KUKA-KR500-FORTEC 6-Axis Robot Arm",
    healthScore: 93,
    status: "HEALTHY",
    temperature: 54.0,
    pressure: "6.8 bar",
    rpm: "2,800 RPM",
    vibration: 1.2,
    current: "92.0 A",
    rulHours: 13800,
    failureProbability: 1.4,
    lastMaintenanceDate: "2026-03-08",
    nextMaintenanceDate: "2026-08-08",
    maintenanceStatus: "Axis 1-6 Servo Synchronized",
    position3d: [0, 0.6, 0],
    cameraOffset: [0.8, 1.4, 2.6],
    explodedOffset: [0, 1.8, 0],
    aiDiagnosis: "KUKA KR500 Fortec spot welding arm cycle repeatability 0.04 mm. Weld gun force 4500 N.",
    aiRecommendation: "Inspect robot arm wrist dress pack cable harness in 60 days.",
    failureState: {
      healthScore: 44,
      status: "CRITICAL",
      temperature: 92.0,
      vibration: 8.2,
      current: "128.0 A",
      rulHours: 35,
      failureProbability: 82.0,
      aiDiagnosis: "Weld robot axis 4 servo motor thermal breakdown during high duty cycle.",
      aiRecommendation: "Inspect axis 4 servo motor cooling fan & check dress pack cable tension.",
    },
    maintenanceHistory: [
      { id: "WO-WELD-901", date: "2026-03-08", type: "Preventive", technician: "KUKA Field Ops", cost: "€1,280", details: "Spot weld gun electrode tip dress & robot dress pack harness inspection." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 54.0,
      vibration: 1.2,
      health: 93,
    })),
  },
  {
    id: "laser-weld-head",
    name: "Laser Welding Head",
    subsystem: "Water-Cooled Fiber Laser Optics Head",
    partNumber: "HIGHYAG-BISO-3D Fiber Laser Weld Head",
    healthScore: 97,
    status: "HEALTHY",
    temperature: 32.0,
    pressure: "4.2 bar",
    rpm: "N/A",
    vibration: 0.4,
    current: "8.0 A",
    rulHours: 18000,
    failureProbability: 0.5,
    lastMaintenanceDate: "2026-04-12",
    nextMaintenanceDate: "2026-10-12",
    maintenanceStatus: "Laser Focus Seam Tracking Nominal",
    position3d: [1.2, 1.2, 0],
    cameraOffset: [1.8, 1.8, 2.2],
    explodedOffset: [2.4, 2.0, 0],
    aiDiagnosis: "HIGHYAG 3D laser seam tracking accuracy 0.05 mm. Protective glass clean.",
    aiRecommendation: "Replace laser protective cover slide every 500 operating hours.",
    failureState: {
      healthScore: 58,
      status: "WARNING",
      temperature: 58.0,
      vibration: 2.8,
      rulHours: 180,
      failureProbability: 38.0,
      aiDiagnosis: "Laser head protective slide glass spatter contamination reducing laser power density.",
      aiRecommendation: "Swap laser protective slide glass cassette & clean seam tracking sensor.",
    },
    maintenanceHistory: [
      { id: "WO-WELD-902", date: "2026-04-12", type: "Preventive", technician: "A. Wagner", cost: "€350", details: "Laser head protective slide glass replacement & optic beam calibration." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 32.0,
      vibration: 0.4,
      health: 97,
    })),
  },
  {
    id: "welding-power-source",
    name: "Inverter Welding Power Source",
    subsystem: "MFDC 1000Hz Spot Welding Inverter",
    partNumber: "BOSCH-REXROTH-PSI-6000 MFDC Inverter",
    healthScore: 96,
    status: "HEALTHY",
    temperature: 46.0,
    pressure: "N/A",
    rpm: "N/A",
    vibration: 0.3,
    current: "92.0 A",
    rulHours: 21000,
    failureProbability: 0.6,
    lastMaintenanceDate: "2026-01-18",
    nextMaintenanceDate: "2027-01-18",
    maintenanceStatus: "MFDC Inverter Secondary Current 18 kA",
    position3d: [2.2, 0.4, 0],
    cameraOffset: [2.8, 1.0, 2.4],
    explodedOffset: [3.4, 0.4, 0],
    aiDiagnosis: "Bosch Rexroth PSI 6000 MFDC inverter weld pulse duration 120 ms steady.",
    aiRecommendation: "Check primary thyristor cooling water flow.",
    failureState: {
      healthScore: 78,
      status: "WARNING",
      temperature: 68.0,
      vibration: 1.4,
      current: "115.0 A",
      rulHours: 600,
      failureProbability: 22.0,
      aiDiagnosis: "Inverter power cabinet internal cooling heat sink temp rise.",
      aiRecommendation: "Clean PSI 6000 inverter cabinet cooling fins & check water flow.",
    },
    maintenanceHistory: [
      { id: "WO-WELD-903", date: "2026-01-18", type: "Firmware", technician: "Bosch Automation", cost: "€580", details: "Weld controller software update & secondary current calibration." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 46.0,
      vibration: 0.3,
      health: 96,
    })),
  },
  {
    id: "water-chiller",
    name: "Water Cooling Chiller",
    subsystem: "Closed-Loop Laser & Spot Weld Chiller",
    partNumber: "RITTAL-CHILLER-15KW Closed-Loop Unit",
    healthScore: 94,
    status: "HEALTHY",
    temperature: 18.0,
    pressure: "4.8 bar",
    rpm: "1,450 RPM",
    vibration: 0.8,
    current: "24.0 A",
    rulHours: 15500,
    failureProbability: 1.1,
    lastMaintenanceDate: "2026-05-01",
    nextMaintenanceDate: "2026-11-01",
    maintenanceStatus: "Cooling Water Temp 18.0°C Nominal",
    position3d: [2.2, 0.4, -1.0],
    cameraOffset: [2.8, 1.0, 1.8],
    explodedOffset: [3.4, 0.4, -1.8],
    aiDiagnosis: "Rittal 15kW chiller cooling water temp 18.0°C ± 0.5°C. Flow rate 45 L/min.",
    aiRecommendation: "Check glycol coolant concentration level.",
    failureState: {
      healthScore: 50,
      status: "CRITICAL",
      temperature: 38.0,
      vibration: 5.2,
      pressure: "2.1 bar",
      rulHours: 48,
      failureProbability: 72.0,
      aiDiagnosis: "Chiller refrigerant compressor pressure loss causing cooling water temp rise.",
      aiRecommendation: "Inspect Rittal chiller refrigerant line & clean condenser fins.",
    },
    maintenanceHistory: [
      { id: "WO-WELD-904", date: "2026-05-01", type: "Preventive", technician: "H. Schmidt", cost: "€420", details: "Chiller glycol fluid check & condenser fin wash." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 18.0,
      vibration: 0.8,
      health: 94,
    })),
  },
  {
    id: "fume-extractor",
    name: "Fume Extraction Hood",
    subsystem: "Overhead Weld Fume Filter Hood",
    partNumber: "KEMPER-SYSTEM-8000 High-Vacuum Extractor",
    healthScore: 95,
    status: "HEALTHY",
    temperature: 34.0,
    pressure: "N/A",
    rpm: "2,800 RPM",
    vibration: 0.7,
    current: "18.0 A",
    rulHours: 17000,
    failureProbability: 0.8,
    lastMaintenanceDate: "2026-02-25",
    nextMaintenanceDate: "2026-08-25",
    maintenanceStatus: "Fume Extraction Airflow 4200 m³/h",
    position3d: [0, 2.0, 0],
    cameraOffset: [0.8, 2.6, 2.4],
    explodedOffset: [0, 3.2, 0],
    aiDiagnosis: "Kemper weld fume extraction fan differential pressure 0.4 kPa nominal.",
    aiRecommendation: "Perform automatic pulse-jet filter cartridge cleaning.",
    failureState: {
      healthScore: 62,
      status: "WARNING",
      temperature: 52.0,
      vibration: 4.0,
      rulHours: 280,
      failureProbability: 32.0,
      aiDiagnosis: "Fume extractor main PTFE filter cartridge particulate loading.",
      aiRecommendation: "Trigger pulse-jet filter reverse cleaning & inspect dust bin.",
    },
    maintenanceHistory: [
      { id: "WO-WELD-905", date: "2026-02-25", type: "Preventive", technician: "L. Weber", cost: "€320", details: "Fume extraction PTFE filter cartridge pulse cleaning & dust bin empty." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 34.0,
      vibration: 0.7,
      health: 95,
    })),
  },
  {
    id: "clamping-fixture",
    name: "Pneumatic Body Clamping Fixtures",
    subsystem: "Automotive Body Side Geometry Fixture",
    partNumber: "TUENKERS-CLAMP-100 Heavy Pneumatic Clamps",
    healthScore: 96,
    status: "HEALTHY",
    temperature: 36.0,
    pressure: "6.8 bar",
    rpm: "N/A",
    vibration: 0.5,
    current: "4.0 A",
    rulHours: 19000,
    failureProbability: 0.6,
    lastMaintenanceDate: "2026-03-20",
    nextMaintenanceDate: "2026-09-20",
    maintenanceStatus: "Tuenkers Clamp Toggle Lock Verified",
    position3d: [-1.2, 0.4, 0.8],
    cameraOffset: [-0.4, 1.0, 2.4],
    explodedOffset: [-1.8, 0.4, 1.4],
    aiDiagnosis: "Tuenkers pneumatic body toggle clamp positioning sensors 100% closed.",
    aiRecommendation: "Grease clamp toggle joint pins quarterly.",
    failureState: {
      healthScore: 68,
      status: "WARNING",
      temperature: 48.0,
      vibration: 2.2,
      pressure: "4.5 bar",
      rulHours: 350,
      failureProbability: 25.0,
      aiDiagnosis: "Pneumatic clamp 3 inductive proximity switch sensor signal delay.",
      aiRecommendation: "Clean clamping pin proximity switch face & check air cylinder.",
    },
    maintenanceHistory: [
      { id: "WO-WELD-906", date: "2026-03-20", type: "Preventive", technician: "K. Meier", cost: "€210", details: "Pneumatic clamp toggle pin greasing & proximity switch test." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 36.0,
      vibration: 0.5,
      health: 96,
    })),
  },
  {
    id: "safety-barrier",
    name: "Safety Interlock Barrier",
    subsystem: "Perimeter Flash Shield & Interlock Fence",
    partNumber: "KUKA-WELD-SHIELD Safety Barrier Enclosure",
    healthScore: 99,
    status: "HEALTHY",
    temperature: 28.0,
    pressure: "N/A",
    rpm: "N/A",
    vibration: 0.1,
    current: "0.5 A",
    rulHours: 30000,
    failureProbability: 0.0,
    lastMaintenanceDate: "2025-07-15",
    nextMaintenanceDate: "2026-07-15",
    maintenanceStatus: "Weld Flash Shield & Gate Dual Loop Closed",
    position3d: [0, 0.6, 1.8],
    cameraOffset: [0.8, 1.2, 3.0],
    explodedOffset: [0, 0.6, 2.8],
    aiDiagnosis: "Automotive welding cell perimeter flash enclosure & interlock door nominal.",
    aiRecommendation: "No maintenance required.",
    failureState: {
      healthScore: 85,
      status: "WARNING",
      temperature: 35.0,
      vibration: 0.8,
      rulHours: 1200,
      failureProbability: 12.0,
      aiDiagnosis: "Weld flash door safety RFID interlock key mis-alignment.",
      aiRecommendation: "Re-align safety door catch pin.",
    },
    maintenanceHistory: [
      { id: "WO-WELD-907", date: "2025-07-15", type: "Safety", technician: "Safety Dept", cost: "€180", details: "Weld flash safety curtain inspection & gate interlock test." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 28.0,
      vibration: 0.1,
      health: 99,
    })),
  },
  {
    id: "weld-teach-console",
    name: "Smart Welding Teach Console",
    subsystem: "KUKA smartPAD Industrial Pendant",
    partNumber: "KUKA-smartPAD-2 Touch Controller",
    healthScore: 98,
    status: "HEALTHY",
    temperature: 31.0,
    pressure: "N/A",
    rpm: "N/A",
    vibration: 0.2,
    current: "1.8 A",
    rulHours: 22000,
    failureProbability: 0.2,
    lastMaintenanceDate: "2026-01-10",
    nextMaintenanceDate: "2027-01-10",
    maintenanceStatus: "KUKA System Software KSS 8.6 Active",
    position3d: [-1.8, 0.4, 1.0],
    cameraOffset: [-1.0, 1.0, 2.4],
    explodedOffset: [-2.6, 0.4, 1.6],
    aiDiagnosis: "KUKA smartPAD-2 touch console & 6D space mouse responsive.",
    aiRecommendation: "Inspect smartPAD cable connector boot.",
    failureState: {
      healthScore: 84,
      status: "WARNING",
      temperature: 45.0,
      vibration: 1.0,
      rulHours: 850,
      failureProbability: 18.0,
      aiDiagnosis: "smartPAD cable boot strain relief wear.",
      aiRecommendation: "Replace smartPAD umbilical cable connector boot.",
    },
    maintenanceHistory: [
      { id: "WO-WELD-908", date: "2026-01-10", type: "Firmware", technician: "KUKA Field Ops", cost: "€380", details: "KSS 8.6 software patch update & E-stop circuit check." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 31.0,
      vibration: 0.2,
      health: 98,
    })),
  },
];

export const automotiveWeldingCellData = {
  id: "KUKA-WELD-CELL",
  name: "Automotive Welding Cell",
  category: "Robotic Welding",
  location: "Automotive Body Shop - Robot Cell 12",
  manufacturer: "KUKA",
  plant: "Dresden",
  serialNumber: "KUKA-KR500-WELD",
  status: "Running",
  healthScore: 93,
  runningHours: 13800,
  lastMaintenance: "2026-03-08",
  nextMaintenance: "2026-08-08",
  criticalAlerts: 0,
  components: automotiveWeldingCellComponents,
  sensors: {
    temperature: { value: 54.0, unit: "°C", baseline: 50.0, status: "NOMINAL" },
    rpm: { value: 2800, unit: "RPM", nominal: 2800, status: "NOMINAL" },
    vibration: { value: 1.2, unit: "mm/s", baseline: 1.0, status: "NOMINAL" },
    voltage: { value: 400.0, unit: "V AC", nominal: 400.0, status: "NOMINAL" },
    current: { value: 92.0, unit: "A", status: "NOMINAL" },
    power: { value: 65.0, unit: "kW", status: "NOMINAL" },
    pressure: { value: "6.8 bar", status: "NOMINAL" },
    efficiency: { value: 95.1, unit: "%", status: "OPTIMAL" },
    rulHours: 13800,
    healthScore: 93,
  },
  aiDiagnosis: {
    summary: "Automated Robotic Welding Cell operating optimal. KUKA KR500 spot weld gun force 4500 N, laser seam tracking accuracy 0.05 mm.",
    recommendation: "Inspect robot arm dress pack harness and check water chiller glycol level at scheduled maintenance window.",
    confidence: 97.9,
  },
  hotspots: [
    { id: "weld-robot-arm", name: "KR500 Spot Welding Robot Arm", status: "HEALTHY", temp: "54.0°C", vibration: "1.2 mm/s", position3d: [0, 0.6, 0] },
    { id: "laser-weld-head", name: "Laser Welding Head", status: "HEALTHY", temp: "32.0°C", vibration: "0.4 mm/s", position3d: [1.2, 1.2, 0] },
    { id: "welding-power-source", name: "Inverter Welding Power Source", status: "HEALTHY", temp: "46.0°C", vibration: "0.3 mm/s", position3d: [2.2, 0.4, 0] },
    { id: "water-chiller", name: "Water Cooling Chiller", status: "HEALTHY", temp: "18.0°C", vibration: "0.8 mm/s", position3d: [2.2, 0.4, -1.0] },
    { id: "fume-extractor", name: "Fume Extraction Hood", status: "HEALTHY", temp: "34.0°C", vibration: "0.7 mm/s", position3d: [0, 2.0, 0] },
  ],
  maintenanceHistory: [
    { id: "WO-WELD-901", date: "2026-03-08", type: "Preventive", technician: "KUKA Field Ops", cost: "€1,280", details: "Spot weld gun electrode tip dress & robot dress pack harness inspection." },
    { id: "WO-WELD-904", date: "2026-05-01", type: "Preventive", technician: "H. Schmidt", cost: "€420", details: "Chiller glycol fluid check & condenser fin wash." },
  ],
  documents: [
    { id: "DOC-WELD-1001", title: "KUKA KR500 Fortec Robotic Welding Cell Technical Manual", fileType: "PDF", size: "28.9 MB" },
    { id: "DOC-WELD-1002", title: "Bosch Rexroth MFDC Inverter Welding SOP-WELD-02", fileType: "PDF", size: "11.4 MB" },
  ],
};
