// Bosch Smart Manufacturing Cell Configuration

export const boschSmartCellComponents = [
  {
    id: "cobot-arm",
    name: "Collaborative Robot Arm",
    subsystem: "Bosch APAS Cobot Assembly Arm",
    partNumber: "BOSCH-APAS-COBOT 6-Axis Sensitive Arm",
    healthScore: 98,
    status: "HEALTHY",
    temperature: 36.4,
    pressure: "N/A",
    rpm: "1,800 RPM",
    vibration: 0.6,
    current: "28.5 A",
    rulHours: 21500,
    failureProbability: 0.4,
    lastMaintenanceDate: "2026-06-01",
    nextMaintenanceDate: "2026-11-01",
    maintenanceStatus: "Capacitive Safety Skin Active",
    position3d: [0, 0.6, 0],
    cameraOffset: [0.8, 1.4, 2.4],
    explodedOffset: [0, 1.8, 0],
    aiDiagnosis: "Bosch APAS cobot capacitive collision avoidance skin response 100% compliant.",
    aiRecommendation: "Perform joint torque sensor calibration at 12-month interval.",
    failureState: {
      healthScore: 60,
      status: "WARNING",
      temperature: 68.0,
      vibration: 4.8,
      rulHours: 280,
      failureProbability: 35.0,
      aiDiagnosis: "Cobot joint 2 capacitive sensor skin sensitivity drift.",
      aiRecommendation: "Recalibrate APAS capacitive skin proximity threshold.",
    },
    maintenanceHistory: [
      { id: "WO-BOS-301", date: "2026-06-01", type: "Preventive", technician: "Bosch Rexroth Ops", cost: "€650", details: "APAS cobot skin sensitivity test & joint software update." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 36.4,
      vibration: 0.6,
      health: 98,
    })),
  },
  {
    id: "smart-gripper",
    name: "Smart Pneumatic Gripper",
    subsystem: "Adaptive Mechatronic Parallel Gripper",
    partNumber: "BOSCH-REX-GRIPPER Parallel Servo Gripper",
    healthScore: 97,
    status: "HEALTHY",
    temperature: 34.0,
    pressure: "5.5 bar",
    rpm: "N/A",
    vibration: 0.4,
    current: "8.0 A",
    rulHours: 19500,
    failureProbability: 0.5,
    lastMaintenanceDate: "2026-05-10",
    nextMaintenanceDate: "2026-11-10",
    maintenanceStatus: "Force-Sensing Finger Gripper Nominal",
    position3d: [1.2, 1.0, 0],
    cameraOffset: [1.8, 1.6, 2.2],
    explodedOffset: [2.4, 1.8, 0],
    aiDiagnosis: "Smart gripper jaw tactile force feedback calibrated at 320 N ± 1 N.",
    aiRecommendation: "No maintenance required.",
    failureState: {
      healthScore: 56,
      status: "WARNING",
      temperature: 58.0,
      vibration: 3.8,
      rulHours: 190,
      failureProbability: 40.0,
      aiDiagnosis: "Gripper finger strain gauge offset drift causing force warning.",
      aiRecommendation: "Perform zero-point tare calibration on gripper finger strain gauges.",
    },
    maintenanceHistory: [
      { id: "WO-BOS-302", date: "2026-05-10", type: "Inspection", technician: "A. Wagner", cost: "€210", details: "Gripper force sensor zero tare & finger rubber pad swap." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 34.0,
      vibration: 0.4,
      health: 97,
    })),
  },
  {
    id: "modular-conveyor",
    name: "Modular Track Conveyor",
    subsystem: "Rexroth TS 2plus Transfer System",
    partNumber: "BOSCH-TS2-TRANSFER Workpiece Pallet Conveyor",
    healthScore: 96,
    status: "HEALTHY",
    temperature: 38.2,
    pressure: "N/A",
    rpm: "1,200 RPM",
    vibration: 0.7,
    current: "18.0 A",
    rulHours: 18000,
    failureProbability: 0.8,
    lastMaintenanceDate: "2026-04-15",
    nextMaintenanceDate: "2026-10-15",
    maintenanceStatus: "Workpiece Pallet Stop Gate Nominal",
    position3d: [-2.0, 0.2, 0],
    cameraOffset: [-1.2, 1.0, 2.4],
    explodedOffset: [-3.2, 0.2, 0],
    aiDiagnosis: "TS 2plus transfer chain wear index under 0.05%. Pallet stop cushions smooth.",
    aiRecommendation: "Apply synthetic chain oil at 60-day interval.",
    failureState: {
      healthScore: 54,
      status: "CRITICAL",
      temperature: 72.0,
      vibration: 6.2,
      rulHours: 80,
      failureProbability: 68.0,
      aiDiagnosis: "Transfer track drive chain pitch elongation causing pallet alignment jam.",
      aiRecommendation: "Adjust track drive chain tensioner & lubricate guide rails.",
    },
    maintenanceHistory: [
      { id: "WO-BOS-303", date: "2026-04-15", type: "Preventive", technician: "L. Weber", cost: "€380", details: "TS 2plus chain lube & pneumatic pallet stop valve test." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 38.2,
      vibration: 0.7,
      health: 96,
    })),
  },
  {
    id: "safety-cage",
    name: "Perimeter Safety Cage",
    subsystem: "Aluminum Profile Safety Barrier & Interlock",
    partNumber: "BOSCH-SAFE-FENCE Extruded Aluminum Cage",
    healthScore: 99,
    status: "HEALTHY",
    temperature: 28.0,
    pressure: "N/A",
    rpm: "N/A",
    vibration: 0.1,
    current: "0.5 A",
    rulHours: 30000,
    failureProbability: 0.0,
    lastMaintenanceDate: "2025-07-20",
    nextMaintenanceDate: "2026-07-20",
    maintenanceStatus: "Safety Gate Interlock Switch Closed",
    position3d: [0, 0.6, 2.0],
    cameraOffset: [0.8, 1.4, 3.2],
    explodedOffset: [0, 0.6, 3.2],
    aiDiagnosis: "Bosch Rexroth eco-safe profile frame structure and door interlock 100% secure.",
    aiRecommendation: "No action required.",
    failureState: {
      healthScore: 85,
      status: "WARNING",
      temperature: 35.0,
      vibration: 0.8,
      rulHours: 1200,
      failureProbability: 12.0,
      aiDiagnosis: "Safety gate RFID interlock actuator slight mechanical mis-alignment.",
      aiRecommendation: "Re-align safety door RFID catch plate.",
    },
    maintenanceHistory: [
      { id: "WO-BOS-304", date: "2025-07-20", type: "Safety", technician: "Safety Dept", cost: "€150", details: "Safety fence mechanical integrity check & RFID door interlock test." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 28.0,
      vibration: 0.1,
      health: 99,
    })),
  },
  {
    id: "plc-cabinet",
    name: "Rexroth PLC Cabinet",
    subsystem: "IndraDrive & ctrlX Automation Controller",
    partNumber: "BOSCH-ctrlX-CORE Industrial PC & PLC",
    healthScore: 98,
    status: "HEALTHY",
    temperature: 33.5,
    pressure: "N/A",
    rpm: "N/A",
    vibration: 0.2,
    current: "14.5 A",
    rulHours: 24000,
    failureProbability: 0.2,
    lastMaintenanceDate: "2026-01-15",
    nextMaintenanceDate: "2027-01-15",
    maintenanceStatus: "ctrlX OS v1.20 Active",
    position3d: [2.2, 0.6, 0],
    cameraOffset: [2.8, 1.2, 2.2],
    explodedOffset: [3.4, 0.6, 0],
    aiDiagnosis: "ctrlX CORE Linux realtime automation engine cycle latency 0.5 ms.",
    aiRecommendation: "Inspect cabinet cooling fan dust filter mat.",
    failureState: {
      healthScore: 82,
      status: "WARNING",
      temperature: 54.0,
      vibration: 1.2,
      rulHours: 850,
      failureProbability: 18.0,
      aiDiagnosis: "Control cabinet internal heat buildup due to restricted filter mat.",
      aiRecommendation: "Clean ctrlX cabinet filter mat & check 24V supply voltage.",
    },
    maintenanceHistory: [
      { id: "WO-BOS-305", date: "2026-01-15", type: "Firmware", technician: "Bosch Automation", cost: "€520", details: "ctrlX OS software update & OPC-UA node configuration." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 33.5,
      vibration: 0.2,
      health: 98,
    })),
  },
  {
    id: "vision-camera-3d",
    name: "3D Vision Camera",
    subsystem: "Random Bin Picking & Quality Inspection Camera",
    partNumber: "BOSCH-3D-VISION Stereo Sensor Tower",
    healthScore: 97,
    status: "HEALTHY",
    temperature: 32.0,
    pressure: "N/A",
    rpm: "N/A",
    vibration: 0.1,
    current: "3.2 A",
    rulHours: 22000,
    failureProbability: 0.3,
    lastMaintenanceDate: "2025-11-12",
    nextMaintenanceDate: "2026-11-12",
    maintenanceStatus: "Stereo Point-Cloud Calibrated",
    position3d: [0, 1.8, 0],
    cameraOffset: [0.6, 2.4, 2.0],
    explodedOffset: [0, 2.8, 0],
    aiDiagnosis: "3D point-cloud reconstruction speed 120 ms per workpiece scan.",
    aiRecommendation: "No maintenance required.",
    failureState: {
      healthScore: 84,
      status: "WARNING",
      temperature: 46.0,
      vibration: 1.0,
      rulHours: 900,
      failureProbability: 16.0,
      aiDiagnosis: "Stereo camera projector LED intensity reduction.",
      aiRecommendation: "Calibrate stereo projector LED illumination gain.",
    },
    maintenanceHistory: [
      { id: "WO-BOS-306", date: "2025-11-12", type: "Calibration", technician: "Bosch Rexroth", cost: "€480", details: "3D stereo point-cloud grid calibration & projector test." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 32.0,
      vibration: 0.1,
      health: 97,
    })),
  },
  {
    id: "inspection-station",
    name: "Inspection Station",
    subsystem: "Automated Laser Metrology Gauge",
    partNumber: "BOSCH-LASER-METRO High-Precision Gauge",
    healthScore: 99,
    status: "HEALTHY",
    temperature: 30.5,
    pressure: "N/A",
    rpm: "N/A",
    vibration: 0.2,
    current: "4.0 A",
    rulHours: 26000,
    failureProbability: 0.1,
    lastMaintenanceDate: "2026-02-10",
    nextMaintenanceDate: "2027-02-10",
    maintenanceStatus: "Gauge Repeatability 0.001 mm",
    position3d: [-1.2, 0.4, 0.8],
    cameraOffset: [-0.6, 1.0, 2.2],
    explodedOffset: [-1.8, 0.4, 1.4],
    aiDiagnosis: "Laser displacement sensor measurement variance under 0.5 um.",
    aiRecommendation: "Verify master gauge block baseline every 6 months.",
    failureState: {
      healthScore: 88,
      status: "WARNING",
      temperature: 42.0,
      vibration: 0.8,
      rulHours: 1100,
      failureProbability: 12.0,
      aiDiagnosis: "Laser glass window micro-particulate coating.",
      aiRecommendation: "Clean laser metrology sensor glass with optical swab.",
    },
    maintenanceHistory: [
      { id: "WO-BOS-307", date: "2026-02-10", type: "Calibration", technician: "Metrology Dept", cost: "€390", details: "Laser metrology master gauge block verification." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 30.5,
      vibration: 0.2,
      health: 99,
    })),
  },
  {
    id: "fixture-table",
    name: "Precision Fixture Table",
    subsystem: "Pneumatic Workpiece Clamping Table",
    partNumber: "BOSCH-FIXTURE-TAB Zero-Point Clamping System",
    healthScore: 96,
    status: "HEALTHY",
    temperature: 31.0,
    pressure: "5.5 bar",
    rpm: "N/A",
    vibration: 0.3,
    current: "2.0 A",
    rulHours: 20000,
    failureProbability: 0.5,
    lastMaintenanceDate: "2026-03-05",
    nextMaintenanceDate: "2026-09-05",
    maintenanceStatus: "Zero-Point Clamping Force 12 kN",
    position3d: [1.2, 0.2, 0.8],
    cameraOffset: [1.8, 0.8, 2.0],
    explodedOffset: [2.0, 0.2, 1.4],
    aiDiagnosis: "Zero-point clamping pin retention force 12 kN verified nominal.",
    aiRecommendation: "Blow out clamping pin recesses with compressed air.",
    failureState: {
      healthScore: 70,
      status: "WARNING",
      temperature: 45.0,
      vibration: 2.1,
      pressure: "3.8 bar",
      rulHours: 420,
      failureProbability: 28.0,
      aiDiagnosis: "Clamping pin air purge seal leak causing clamping pressure drop.",
      aiRecommendation: "Replace zero-point clamping pin O-ring seals.",
    },
    maintenanceHistory: [
      { id: "WO-BOS-308", date: "2026-03-05", type: "Preventive", technician: "K. Meier", cost: "€220", details: "Zero-point clamping pin seal replacement & pressure check." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 31.0,
      vibration: 0.3,
      health: 96,
    })),
  },
];

export const boschSmartCellData = {
  id: "BOSCH-SMART-CELL",
  name: "Bosch Smart Manufacturing Cell",
  category: "Smart Automation",
  location: "Smart Factory Floor - Module 1",
  manufacturer: "Bosch",
  plant: "Stuttgart",
  serialNumber: "BOSCH-REX-4001",
  status: "Running",
  healthScore: 98,
  runningHours: 21500,
  lastMaintenance: "2026-06-01",
  nextMaintenance: "2026-11-01",
  criticalAlerts: 0,
  components: boschSmartCellComponents,
  sensors: {
    temperature: { value: 36.4, unit: "°C", baseline: 35.0, status: "NOMINAL" },
    rpm: { value: 1800, unit: "RPM", nominal: 1800, status: "NOMINAL" },
    vibration: { value: 0.6, unit: "mm/s", baseline: 0.5, status: "NOMINAL" },
    voltage: { value: 400.0, unit: "V AC", nominal: 400.0, status: "NOMINAL" },
    current: { value: 28.5, unit: "A", status: "NOMINAL" },
    power: { value: 22.0, unit: "kW", status: "NOMINAL" },
    pressure: { value: "5.5 bar", status: "NOMINAL" },
    efficiency: { value: 98.9, unit: "%", status: "OPTIMAL" },
    rulHours: 21500,
    healthScore: 98,
  },
  aiDiagnosis: {
    summary: "Industry 4.0 Smart Manufacturing Cell operating at 98.9% overall efficiency. APAS Cobot collision skin 100% pass.",
    recommendation: "Perform joint torque sensor calibration at scheduled 12-month window.",
    confidence: 99.1,
  },
  hotspots: [
    { id: "cobot-arm", name: "Collaborative Robot Arm", status: "HEALTHY", temp: "36.4°C", vibration: "0.6 mm/s", position3d: [0, 0.6, 0] },
    { id: "smart-gripper", name: "Smart Pneumatic Gripper", status: "HEALTHY", temp: "34.0°C", vibration: "0.4 mm/s", position3d: [1.2, 1.0, 0] },
    { id: "modular-conveyor", name: "Modular Track Conveyor", status: "HEALTHY", temp: "38.2°C", vibration: "0.7 mm/s", position3d: [-2.0, 0.2, 0] },
    { id: "plc-cabinet", name: "Rexroth PLC Cabinet", status: "HEALTHY", temp: "33.5°C", vibration: "0.2 mm/s", position3d: [2.2, 0.6, 0] },
    { id: "vision-camera-3d", name: "3D Vision Camera", status: "HEALTHY", temp: "32.0°C", vibration: "0.1 mm/s", position3d: [0, 1.8, 0] },
  ],
  maintenanceHistory: [
    { id: "WO-BOS-301", date: "2026-06-01", type: "Preventive", technician: "Bosch Rexroth Ops", cost: "€650", details: "APAS cobot skin sensitivity test & joint software update." },
    { id: "WO-BOS-305", date: "2026-01-15", type: "Firmware", technician: "Bosch Automation", cost: "€520", details: "ctrlX OS software update & OPC-UA node configuration." },
  ],
  documents: [
    { id: "DOC-BOS-401", title: "Bosch Rexroth ctrlX Automation System Manual", fileType: "PDF", size: "28.4 MB" },
    { id: "DOC-BOS-402", title: "APAS Cobot Safety & Calibration Guide", fileType: "PDF", size: "15.2 MB" },
  ],
};
