// Industrial Air Compressor Configuration

export const industrialAirCompressorComponents = [
  {
    id: "compressor-motor",
    name: "200kW Compressor Motor",
    subsystem: "Main Induction Drive Motor",
    partNumber: "IR-MOTOR-200KW 400V Induction Motor",
    healthScore: 95,
    status: "HEALTHY",
    temperature: 52.0,
    pressure: "N/A",
    rpm: "3,600 RPM",
    vibration: 1.3,
    current: "85.0 A",
    rulHours: 15400,
    failureProbability: 1.2,
    lastMaintenanceDate: "2026-05-02",
    nextMaintenanceDate: "2026-10-02",
    maintenanceStatus: "Motor Insulation Resistance > 100 Mohm",
    position3d: [-2.2, 0.4, 0],
    cameraOffset: [-1.4, 1.2, 2.6],
    explodedOffset: [-3.8, 0.4, 0],
    aiDiagnosis: "200kW compressor motor winding temp steady at 52.0°C. Current draw nominal.",
    aiRecommendation: "Perform bearing greasing with synthetic grease in 90 days.",
    failureState: {
      healthScore: 42,
      status: "CRITICAL",
      temperature: 94.0,
      vibration: 8.5,
      current: "115.0 A",
      rulHours: 32,
      failureProbability: 84.0,
      aiDiagnosis: "Compressor motor drive bearing inner-race spalling causing vibration & over-temp.",
      aiRecommendation: "Replace compressor motor drive-end bearing and check shaft coupling.",
    },
    maintenanceHistory: [
      { id: "WO-COMP-501", date: "2026-05-02", type: "Preventive", technician: "H. Schmidt", cost: "€580", details: "Compressor motor bearing grease replenishment & current check." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 52.0,
      vibration: 1.3,
      health: 95,
    })),
  },
  {
    id: "cooling-fan",
    name: "Forced Air Cooling Fan",
    subsystem: "Oil Cooler Radiator Fan",
    partNumber: "IR-COOL-FAN-450 High-Volume Blower",
    healthScore: 96,
    status: "HEALTHY",
    temperature: 36.0,
    pressure: "N/A",
    rpm: "2,400 RPM",
    vibration: 0.7,
    current: "12.0 A",
    rulHours: 18000,
    failureProbability: 0.6,
    lastMaintenanceDate: "2025-11-20",
    nextMaintenanceDate: "2026-11-20",
    maintenanceStatus: "Radiator Airflow 22.0 m/s",
    position3d: [-1.0, 0.8, 0],
    cameraOffset: [-0.2, 1.4, 2.4],
    explodedOffset: [-1.8, 1.6, 0],
    aiDiagnosis: "Cooling fan impeller clean with zero dust fouling. Heat exchanger Delta T nominal.",
    aiRecommendation: "Clean radiator fins during monthly washdown.",
    failureState: {
      healthScore: 62,
      status: "WARNING",
      temperature: 68.0,
      vibration: 4.6,
      rulHours: 220,
      failureProbability: 35.0,
      aiDiagnosis: "Cooling fan belt slip causing reduced radiator airflow velocity.",
      aiRecommendation: "Adjust fan belt tensioner & wash radiator cooling fins.",
    },
    maintenanceHistory: [
      { id: "WO-COMP-502", date: "2025-11-20", type: "Preventive", technician: "L. Weber", cost: "€280", details: "Cooling fan belt swap & radiator coil wash." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 36.0,
      vibration: 0.7,
      health: 96,
    })),
  },
  {
    id: "air-filter",
    name: "Heavy-Duty Air Filter",
    subsystem: "Compressor Air Intake Filtration",
    partNumber: "DONALDSON-P-500 Heavy Dust Filter",
    healthScore: 93,
    status: "HEALTHY",
    temperature: 28.5,
    pressure: "0.02 bar drop",
    rpm: "N/A",
    vibration: 0.2,
    current: "N/A",
    rulHours: 12000,
    failureProbability: 1.5,
    lastMaintenanceDate: "2026-04-12",
    nextMaintenanceDate: "2026-10-12",
    maintenanceStatus: "Air Filter Differential Pressure Nominal",
    position3d: [-0.2, 1.2, 0],
    cameraOffset: [0.6, 1.8, 2.4],
    explodedOffset: [-0.2, 2.4, 0],
    aiDiagnosis: "Air filter differential pressure 0.02 bar. Dust filtration efficiency 99.9%.",
    aiRecommendation: "Replace intake filter cartridge every 2000 operating hours.",
    failureState: {
      healthScore: 54,
      status: "WARNING",
      temperature: 45.0,
      vibration: 2.2,
      pressure: "0.15 bar drop",
      rulHours: 150,
      failureProbability: 42.0,
      aiDiagnosis: "Intake air filter restriction causing compressor volumetric efficiency drop.",
      aiRecommendation: "Replace Donaldson air filter cartridge immediately.",
    },
    maintenanceHistory: [
      { id: "WO-COMP-503", date: "2026-04-12", type: "Preventive", technician: "A. Wagner", cost: "€180", details: "Intake air filter element replacement & housing clean." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 28.5,
      vibration: 0.2,
      health: 93,
    })),
  },
  {
    id: "oil-separator",
    name: "Oil Coalescing Separator",
    subsystem: "Air-Oil Separator Vessel",
    partNumber: "IR-SEP-800 Coalescing Element",
    healthScore: 94,
    status: "HEALTHY",
    temperature: 74.0,
    pressure: "10.8 bar",
    rpm: "N/A",
    vibration: 0.5,
    current: "N/A",
    rulHours: 14000,
    failureProbability: 1.4,
    lastMaintenanceDate: "2026-03-01",
    nextMaintenanceDate: "2026-09-01",
    maintenanceStatus: "Oil Carryover < 2 ppm",
    position3d: [0.8, 0.4, 0],
    cameraOffset: [1.6, 1.2, 2.4],
    explodedOffset: [1.6, 1.2, 0],
    aiDiagnosis: "Air-oil separator element differential pressure 0.3 bar. Oil carryover 1.5 ppm.",
    aiRecommendation: "Sample Ultra-Coolant synthetic oil at 4000h mark.",
    failureState: {
      healthScore: 48,
      status: "CRITICAL",
      temperature: 98.0,
      vibration: 5.2,
      rulHours: 48,
      failureProbability: 74.0,
      aiDiagnosis: "Oil separator element rupture causing oil carryover into plant air header.",
      aiRecommendation: "LOTO compressor & replace oil coalescing separator element.",
    },
    maintenanceHistory: [
      { id: "WO-COMP-504", date: "2026-03-01", type: "Preventive", technician: "Ingersoll Ops", cost: "€620", details: "Air-oil separator element replacement & coolant flush." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 74.0,
      vibration: 0.5,
      health: 94,
    })),
  },
  {
    id: "screw-element",
    name: "Rotary Screw Element",
    subsystem: "Twin-Screw Air Compressor Airend",
    partNumber: "IR-AIREND-200 Screw Rotor Pair",
    healthScore: 96,
    status: "HEALTHY",
    temperature: 78.5,
    pressure: "10.8 bar",
    rpm: "3,600 RPM",
    vibration: 1.1,
    current: "N/A",
    rulHours: 17500,
    failureProbability: 0.9,
    lastMaintenanceDate: "2025-10-15",
    nextMaintenanceDate: "2026-10-15",
    maintenanceStatus: "Rotor Clearance Profile Nominal",
    position3d: [0, 0, 0],
    cameraOffset: [0.8, 0.8, 2.4],
    explodedOffset: [0, -1.0, 0],
    aiDiagnosis: "Rotary male/female screw meshing profile clearance nominal. Discharge temp 78.5°C.",
    aiRecommendation: "Vibration spectrum 1X rotor frequency low.",
    failureState: {
      healthScore: 40,
      status: "CRITICAL",
      temperature: 108.0,
      vibration: 9.0,
      rulHours: 24,
      failureProbability: 86.0,
      aiDiagnosis: "Screw airend discharge rotor thermal scuffing & bearing cage fracture.",
      aiRecommendation: "URGENT: Shutdown compressor & replace rotary screw airend unit.",
    },
    maintenanceHistory: [
      { id: "WO-COMP-505", date: "2025-10-15", type: "Overhaul", technician: "Ingersoll Field Ops", cost: "€4,500", details: "Airend rotor seal replacement & clearance re-shims." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 78.5,
      vibration: 1.1,
      health: 96,
    })),
  },
  {
    id: "pressure-tank",
    name: "High-Pressure Receiver Tank",
    subsystem: "5000L Air Receiver Vessel",
    partNumber: "IR-TANK-5000L ASME Certified Receiver Tank",
    healthScore: 98,
    status: "HEALTHY",
    temperature: 34.0,
    pressure: "10.8 bar",
    rpm: "N/A",
    vibration: 0.2,
    current: "N/A",
    rulHours: 28000,
    failureProbability: 0.1,
    lastMaintenanceDate: "2025-09-01",
    nextMaintenanceDate: "2026-09-01",
    maintenanceStatus: "Auto Drain Valve Cycling Nominal",
    position3d: [2.0, 0, 0],
    cameraOffset: [2.6, 0.8, 2.6],
    explodedOffset: [3.2, 0, 0],
    aiDiagnosis: "ASME pressure vessel 5000L wall thickness 18 mm. Auto condensate drain active.",
    aiRecommendation: "Test safety relief valve annually.",
    failureState: {
      healthScore: 70,
      status: "WARNING",
      temperature: 42.0,
      vibration: 1.4,
      rulHours: 450,
      failureProbability: 25.0,
      aiDiagnosis: "Automatic condensate drain valve clogged causing water accumulation in receiver tank.",
      aiRecommendation: "Purge receiver tank manual drain valve & replace solenoid drain kit.",
    },
    maintenanceHistory: [
      { id: "WO-COMP-506", date: "2025-09-01", type: "Inspection", technician: "TÜV Inspector", cost: "€1,200", details: "ASME pressure tank internal inspection & NDT thickness scan." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 34.0,
      vibration: 0.2,
      health: 98,
    })),
  },
  {
    id: "thrust-bearings",
    name: "Heavy Thrust Bearings",
    subsystem: "Airend Rotor Thrust Support Bearings",
    partNumber: "SKF-7316-Angular Contact Ball Bearings",
    healthScore: 92,
    status: "HEALTHY",
    temperature: 64.0,
    pressure: "N/A",
    rpm: "3,600 RPM",
    vibration: 1.4,
    current: "N/A",
    rulHours: 11000,
    failureProbability: 2.2,
    lastMaintenanceDate: "2026-02-18",
    nextMaintenanceDate: "2026-08-18",
    maintenanceStatus: "Bearing Vibration Baseline Nominal",
    position3d: [0, -0.6, 0],
    cameraOffset: [0.8, 0, 2.2],
    explodedOffset: [0, -1.8, 0],
    aiDiagnosis: "Airend thrust bearing BPFO vibration harmonic under ISO Class 1 threshold.",
    aiRecommendation: "Replenish synthetic coolant lube oil every 4000 hours.",
    failureState: {
      healthScore: 46,
      status: "CRITICAL",
      temperature: 92.0,
      vibration: 7.6,
      rulHours: 40,
      failureProbability: 78.0,
      aiDiagnosis: "Thrust bearing outer race micro-spall causing 380 Hz axial vibration.",
      aiRecommendation: "Replace airend thrust bearing set & inspect oil filter.",
    },
    maintenanceHistory: [
      { id: "WO-COMP-507", date: "2026-02-18", type: "Preventive", technician: "Ingersoll Ops", cost: "€780", details: "Thrust bearing clearance check & oil sampling." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 64.0,
      vibration: 1.4,
      health: 92,
    })),
  },
  {
    id: "control-cabinet-comp",
    name: "Xe-Series Controller Cabinet",
    subsystem: "Ingersoll Rand Xe-145 Microprocessor Panel",
    partNumber: "IR-Xe145 Touchscreen Control Panel",
    healthScore: 97,
    status: "HEALTHY",
    temperature: 32.0,
    pressure: "N/A",
    rpm: "N/A",
    vibration: 0.2,
    current: "8.0 A",
    rulHours: 22000,
    failureProbability: 0.3,
    lastMaintenanceDate: "2026-01-10",
    nextMaintenanceDate: "2027-01-10",
    maintenanceStatus: "Xe-Series OS v4.2 Active",
    position3d: [2.8, 0.4, 0.6],
    cameraOffset: [3.4, 1.0, 2.2],
    explodedOffset: [4.0, 0.4, 1.2],
    aiDiagnosis: "Xe-Series controller Modbus TCP communication verified clean. Auto dual-control active.",
    aiRecommendation: "Clean controller cabinet dust filter.",
    failureState: {
      healthScore: 82,
      status: "WARNING",
      temperature: 52.0,
      vibration: 1.0,
      rulHours: 750,
      failureProbability: 18.0,
      aiDiagnosis: "Control panel internal enclosure temp rise due to clogged filter mat.",
      aiRecommendation: "Wipe controller touchscreen & replace cabinet dust filter.",
    },
    maintenanceHistory: [
      { id: "WO-COMP-508", date: "2026-01-10", type: "Firmware", technician: "Ingersoll Automation", cost: "€380", details: "Xe-145 controller firmware flash & sensor zero check." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 32.0,
      vibration: 0.2,
      health: 97,
    })),
  },
];

export const industrialAirCompressorData = {
  id: "INGERSOLL-COMP-200",
  name: "Industrial Air Compressor",
  category: "Utility & Compressors",
  location: "Utility Plant - Compressor Room 1",
  manufacturer: "Ingersoll Rand",
  plant: "Frankfurt",
  serialNumber: "IR-COMP-200KW-88",
  status: "Running",
  healthScore: 94,
  runningHours: 15400,
  lastMaintenance: "2026-05-02",
  nextMaintenance: "2026-10-02",
  criticalAlerts: 0,
  components: industrialAirCompressorComponents,
  sensors: {
    temperature: { value: 52.0, unit: "°C", baseline: 50.0, status: "NOMINAL" },
    rpm: { value: 3600, unit: "RPM", nominal: 3600, status: "NOMINAL" },
    vibration: { value: 1.3, unit: "mm/s", baseline: 1.2, status: "NOMINAL" },
    voltage: { value: 400.0, unit: "V AC", nominal: 400.0, status: "NOMINAL" },
    current: { value: 85.0, unit: "A", status: "NOMINAL" },
    power: { value: 200.0, unit: "kW", status: "NOMINAL" },
    pressure: { value: "10.8 bar", status: "NOMINAL" },
    efficiency: { value: 95.6, unit: "%", status: "OPTIMAL" },
    rulHours: 15400,
    healthScore: 94,
  },
  aiDiagnosis: {
    summary: "200kW Rotary Screw Air Compressor operating optimal. Discharge pressure 10.8 bar stable, oil carryover < 1.5 ppm.",
    recommendation: "Replenish synthetic coolant lube oil and inspect air filter element at next 2000h service window.",
    confidence: 97.8,
  },
  hotspots: [
    { id: "compressor-motor", name: "200kW Compressor Motor", status: "HEALTHY", temp: "52.0°C", vibration: "1.3 mm/s", position3d: [-2.2, 0.4, 0] },
    { id: "air-filter", name: "Heavy-Duty Air Filter", status: "HEALTHY", temp: "28.5°C", vibration: "0.2 mm/s", position3d: [-0.2, 1.2, 0] },
    { id: "screw-element", name: "Rotary Screw Element", status: "HEALTHY", temp: "78.5°C", vibration: "1.1 mm/s", position3d: [0, 0, 0] },
    { id: "pressure-tank", name: "High-Pressure Receiver Tank", status: "HEALTHY", temp: "34.0°C", vibration: "0.2 mm/s", position3d: [2.0, 0, 0] },
    { id: "control-cabinet-comp", name: "Xe-Series Controller Cabinet", status: "HEALTHY", temp: "32.0°C", vibration: "0.2 mm/s", position3d: [2.8, 0.4, 0.6] },
  ],
  maintenanceHistory: [
    { id: "WO-COMP-501", date: "2026-05-02", type: "Preventive", technician: "H. Schmidt", cost: "€580", details: "Compressor motor bearing grease replenishment & current check." },
    { id: "WO-COMP-504", date: "2026-03-01", type: "Preventive", technician: "Ingersoll Ops", cost: "€620", details: "Air-oil separator element replacement & coolant flush." },
  ],
  documents: [
    { id: "DOC-COMP-601", title: "Ingersoll Rand 200kW Rotary Screw Compressor Manual", fileType: "PDF", size: "22.4 MB" },
    { id: "DOC-COMP-602", title: "Air Receiver ASME Pressure Vessel Inspection Protocol", fileType: "PDF", size: "8.6 MB" },
  ],
};
