// Industrial Pump Station Configuration

export const industrialPumpStationComponents = [
  {
    id: "impeller-stage",
    name: "Stainless Steel Impeller",
    subsystem: "Centrifugal Hydraulic Impeller Assembly",
    partNumber: "KSB-IMP-316L Closed Hydraulic Impeller",
    healthScore: 94,
    status: "HEALTHY",
    temperature: 42.0,
    pressure: "18.2 bar",
    rpm: "2,900 RPM",
    vibration: 1.5,
    current: "N/A",
    rulHours: 14000,
    failureProbability: 1.2,
    lastMaintenanceDate: "2026-04-19",
    nextMaintenanceDate: "2026-09-19",
    maintenanceStatus: "Impeller Dynamic Balance ISO G2.5",
    position3d: [0, 0, 0],
    cameraOffset: [0.8, 0.8, 2.4],
    explodedOffset: [0, 1.2, 0],
    aiDiagnosis: "KSB 316L stainless closed impeller hydraulic efficiency 94.8%. Zero cavitation erosion.",
    aiRecommendation: "Perform hydraulic curve check at 12-month interval.",
    failureState: {
      healthScore: 42,
      status: "CRITICAL",
      temperature: 78.0,
      vibration: 8.8,
      rulHours: 36,
      failureProbability: 82.0,
      aiDiagnosis: "Impeller vane cavitation pitting causing severe hydraulic imbalance and 1X vibration peak.",
      aiRecommendation: "Inspect pump suction pressure & replace damaged impeller stage.",
    },
    maintenanceHistory: [
      { id: "WO-PUMP-601", date: "2026-04-19", type: "Preventive", technician: "KSB Field Ops", cost: "€950", details: "Impeller dynamic balance verification & casing wear ring clearance test." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 42.0,
      vibration: 1.5,
      health: 94,
    })),
  },
  {
    id: "pump-shaft",
    name: "Precision Pump Shaft",
    subsystem: "420 Stainless Heavy Drive Shaft",
    partNumber: "KSB-SHAFT-45MM Hardened Alloy Spindle",
    healthScore: 97,
    status: "HEALTHY",
    temperature: 44.5,
    pressure: "N/A",
    rpm: "2,900 RPM",
    vibration: 0.8,
    current: "N/A",
    rulHours: 22000,
    failureProbability: 0.4,
    lastMaintenanceDate: "2025-10-12",
    nextMaintenanceDate: "2026-10-12",
    maintenanceStatus: "Shaft Runout 0.005 mm",
    position3d: [-0.8, 0, 0],
    cameraOffset: [0, 0.6, 2.2],
    explodedOffset: [-1.4, 0, 0],
    aiDiagnosis: "Precision 420 stainless pump shaft runout within 0.005 mm limit.",
    aiRecommendation: "Check shaft flexible coupling alignment annually.",
    failureState: {
      healthScore: 60,
      status: "WARNING",
      temperature: 72.0,
      vibration: 4.8,
      rulHours: 280,
      failureProbability: 32.0,
      aiDiagnosis: "Shaft thermal laser misalignment causing secondary angular vibration.",
      aiRecommendation: "Laser re-align pump shaft to electric motor coupling.",
    },
    maintenanceHistory: [
      { id: "WO-PUMP-602", date: "2025-10-12", type: "Preventive", technician: "K. Meier", cost: "€450", details: "Laser shaft alignment & coupling pin replacement." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 44.5,
      vibration: 0.8,
      health: 97,
    })),
  },
  {
    id: "radial-bearings",
    name: "Heavy Duty Radial Bearings",
    subsystem: "Drive-End & Non-Drive Shaft Support",
    partNumber: "SKF-6312-C3 Deep Groove Ball Bearings",
    healthScore: 92,
    status: "HEALTHY",
    temperature: 54.0,
    pressure: "N/A",
    rpm: "2,900 RPM",
    vibration: 1.4,
    current: "N/A",
    rulHours: 12600,
    failureProbability: 2.1,
    lastMaintenanceDate: "2026-03-05",
    nextMaintenanceDate: "2026-09-05",
    maintenanceStatus: "Bearing Greasing Nominal",
    position3d: [-1.4, 0, 0],
    cameraOffset: [-0.6, 0.6, 2.2],
    explodedOffset: [-2.2, 0, 0],
    aiDiagnosis: "Bearing outer-race vibration frequency clear. Grease temp 54.0°C.",
    aiRecommendation: "Replenish 30g Mobilith synthetic grease every 2000 operating hours.",
    failureState: {
      healthScore: 46,
      status: "CRITICAL",
      temperature: 89.0,
      vibration: 7.8,
      rulHours: 42,
      failureProbability: 78.0,
      aiDiagnosis: "Drive-end bearing cage micro-spall formation due to moisture contamination.",
      aiRecommendation: "Replace SKF 6312 bearing assembly and check mechanical seal flush line.",
    },
    maintenanceHistory: [
      { id: "WO-PUMP-603", date: "2026-03-05", type: "Preventive", technician: "H. Schmidt", cost: "€380", details: "Pump bearing grease purge & vibration baseline check." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 54.0,
      vibration: 1.4,
      health: 92,
    })),
  },
  {
    id: "mechanical-seal",
    name: "Mechanical Flush Seal",
    subsystem: "Silicon Carbide Shaft Sealing Assembly",
    partNumber: "BURGMANN-HJ927 SSiC Mechanical Seal",
    healthScore: 91,
    status: "HEALTHY",
    temperature: 48.0,
    pressure: "18.2 bar",
    rpm: "2,900 RPM",
    vibration: 0.6,
    current: "N/A",
    rulHours: 11000,
    failureProbability: 2.5,
    lastMaintenanceDate: "2026-02-10",
    nextMaintenanceDate: "2026-08-10",
    maintenanceStatus: "Seal Leakage Zero (Plan 11 Flush)",
    position3d: [-0.4, 0, 0],
    cameraOffset: [0.2, 0.6, 2.0],
    explodedOffset: [-0.4, -1.0, 0],
    aiDiagnosis: "Burgmann silicon carbide mechanical seal face temp 48.0°C. Plan 11 flush flow active.",
    aiRecommendation: "Monitor seal quench drain bottle monthly.",
    failureState: {
      healthScore: 48,
      status: "CRITICAL",
      temperature: 84.0,
      vibration: 4.8,
      rulHours: 48,
      failureProbability: 74.0,
      aiDiagnosis: "Mechanical seal face thermal wiping causing fluid drip leakage > 10 drops/min.",
      aiRecommendation: "Replace Burgmann mechanical seal cartridge & inspect flush cyclone separator.",
    },
    maintenanceHistory: [
      { id: "WO-PUMP-604", date: "2026-02-10", type: "Corrective", technician: "KSB Field Ops", cost: "€820", details: "Mechanical seal replacement & Plan 11 flush line clean." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 48.0,
      vibration: 0.6,
      health: 91,
    })),
  },
  {
    id: "pump-motor",
    name: "75kW Induction Motor",
    subsystem: "High-Efficiency Pump Drive Motor",
    partNumber: "SIEM-1LE5-75KW 4-Pole Electric Motor",
    healthScore: 96,
    status: "HEALTHY",
    temperature: 46.8,
    pressure: "N/A",
    rpm: "2,900 RPM",
    vibration: 1.1,
    current: "62.0 A",
    rulHours: 18500,
    failureProbability: 0.8,
    lastMaintenanceDate: "2026-01-20",
    nextMaintenanceDate: "2027-01-20",
    maintenanceStatus: "Motor Winding Temp 46.8°C Nominal",
    position3d: [-2.2, 0.4, 0],
    cameraOffset: [-1.4, 1.0, 2.6],
    explodedOffset: [-3.4, 0.4, 0],
    aiDiagnosis: "75kW induction motor phase current 62.0 A steady. Efficiency 95.2%.",
    aiRecommendation: "Check motor cooling fan cowl cleanliness.",
    failureState: {
      healthScore: 50,
      status: "CRITICAL",
      temperature: 88.0,
      vibration: 7.2,
      current: "88.0 A",
      rulHours: 50,
      failureProbability: 70.0,
      aiDiagnosis: "Motor L2 phase current overload causing winding temp rise.",
      aiRecommendation: "Verify motor terminal box connection tightness & check VFD output.",
    },
    maintenanceHistory: [
      { id: "WO-PUMP-605", date: "2026-01-20", type: "Preventive", technician: "A. Wagner", cost: "€420", details: "Motor megger insulation test & terminal box re-torque." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 46.8,
      vibration: 1.1,
      health: 96,
    })),
  },
  {
    id: "suction-pipe",
    name: "Flanged Suction Pipe",
    subsystem: "Intake Suction Manifold & Strainer",
    partNumber: "KSB-SUCT-DN200 Stainless Intake Flange",
    healthScore: 98,
    status: "HEALTHY",
    temperature: 22.0,
    pressure: "2.4 bar",
    rpm: "N/A",
    vibration: 0.3,
    current: "N/A",
    rulHours: 25000,
    failureProbability: 0.2,
    lastMaintenanceDate: "2025-09-15",
    nextMaintenanceDate: "2026-09-15",
    maintenanceStatus: "Suction NPSHa 8.5m > NPSHr 3.2m",
    position3d: [0, -1.0, -0.6],
    cameraOffset: [0.8, -0.4, 2.2],
    explodedOffset: [0, -2.2, -1.2],
    aiDiagnosis: "Suction manifold pressure 2.4 bar. NPSH margin +5.3m ensures zero cavitation.",
    aiRecommendation: "Inspect suction basket strainer differential pressure quarterly.",
    failureState: {
      healthScore: 72,
      status: "WARNING",
      temperature: 30.0,
      vibration: 2.8,
      pressure: "0.8 bar",
      rulHours: 350,
      failureProbability: 25.0,
      aiDiagnosis: "Suction strainer debris accumulation causing intake pressure drop.",
      aiRecommendation: "Backwash suction basket strainer & clean intake valve.",
    },
    maintenanceHistory: [
      { id: "WO-PUMP-606", date: "2025-09-15", type: "Inspection", technician: "K. Meier", cost: "€180", details: "Suction basket strainer backwash & flange bolt torque." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 22.0,
      vibration: 0.3,
      health: 98,
    })),
  },
  {
    id: "discharge-pipe",
    name: "High-Pressure Discharge Pipe",
    subsystem: "Discharge Manifold & Check Valve",
    partNumber: "KSB-DISCH-DN150 High Pressure Pipe",
    healthScore: 97,
    status: "HEALTHY",
    temperature: 24.0,
    pressure: "18.2 bar",
    rpm: "N/A",
    vibration: 0.4,
    current: "N/A",
    rulHours: 24000,
    failureProbability: 0.3,
    lastMaintenanceDate: "2025-09-15",
    nextMaintenanceDate: "2026-09-15",
    maintenanceStatus: "Non-Return Check Valve Operational",
    position3d: [0, 1.2, 0.6],
    cameraOffset: [0.8, 1.8, 2.4],
    explodedOffset: [0, 2.4, 1.2],
    aiDiagnosis: "Discharge check valve closing hydraulic damper smooth. Zero water hammer.",
    aiRecommendation: "No maintenance required.",
    failureState: {
      healthScore: 75,
      status: "WARNING",
      temperature: 32.0,
      vibration: 3.2,
      rulHours: 420,
      failureProbability: 22.0,
      aiDiagnosis: "Discharge non-return valve hydraulic damper chatter during pump shutdown.",
      aiRecommendation: "Inspect non-return valve hydraulic dashpot oil level.",
    },
    maintenanceHistory: [
      { id: "WO-PUMP-607", date: "2025-09-15", type: "Preventive", technician: "K. Meier", cost: "€220", details: "Discharge check valve dashpot oil refill & flange leak test." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 24.0,
      vibration: 0.4,
      health: 97,
    })),
  },
  {
    id: "control-panel-pump",
    name: "Automated Pump Control Panel",
    subsystem: "VFD Drive & Pump Station Controller",
    partNumber: "DANFOSS-VLT-AQUA High-Power VFD Panel",
    healthScore: 98,
    status: "HEALTHY",
    temperature: 32.5,
    pressure: "N/A",
    rpm: "N/A",
    vibration: 0.2,
    current: "4.5 A",
    rulHours: 23000,
    failureProbability: 0.2,
    lastMaintenanceDate: "2026-01-10",
    nextMaintenanceDate: "2027-01-10",
    maintenanceStatus: "Danfoss VLT Aqua Drive Active",
    position3d: [2.0, 0.4, 0.8],
    cameraOffset: [2.6, 1.0, 2.2],
    explodedOffset: [3.2, 0.4, 1.4],
    aiDiagnosis: "Danfoss VFD pressure PID loop maintains 18.2 bar constant header pressure.",
    aiRecommendation: "Clean VFD cabinet air filter mat.",
    failureState: {
      healthScore: 82,
      status: "WARNING",
      temperature: 52.0,
      vibration: 1.0,
      rulHours: 800,
      failureProbability: 18.0,
      aiDiagnosis: "VFD cabinet internal cooling fan dust filter restriction.",
      aiRecommendation: "Clean Danfoss VFD heat sink filter mat.",
    },
    maintenanceHistory: [
      { id: "WO-PUMP-608", date: "2026-01-10", type: "Firmware", technician: "Danfoss Ops", cost: "€350", details: "VFD parameters backup & PID loop tuning." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 32.5,
      vibration: 0.2,
      health: 98,
    })),
  },
];

export const industrialPumpStationData = {
  id: "KSB-PUMP-STATION",
  name: "Industrial Pump Station",
  category: "Fluid Management",
  location: "Water Treatment Plant - Station 2",
  manufacturer: "KSB",
  plant: "Hamburg",
  serialNumber: "KSB-PUMP-400-2024",
  status: "Running",
  healthScore: 91,
  runningHours: 12600,
  lastMaintenance: "2026-04-19",
  nextMaintenance: "2026-09-19",
  criticalAlerts: 0,
  components: industrialPumpStationComponents,
  sensors: {
    temperature: { value: 46.8, unit: "°C", baseline: 45.0, status: "NOMINAL" },
    rpm: { value: 2900, unit: "RPM", nominal: 2900, status: "NOMINAL" },
    vibration: { value: 1.5, unit: "mm/s", baseline: 1.3, status: "NOMINAL" },
    voltage: { value: 400.0, unit: "V AC", nominal: 400.0, status: "NOMINAL" },
    current: { value: 62.0, unit: "A", status: "NOMINAL" },
    power: { value: 75.0, unit: "kW", status: "NOMINAL" },
    pressure: { value: "18.2 bar", status: "NOMINAL" },
    efficiency: { value: 94.8, unit: "%", status: "OPTIMAL" },
    rulHours: 12600,
    healthScore: 91,
  },
  aiDiagnosis: {
    summary: "Multistage Centrifugal Booster Pump Station operating at 94.8% hydraulic efficiency. Zero cavitation erosion.",
    recommendation: "Replenish Mobilith synthetic grease on radial bearings at next 2000h service interval.",
    confidence: 97.4,
  },
  hotspots: [
    { id: "impeller-stage", name: "Stainless Steel Impeller", status: "HEALTHY", temp: "42.0°C", vibration: "1.5 mm/s", position3d: [0, 0, 0] },
    { id: "mechanical-seal", name: "Mechanical Flush Seal", status: "HEALTHY", temp: "48.0°C", vibration: "0.6 mm/s", position3d: [-0.4, 0, 0] },
    { id: "pump-motor", name: "75kW Induction Motor", status: "HEALTHY", temp: "46.8°C", vibration: "1.1 mm/s", position3d: [-2.2, 0.4, 0] },
    { id: "suction-pipe", name: "Flanged Suction Pipe", status: "HEALTHY", temp: "22.0°C", vibration: "0.3 mm/s", position3d: [0, -1.0, -0.6] },
    { id: "control-panel-pump", name: "Automated Pump Control Panel", status: "HEALTHY", temp: "32.5°C", vibration: "0.2 mm/s", position3d: [2.0, 0.4, 0.8] },
  ],
  maintenanceHistory: [
    { id: "WO-PUMP-601", date: "2026-04-19", type: "Preventive", technician: "KSB Field Ops", cost: "€950", details: "Impeller dynamic balance verification & casing wear ring clearance test." },
    { id: "WO-PUMP-604", date: "2026-02-10", type: "Corrective", technician: "KSB Field Ops", cost: "€820", details: "Mechanical seal replacement & Plan 11 flush line clean." },
  ],
  documents: [
    { id: "DOC-PUMP-701", title: "KSB Multistage Booster Pump Station Operation Manual", fileType: "PDF", size: "19.8 MB" },
    { id: "DOC-PUMP-702", title: "Burgmann Mechanical Seal Maintenance SOP-PUMP-04", fileType: "PDF", size: "5.4 MB" },
  ],
};
