// Electric Motor M-15 (3-Phase Heavy Duty Induction Motor) Configuration & Part Breakdown

export const motorM15Components = [
  {
    id: "COMP-MTR-HOUSING",
    name: "Cast-Iron Ribbed Stator Housing",
    subsystem: "Frame & Thermal Dissipation Assembly",
    partNumber: "MTR-M15-FR160M Cast Iron Housing",
    healthScore: 98,
    status: "HEALTHY",
    temperature: 42.5,
    pressure: "N/A",
    rpm: "1,480 RPM",
    vibration: 0.8,
    current: "28.0 A",
    rulHours: 24000,
    failureProbability: 0.5,
    lastMaintenanceDate: "2026-04-10",
    nextMaintenanceDate: "2027-04-10",
    maintenanceStatus: "Thermal Fin Heat Dissipation Nominal",
    position3d: [0, 0.4, 0],
    cameraOffset: [0.8, 1.2, 2.4],
    explodedOffset: [0, 1.6, 0],
    aiDiagnosis: "Surface thermal emissivity optimal. Cooling rib airflow unobstructed.",
    aiRecommendation: "Perform periodic cleaning of external cooling fins at standard 6-month interval.",
    failureState: {
      healthScore: 55,
      status: "WARNING",
      temperature: 88.0,
      vibration: 4.2,
      current: "35.0 A",
      rulHours: 120,
      failureProbability: 45.0,
      aiDiagnosis: "Heavy particulate accumulation on stator fins causing restricted convection cooling.",
      aiRecommendation: "Clean stator cooling ribs and verify ambient airflow clearance.",
    },
    maintenanceHistory: [
      { id: "WO-MTR-101", date: "2026-04-10", type: "Preventive", technician: "Electrical Team", cost: "€250", details: "Housing degrease & vibration baseline log." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: Number((41.8 + Math.sin(i * 0.3) * 0.4).toFixed(1)),
      vibration: 0.8,
      health: 98,
    })),
  },
  {
    id: "COMP-MTR-STATOR",
    name: "Stator Core & Copper End Windings",
    subsystem: "Electromagnetic Stator Assembly",
    partNumber: "MTR-STAT-CLASS-H 15kW Stator Core",
    healthScore: 96,
    status: "HEALTHY",
    temperature: 58.2,
    pressure: "N/A",
    rpm: "1,480 RPM",
    vibration: 1.1,
    current: "28.5 A",
    rulHours: 18500,
    failureProbability: 1.2,
    lastMaintenanceDate: "2026-02-15",
    nextMaintenanceDate: "2027-02-15",
    maintenanceStatus: "Class H Insulation Resistance > 500 MOhm",
    position3d: [0, 0.4, 0],
    cameraOffset: [0.6, 1.0, 2.2],
    explodedOffset: [0, 0.4, 1.8],
    aiDiagnosis: "3-phase winding current balance within 0.8% deviation. Insulation dielectric strength optimal.",
    aiRecommendation: "Next insulation resistance Megger test scheduled for annual maintenance cycle.",
    failureState: {
      healthScore: 42,
      status: "CRITICAL",
      temperature: 115.0,
      vibration: 5.8,
      current: "44.0 A",
      rulHours: 36,
      failureProbability: 78.0,
      aiDiagnosis: "Phase-to-phase partial winding short-circuit caused by thermal insulation breakdown.",
      aiRecommendation: "URGENT: Isolate motor power supply and perform surge comparison test on stator windings.",
    },
    maintenanceHistory: [
      { id: "WO-MTR-102", date: "2026-02-15", type: "Inspection", technician: "Siemens Service", cost: "€480", details: "Megger insulation resistance test (1.2 GigaOhm) & surge test pass." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: Number((57.5 + i * 0.1).toFixed(1)),
      vibration: 1.1,
      health: 96,
    })),
  },
  {
    id: "COMP-MTR-ROTOR",
    name: "Squirrel-Cage Rotor Core",
    subsystem: "Rotating Electro-Mechanical Core",
    partNumber: "MTR-ROTOR-SQC160 Die-Cast Aluminum Rotor",
    healthScore: 95,
    status: "HEALTHY",
    temperature: 62.0,
    pressure: "N/A",
    rpm: "1,480 RPM",
    vibration: 1.2,
    current: "28.5 A",
    rulHours: 16000,
    failureProbability: 1.5,
    lastMaintenanceDate: "2026-01-20",
    nextMaintenanceDate: "2027-01-20",
    maintenanceStatus: "Dynamic Balancing Grade ISO G1.0",
    position3d: [0, 0.4, 0],
    cameraOffset: [0.7, 1.1, 2.3],
    explodedOffset: [0, 0.4, -1.8],
    aiDiagnosis: "Rotor bar current signature analysis (MCSA) shows no broken or cracked rotor bars.",
    aiRecommendation: "Rotor residual unbalance under 0.003 g. Operating smoothly.",
    failureState: {
      healthScore: 48,
      status: "CRITICAL",
      temperature: 98.5,
      vibration: 7.2,
      current: "38.0 A",
      rulHours: 48,
      failureProbability: 72.0,
      aiDiagnosis: "Broken rotor bar condition detected via sideband spectrum modulation around fundamental slip frequency.",
      aiRecommendation: "Schedule rotor cage rebuild or replacement to prevent complete stator bore rub damage.",
    },
    maintenanceHistory: [
      { id: "WO-MTR-103", date: "2026-01-20", type: "Preventive", technician: "M. Weber", cost: "€620", details: "Dynamic balance spin testing & ultrasonic flaw check." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: Number((61.2 + Math.cos(i) * 0.3).toFixed(1)),
      vibration: 1.2,
      health: 95,
    })),
  },
  {
    id: "COMP-MTR-DE-BEARING",
    name: "Drive-End (DE) Deep Groove Bearing",
    subsystem: "Front Support & Load Bearing",
    partNumber: "SKF-6309-2Z/C3 Deep Groove Ball Bearing",
    healthScore: 76,
    status: "WARNING",
    temperature: 68.4,
    pressure: "N/A",
    rpm: "1,480 RPM",
    vibration: 3.6,
    current: "29.2 A",
    rulHours: 240,
    failureProbability: 28.5,
    lastMaintenanceDate: "2026-05-02",
    nextMaintenanceDate: "2026-07-15",
    maintenanceStatus: "Outer Race High-Frequency Vibration Peak",
    position3d: [0, 0.4, 1.2],
    cameraOffset: [0.5, 0.8, 2.0],
    explodedOffset: [0, 0.4, 2.6],
    aiDiagnosis: "BPFO (Ball Pass Frequency Outer Race) peak detected at 104 Hz. Early surface spalling on bearing outer ring.",
    aiRecommendation: "Replenish polyurea synthetic grease (15g) and schedule bearing replacement within 14 operating days.",
    failureState: {
      healthScore: 32,
      status: "CRITICAL",
      temperature: 104.0,
      vibration: 9.8,
      current: "39.0 A",
      rulHours: 12,
      failureProbability: 92.0,
      aiDiagnosis: "Severe bearing cage collapse and cage pocket fracture causing imminent shaft seizure.",
      aiRecommendation: "IMMEDIATE EMERGENCY SHUTDOWN: Replace DE bearing and inspect bearing journal fit.",
    },
    maintenanceHistory: [
      { id: "WO-MTR-104", date: "2026-05-02", type: "Lubrication", technician: "K. Schmidt", cost: "€140", details: "Polyurea grease re-injection & vibration spectrum capture." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: Number((65.0 + i * 0.38).toFixed(1)),
      vibration: Number((3.0 + i * 0.07).toFixed(2)),
      health: Math.max(50, 84 - i * 0.9),
    })),
  },
  {
    id: "COMP-MTR-NDE-BEARING",
    name: "Non-Drive End (NDE) Bearing",
    subsystem: "Rear Support Bearing Assembly",
    partNumber: "SKF-6209-2Z/C3 Deep Groove Ball Bearing",
    healthScore: 94,
    status: "HEALTHY",
    temperature: 46.0,
    pressure: "N/A",
    rpm: "1,480 RPM",
    vibration: 0.9,
    current: "28.0 A",
    rulHours: 15400,
    failureProbability: 1.4,
    lastMaintenanceDate: "2026-03-01",
    nextMaintenanceDate: "2027-03-01",
    maintenanceStatus: "Nominal Vibration & Temperature Profile",
    position3d: [0, 0.4, -1.2],
    cameraOffset: [0.5, 0.8, -2.0],
    explodedOffset: [0, 0.4, -2.6],
    aiDiagnosis: "NDE bearing operating smoothly. Preload wave spring maintaining axial position.",
    aiRecommendation: "Routine grease inspection at next 6-month planned maintenance window.",
    failureState: {
      healthScore: 50,
      status: "WARNING",
      temperature: 82.0,
      vibration: 6.4,
      current: "32.0 A",
      rulHours: 150,
      failureProbability: 48.0,
      aiDiagnosis: "NDE bearing grease degradation causing thermal runaway and elevated high-frequency demodulation.",
      aiRecommendation: "Purge contaminated grease and inspect bearing seal integrity.",
    },
    maintenanceHistory: [
      { id: "WO-MTR-105", date: "2026-03-01", type: "Preventive", technician: "K. Schmidt", cost: "€120", details: "Grease replenish & ultrasonic acoustic check." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 46.0,
      vibration: 0.9,
      health: 94,
    })),
  },
  {
    id: "COMP-MTR-SHAFT",
    name: "Precision Rotor Output Shaft",
    subsystem: "Rotational Torque Transmission",
    partNumber: "MTR-SHAFT-42MM High-Tensile 42CrMo4 Shaft",
    healthScore: 98,
    status: "HEALTHY",
    temperature: 44.0,
    pressure: "N/A",
    rpm: "1,480 RPM",
    vibration: 0.7,
    current: "28.0 A",
    rulHours: 25000,
    failureProbability: 0.2,
    lastMaintenanceDate: "2026-01-10",
    nextMaintenanceDate: "2027-01-10",
    maintenanceStatus: "Shaft Runout 0.004 mm (ISO Grade 1)",
    position3d: [0, 0.4, 0],
    cameraOffset: [0.9, 1.1, 2.2],
    explodedOffset: [0, 0.4, 3.2],
    aiDiagnosis: "Shaft radial runout and keyway condition nominal. Zero torsional deflection.",
    aiRecommendation: "Check flexible shaft coupling alignment with driven pump/load.",
    failureState: {
      healthScore: 54,
      status: "WARNING",
      temperature: 78.0,
      vibration: 6.8,
      current: "36.0 A",
      rulHours: 180,
      failureProbability: 42.0,
      aiDiagnosis: "Shaft angular misalignment with driven machine causing 2X RPM harmonic vibration spike.",
      aiRecommendation: "Perform precision laser alignment and replace coupling elastomer insert.",
    },
    maintenanceHistory: [
      { id: "WO-MTR-106", date: "2026-01-10", type: "Inspection", technician: "M. Weber", cost: "€310", details: "Dial indicator shaft runout check (0.004 mm) & keyway inspection." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 44.0,
      vibration: 0.7,
      health: 98,
    })),
  },
  {
    id: "COMP-MTR-FAN",
    name: "Centrifugal Cooling Fan & Cowl",
    subsystem: "Forced Convection Cooling System",
    partNumber: "MTR-FAN-COWL-160 Polypropylene Bi-Directional Fan",
    healthScore: 97,
    status: "HEALTHY",
    temperature: 32.0,
    pressure: "N/A",
    rpm: "1,480 RPM",
    vibration: 0.6,
    current: "N/A",
    rulHours: 20000,
    failureProbability: 0.4,
    lastMaintenanceDate: "2026-04-15",
    nextMaintenanceDate: "2027-04-15",
    maintenanceStatus: "Fan Blades Clean & Cowl Secure",
    position3d: [0, 0.4, -1.5],
    cameraOffset: [0.6, 0.8, -2.2],
    explodedOffset: [0, 0.4, -3.2],
    aiDiagnosis: "Cooling fan volumetric airflow delivers 0.18 m3/s across frame ribs. No blade cracking.",
    aiRecommendation: "Inspect fan cowl intake guard mesh for lint or debris build-up during routine walkdown.",
    failureState: {
      healthScore: 60,
      status: "WARNING",
      temperature: 52.0,
      vibration: 5.2,
      current: "N/A",
      rulHours: 320,
      failureProbability: 35.0,
      aiDiagnosis: "Cooling fan blade chipped causing dynamic unbalance and reduced convection cooling.",
      aiRecommendation: "Replace molded polypropylene fan impeller and check cowl clearance.",
    },
    maintenanceHistory: [
      { id: "WO-MTR-107", date: "2026-04-15", type: "Cleaning", technician: "Plant Maintenance", cost: "€80", details: "Fan cowl removal, blade cleaning & snap-ring check." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 32.0,
      vibration: 0.6,
      health: 97,
    })),
  },
  {
    id: "COMP-MTR-BOX",
    name: "IP66 Terminal Junction Box",
    subsystem: "Electrical Power Connection & Telemetry",
    partNumber: "MTR-TB-6PIN Cast Aluminum Terminal Box",
    healthScore: 99,
    status: "HEALTHY",
    temperature: 36.0,
    pressure: "N/A",
    rpm: "N/A",
    vibration: 0.3,
    current: "28.5 A",
    rulHours: 30000,
    failureProbability: 0.1,
    lastMaintenanceDate: "2026-01-05",
    nextMaintenanceDate: "2027-01-05",
    maintenanceStatus: "Terminal Torque 6.5 Nm & Cable Glands Sealed",
    position3d: [0, 1.2, 0],
    cameraOffset: [0.5, 1.8, 1.5],
    explodedOffset: [0, 2.2, 0],
    aiDiagnosis: "Terminal lugs connection resistance under 0.02 mOhm. No thermal hot spots detected.",
    aiRecommendation: "Gasket seal compression intact. IP66 ingress rating verified.",
    failureState: {
      healthScore: 62,
      status: "WARNING",
      temperature: 84.0,
      vibration: 1.2,
      current: "32.0 A",
      rulHours: 200,
      failureProbability: 38.0,
      aiDiagnosis: "Loose Phase V terminal connection bolt causing high electrical contact resistance heating.",
      aiRecommendation: "Re-torque terminal lug nuts to specified 6.5 Nm and inspect terminal block insulator.",
    },
    maintenanceHistory: [
      { id: "WO-MTR-108", date: "2026-01-05", type: "Torque Check", technician: "Electrical Team", cost: "€110", details: "Infrared thermal scan of terminal block & cable gland seal check." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 36.0,
      vibration: 0.3,
      health: 99,
    })),
  },
];

export const motorM15Data = {
  id: "MOTOR-M-15",
  name: "Electric Motor M-15 (3-Phase Heavy Induction Motor)",
  category: "15kW 400V Squirrel-Cage Industrial Electric Motor",
  location: "Manufacturing Hall - Station M-15",
  manufacturer: "Siemens SIMOTICS Industrial Motors",
  serialNumber: "SN-SIMOTICS-1LE1-15KW",
  installationDate: "2023-08-12",
  operatingHours: 12400,
  status: "WARNING",
  healthScore: 76,
  temperature: 68.4,
  pressure: "N/A",
  vibration: 3.6,
  rpm: "1,480 RPM",
  current: "28.5 A",
  power: "15.0 kW",
  efficiency: "95.2%",
  rulHours: 240,
  components: motorM15Components,
};
