// 45T Hydraulic Stamping Press Configuration & Component Breakdown

export const press45TComponents = [
  {
    id: "COMP-PRS-BED",
    name: "Machine Bed & Bolster Plate",
    subsystem: "Heavy Cast Foundation & Die Bolster",
    partNumber: "PRS-45T-BED-01 Heavy Meehanite Cast Bed",
    healthScore: 98,
    status: "HEALTHY",
    temperature: 38.0,
    pressure: "N/A",
    rpm: "45 SPM",
    vibration: 0.8,
    current: "32.0 A",
    rulHours: 28000,
    failureProbability: 0.3,
    lastMaintenanceDate: "2026-03-12",
    nextMaintenanceDate: "2027-03-12",
    maintenanceStatus: "Bolster Surface Flatness 0.02 mm",
    position3d: [0, -0.3, 0],
    cameraOffset: [1.2, 0.6, 2.8],
    explodedOffset: [0, -1.5, 0],
    aiDiagnosis: "Heavy bed foundation damping capacity optimal. Zero foundation anchor settlement.",
    aiRecommendation: "Verify T-slot cleanliness and die clamp torque at each tooling change.",
    failureState: {
      healthScore: 60,
      status: "WARNING",
      temperature: 55.0,
      vibration: 3.8,
      current: "38.0 A",
      rulHours: 240,
      failureProbability: 35.0,
      aiDiagnosis: "Bolster plate center deflection exceeding 0.08 mm under full 45-ton stamping load.",
      aiRecommendation: "Perform precision laser flatness scan and re-shim bed bolster mounting pads.",
    },
    maintenanceHistory: [
      { id: "WO-PRS-01", date: "2026-03-12", type: "Inspection", technician: "Heavy Press Service", cost: "€550", details: "Bolster optical flatness check & foundation torque verification." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 38.0,
      vibration: 0.8,
      health: 98,
    })),
  },
  {
    id: "COMP-PRS-COLUMNS",
    name: "Chrome Tie Rod Guide Columns",
    subsystem: "Press Frame & Ram Guiding",
    partNumber: "PRS-45T-COL-4X Hard Chrome Plated Tie Rods",
    healthScore: 96,
    status: "HEALTHY",
    temperature: 42.0,
    pressure: "N/A",
    rpm: "45 SPM",
    vibration: 1.0,
    current: "32.0 A",
    rulHours: 22000,
    failureProbability: 1.0,
    lastMaintenanceDate: "2026-02-18",
    nextMaintenanceDate: "2027-02-18",
    maintenanceStatus: "Column Pre-Tension & Bushing Clearance Nominal",
    position3d: [0, 1.4, 0],
    cameraOffset: [1.5, 1.8, 3.2],
    explodedOffset: [2.0, 1.4, 0],
    aiDiagnosis: "4-Column pre-stress hydraulic nuts uniform within 1.2% tensile strain.",
    aiRecommendation: "Automatic centralized lubrication delivering 2cc grease per 1,000 strokes.",
    failureState: {
      healthScore: 50,
      status: "WARNING",
      temperature: 68.0,
      vibration: 5.2,
      current: "42.0 A",
      rulHours: 140,
      failureProbability: 48.0,
      aiDiagnosis: "Front-right bronze guide bushing galling due to dry lubrication condition.",
      aiRecommendation: "Inspect centralized auto-grease line for blockage and clean bronze guide gibs.",
    },
    maintenanceHistory: [
      { id: "WO-PRS-02", date: "2026-02-18", type: "Preventive", technician: "Hydraulics Team", cost: "€420", details: "Guide gib clearance measurement (0.04 mm) & lube distributor clean." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 42.0,
      vibration: 1.0,
      health: 96,
    })),
  },
  {
    id: "COMP-PRS-CROWN",
    name: "Top Hydraulic Crown & Upper Cylinder",
    subsystem: "Main Hydraulic Power & Cylinder Assembly",
    partNumber: "PRS-45T-CYL-250 High-Pressure 250bar Cylinder",
    healthScore: 94,
    status: "HEALTHY",
    temperature: 52.5,
    pressure: "210.0 bar",
    rpm: "45 SPM",
    vibration: 1.2,
    current: "45.0 A",
    rulHours: 17500,
    failureProbability: 1.8,
    lastMaintenanceDate: "2026-01-25",
    nextMaintenanceDate: "2027-01-25",
    maintenanceStatus: "Piston Seals & Pre-Fill Valve Nominal",
    position3d: [0, 3.2, 0],
    cameraOffset: [1.2, 3.4, 2.6],
    explodedOffset: [0, 4.5, 0],
    aiDiagnosis: "Main cylinder pressure holding test passed at 210 bar. Zero internal bypass leakage.",
    aiRecommendation: "Sample hydraulic oil for ISO 4406 particulate cleanliness count next month.",
    failureState: {
      healthScore: 42,
      status: "CRITICAL",
      temperature: 86.0,
      pressure: "145.0 bar",
      vibration: 6.8,
      current: "58.0 A",
      rulHours: 32,
      failureProbability: 80.0,
      aiDiagnosis: "Piston rod high-pressure polyurethane seal blow-by causing rapid tonnage drop.",
      aiRecommendation: "Replace main hydraulic piston seal pack and inspect cylinder barrel for scoring.",
    },
    maintenanceHistory: [
      { id: "WO-PRS-03", date: "2026-01-25", type: "Hydraulic", technician: "Bosch Rexroth", cost: "€1,200", details: "Pre-fill valve cartridge replacement & pressure relief test." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: Number((51.8 + i * 0.15).toFixed(1)),
      vibration: 1.2,
      health: 94,
    })),
  },
  {
    id: "COMP-PRS-RAM",
    name: "Moving Stamping Ram & Forming Die",
    subsystem: "Dynamic Reciprocating Slide & Upper Die",
    partNumber: "PRS-45T-SLIDE Heavy Precision Ram",
    healthScore: 92,
    status: "HEALTHY",
    temperature: 46.0,
    pressure: "210.0 bar",
    rpm: "45 SPM",
    vibration: 1.6,
    current: "45.0 A",
    rulHours: 15200,
    failureProbability: 2.2,
    lastMaintenanceDate: "2026-04-05",
    nextMaintenanceDate: "2026-10-05",
    maintenanceStatus: "Ram Parallelism to Bed < 0.03 mm",
    position3d: [0, 1.7, 0],
    cameraOffset: [0.8, 1.8, 2.5],
    explodedOffset: [0, 1.7, 2.2],
    aiDiagnosis: "Forming stroke positional repeatability 0.01 mm via linear magnetostrictive scale.",
    aiRecommendation: "Check die punch wear and clearance during scheduled weekly tooling audit.",
    failureState: {
      healthScore: 40,
      status: "CRITICAL",
      temperature: 78.0,
      pressure: "160.0 bar",
      vibration: 8.4,
      current: "62.0 A",
      rulHours: 24,
      failureProbability: 84.0,
      aiDiagnosis: "Upper stamping die misalignment causing asymmetric tonnage overload and ram tipping.",
      aiRecommendation: "Re-align stamping die set and inspect linear guide gib shims.",
    },
    maintenanceHistory: [
      { id: "WO-PRS-04", date: "2026-04-05", type: "Tooling", technician: "Die Maintenance", cost: "€880", details: "Upper die punch sharpen & hydraulic ram parallelism re-calibration." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 46.0,
      vibration: 1.6,
      health: 92,
    })),
  },
  {
    id: "COMP-PRS-VALVE",
    name: "Proportional Directional Hydraulic Valve Block",
    subsystem: "Electro-Hydraulic Servo Valve Manifold",
    partNumber: "REXROTH-4WREE-10 Proportional Directional Valve",
    healthScore: 97,
    status: "HEALTHY",
    temperature: 48.0,
    pressure: "210.0 bar",
    rpm: "N/A",
    vibration: 0.7,
    current: "12.0 A",
    rulHours: 20000,
    failureProbability: 0.6,
    lastMaintenanceDate: "2026-03-01",
    nextMaintenanceDate: "2027-03-01",
    maintenanceStatus: "Spool Response Time 12 ms Nominal",
    position3d: [1.8, 2.4, 1.4],
    cameraOffset: [2.2, 2.6, 2.4],
    explodedOffset: [3.2, 2.4, 2.2],
    aiDiagnosis: "Proportional valve position feedback LVDT linear across 0-100% flow range. No stick-slip.",
    aiRecommendation: "Replace pressure line filter element (3 micron) at 2,000 hour interval.",
    failureState: {
      healthScore: 46,
      status: "CRITICAL",
      temperature: 74.0,
      pressure: "175.0 bar",
      vibration: 4.8,
      current: "22.0 A",
      rulHours: 40,
      failureProbability: 75.0,
      aiDiagnosis: "Varnish build-up in valve spool sleeve causing sluggish proportional acceleration response.",
      aiRecommendation: "Ultrasonic flush valve manifold and replace high-pressure filter cartridge.",
    },
    maintenanceHistory: [
      { id: "WO-PRS-05", date: "2026-03-01", type: "Filter Replacement", technician: "Hydraulics Team", cost: "€320", details: "3-Micron pressure filter cartridge swap & spool response test." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 48.0,
      vibration: 0.7,
      health: 97,
    })),
  },
];

export const press45TData = {
  id: "PRESS-45T-02",
  name: "45T Hydraulic Stamping & Forming Press",
  category: "45-Ton Precision 4-Column Hydraulic Forming Press",
  location: "Manufacturing Hall - Press Bay 2",
  manufacturer: "Schuler Hydraulic Presses AG",
  serialNumber: "SCHULER-HYD-45T-2024",
  installationDate: "2023-11-04",
  operatingHours: 9800,
  status: "HEALTHY",
  healthScore: 95,
  temperature: 46.0,
  pressure: "210.0 bar",
  vibration: 1.2,
  rpm: "45 SPM",
  current: "45.0 A",
  power: "37.0 kW",
  efficiency: "96.0%",
  rulHours: 18000,
  components: press45TComponents,
};
