// Schneider Conveyor & Sorting System Configuration

export const schneiderConveyorComponents = [
  {
    id: "sorting-belt",
    name: "High-Speed Sorting Belt",
    subsystem: "Main Modular Belt Conveyor",
    partNumber: "SCHN-SORT-BELT Modular Plastic Belt",
    healthScore: 89,
    status: "HEALTHY",
    temperature: 45.0,
    pressure: "4.0 bar",
    rpm: "1,200 RPM",
    vibration: 1.8,
    current: "34.0 A",
    rulHours: 8900,
    failureProbability: 2.5,
    lastMaintenanceDate: "2026-02-18",
    nextMaintenanceDate: "2026-08-18",
    maintenanceStatus: "Modular Belt Pitch & Tension Nominal",
    position3d: [0, 0, 0],
    cameraOffset: [0.8, 0.8, 2.4],
    explodedOffset: [0, 1.2, 0],
    aiDiagnosis: "Modular conveyor belt linear speed 3.2 m/s verified. Throughput 4800 pkgs/h.",
    aiRecommendation: "Inspect drive sprocket teeth wear during monthly maintenance.",
    failureState: {
      healthScore: 50,
      status: "WARNING",
      temperature: 70.0,
      vibration: 6.2,
      rulHours: 120,
      failureProbability: 55.0,
      aiDiagnosis: "Drive sprocket tooth elongation causing modular belt skip on drive head.",
      aiRecommendation: "Replace drive sprocket wheel & re-tension modular belt track.",
    },
    maintenanceHistory: [
      { id: "WO-SCHN-701", date: "2026-02-18", type: "Preventive", technician: "Schneider Ops", cost: "€450", details: "Modular belt pin replacement & drive sprocket alignment." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 45.0,
      vibration: 1.8,
      health: 89,
    })),
  },
  {
    id: "diverter-arm",
    name: "Pneumatic Diverter Arms",
    subsystem: "High-Speed Package Sorting Diverter",
    partNumber: "SCHN-DIVERT-ARM High-Speed Pneumatic Arm",
    healthScore: 94,
    status: "HEALTHY",
    temperature: 38.0,
    pressure: "5.5 bar",
    rpm: "N/A",
    vibration: 1.1,
    current: "14.0 A",
    rulHours: 13500,
    failureProbability: 1.1,
    lastMaintenanceDate: "2026-04-10",
    nextMaintenanceDate: "2026-10-10",
    maintenanceStatus: "Diverter Response Time 14 ms Nominal",
    position3d: [1.2, 0.4, 0],
    cameraOffset: [1.8, 1.0, 2.2],
    explodedOffset: [2.0, 1.0, 0],
    aiDiagnosis: "Diverter arm pneumatic stroke latency steady at 14 ms. Zero sorting missed packages.",
    aiRecommendation: "Inspect diverter rubber bumper pads.",
    failureState: {
      healthScore: 52,
      status: "CRITICAL",
      temperature: 65.0,
      vibration: 5.5,
      pressure: "3.2 bar",
      rulHours: 60,
      failureProbability: 68.0,
      aiDiagnosis: "Diverter solenoid valve pressure drop causing sluggish arm return.",
      aiRecommendation: "Replace pneumatic solenoid valve cartridge & check air filter.",
    },
    maintenanceHistory: [
      { id: "WO-SCHN-702", date: "2026-04-10", type: "Preventive", technician: "L. Weber", cost: "€280", details: "Diverter arm rubber pad replacement & solenoid valve lubrication." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 38.0,
      vibration: 1.1,
      health: 94,
    })),
  },
  {
    id: "photoelectric-sensors",
    name: "Photoelectric Sensor Array",
    subsystem: "Package Tracking & Gap Detection Array",
    partNumber: "SCHN-OPT-SENS Photoelectric Light Eye Array",
    healthScore: 98,
    status: "HEALTHY",
    temperature: 31.0,
    pressure: "N/A",
    rpm: "N/A",
    vibration: 0.2,
    current: "2.0 A",
    rulHours: 24000,
    failureProbability: 0.2,
    lastMaintenanceDate: "2025-11-05",
    nextMaintenanceDate: "2026-11-05",
    maintenanceStatus: "Package Gap Tracking 100% Accurate",
    position3d: [-1.2, 0.4, 0.6],
    cameraOffset: [-0.6, 1.0, 2.0],
    explodedOffset: [-1.8, 0.4, 1.2],
    aiDiagnosis: "Photoelectric sensor array tracking package gap down to 50 mm.",
    aiRecommendation: "Clean optical reflector mirrors during monthly shutdown.",
    failureState: {
      healthScore: 82,
      status: "WARNING",
      temperature: 44.0,
      vibration: 1.0,
      rulHours: 850,
      failureProbability: 18.0,
      aiDiagnosis: "Photoelectric lens dust accumulation causing intermittent package detection delay.",
      aiRecommendation: "Wipe optical lenses with anti-static cloth.",
    },
    maintenanceHistory: [
      { id: "WO-SCHN-703", date: "2025-11-05", type: "Inspection", technician: "K. Meier", cost: "€150", details: "Photoelectric sensor lens cleaning & optical alignment check." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 31.0,
      vibration: 0.2,
      health: 98,
    })),
  },
  {
    id: "vfd-drive",
    name: "Variable Frequency Drive VFD",
    subsystem: "Altivar Process ATV930 Speed Inverter",
    partNumber: "SCHN-ATV930-18KW Variable Speed Drive",
    healthScore: 96,
    status: "HEALTHY",
    temperature: 42.0,
    pressure: "N/A",
    rpm: "1,200 RPM",
    vibration: 0.4,
    current: "34.0 A",
    rulHours: 21000,
    failureProbability: 0.5,
    lastMaintenanceDate: "2026-01-20",
    nextMaintenanceDate: "2027-01-20",
    maintenanceStatus: "Altivar VFD DC Bus Nominal (560V)",
    position3d: [2.2, 0.6, 0.8],
    cameraOffset: [2.8, 1.2, 2.2],
    explodedOffset: [3.4, 0.6, 1.4],
    aiDiagnosis: "Schneider Altivar VFD motor current waveform harmonic distortion under 2.5%.",
    aiRecommendation: "Inspect VFD enclosure cooling fan.",
    failureState: {
      healthScore: 78,
      status: "WARNING",
      temperature: 62.0,
      vibration: 1.5,
      rulHours: 600,
      failureProbability: 22.0,
      aiDiagnosis: "VFD heat sink fan dust accumulation causing transistor temperature rise.",
      aiRecommendation: "Clean Altivar VFD heat sink cooling fan & filter mat.",
    },
    maintenanceHistory: [
      { id: "WO-SCHN-704", date: "2026-01-20", type: "Firmware", technician: "Schneider Field Ops", cost: "€420", details: "Altivar ATV930 firmware patch update & thermal test." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 42.0,
      vibration: 0.4,
      health: 96,
    })),
  },
  {
    id: "drive-roller",
    name: "Vulcanized Drive Roller",
    subsystem: "Head Drive Roller Assembly",
    partNumber: "SCHN-DRIVE-ROLL 300mm Rubber Coated Roller",
    healthScore: 95,
    status: "HEALTHY",
    temperature: 41.5,
    pressure: "N/A",
    rpm: "1,200 RPM",
    vibration: 1.0,
    current: "N/A",
    rulHours: 17000,
    failureProbability: 0.8,
    lastMaintenanceDate: "2026-03-01",
    nextMaintenanceDate: "2026-09-01",
    maintenanceStatus: "Rubber Vulcanized Coating Intact",
    position3d: [-2.2, 0.2, 0],
    cameraOffset: [-1.4, 0.8, 2.4],
    explodedOffset: [-3.2, 0.2, 0],
    aiDiagnosis: "Head drive roller rubber vulcanized coating friction coefficient nominal.",
    aiRecommendation: "Inspect rubber lag coating wear profile.",
    failureState: {
      healthScore: 60,
      status: "WARNING",
      temperature: 68.0,
      vibration: 4.8,
      rulHours: 320,
      failureProbability: 32.0,
      aiDiagnosis: "Drive roller rubber coating groove wear causing slight belt slip.",
      aiRecommendation: "Re-lag vulcanized rubber coating on drive roller spindle.",
    },
    maintenanceHistory: [
      { id: "WO-SCHN-705", date: "2026-03-01", type: "Preventive", technician: "A. Wagner", cost: "€390", details: "Drive roller rubber coating inspection & bearing greasing." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 41.5,
      vibration: 1.0,
      health: 95,
    })),
  },
  {
    id: "roller-bearings",
    name: "Sealed Roller Bearings",
    subsystem: "Drive & Tail Roller Support Bearings",
    partNumber: "SKF-FY-40-FM Flanged Bearing Units",
    healthScore: 92,
    status: "HEALTHY",
    temperature: 48.0,
    pressure: "N/A",
    rpm: "1,200 RPM",
    vibration: 1.3,
    current: "N/A",
    rulHours: 13000,
    failureProbability: 1.8,
    lastMaintenanceDate: "2026-02-18",
    nextMaintenanceDate: "2026-08-18",
    maintenanceStatus: "Flanged Pillow Block Greased",
    position3d: [-2.2, -0.4, 0],
    cameraOffset: [-1.4, 0.2, 2.2],
    explodedOffset: [-3.2, -0.8, 0],
    aiDiagnosis: "Flanged bearing unit operating temp 48.0°C. Zero inner race spalling.",
    aiRecommendation: "Replenish lithium grease every 2000 hours.",
    failureState: {
      healthScore: 48,
      status: "CRITICAL",
      temperature: 84.0,
      vibration: 7.2,
      rulHours: 45,
      failureProbability: 75.0,
      aiDiagnosis: "Tail roller bearing seal failure causing dust ingress & elevated vibration.",
      aiRecommendation: "Replace SKF FY-40 flanged bearing unit.",
    },
    maintenanceHistory: [
      { id: "WO-SCHN-706", date: "2026-02-18", type: "Preventive", technician: "H. Schmidt", cost: "€280", details: "Pillow block bearing greasing & seal check." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 48.0,
      vibration: 1.3,
      health: 92,
    })),
  },
  {
    id: "package-scanner",
    name: "Package Barcode Scanner",
    subsystem: "Overhead Multi-Laser Tunnel Scanner",
    partNumber: "SICK-CLV690 Overhead Barcode Tunnel",
    healthScore: 99,
    status: "HEALTHY",
    temperature: 30.0,
    pressure: "N/A",
    rpm: "N/A",
    vibration: 0.1,
    current: "2.8 A",
    rulHours: 26000,
    failureProbability: 0.1,
    lastMaintenanceDate: "2025-10-12",
    nextMaintenanceDate: "2026-10-12",
    maintenanceStatus: "Omnidirectional Read Rate 99.9%",
    position3d: [0, 1.6, 0],
    cameraOffset: [0.6, 2.2, 2.2],
    explodedOffset: [0, 2.8, 0],
    aiDiagnosis: "Overhead SICK laser tunnel scanner package identification 99.9% read rate.",
    aiRecommendation: "No maintenance required.",
    failureState: {
      healthScore: 84,
      status: "WARNING",
      temperature: 42.0,
      vibration: 0.9,
      rulHours: 900,
      failureProbability: 15.0,
      aiDiagnosis: "Scanner window smudge causing occasional read retries.",
      aiRecommendation: "Clean scanner glass window with optical wipe.",
    },
    maintenanceHistory: [
      { id: "WO-SCHN-707", date: "2025-10-12", type: "Calibration", technician: "SICK Field Ops", cost: "€320", details: "Tunnel scanner laser alignment & autofocus test." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 30.0,
      vibration: 0.1,
      health: 99,
    })),
  },
  {
    id: "diverter-motor",
    name: "Diverter Servo Motor",
    subsystem: "High-Torque Diverter Actuator Drive",
    partNumber: "SCHN-SERVO-DIVERT 3.5kW Brushless Motor",
    healthScore: 96,
    status: "HEALTHY",
    temperature: 42.5,
    pressure: "N/A",
    rpm: "3,000 RPM",
    vibration: 0.8,
    current: "16.0 A",
    rulHours: 18000,
    failureProbability: 0.6,
    lastMaintenanceDate: "2026-03-15",
    nextMaintenanceDate: "2026-09-15",
    maintenanceStatus: "Diverter Servo Synced",
    position3d: [1.8, 0.4, -0.6],
    cameraOffset: [2.4, 1.0, 1.8],
    explodedOffset: [2.8, -0.2, -1.2],
    aiDiagnosis: "Diverter servo motor acceleration 12 m/s² verified smooth.",
    aiRecommendation: "Check servo motor gear reducer grease level.",
    failureState: {
      healthScore: 65,
      status: "WARNING",
      temperature: 68.0,
      vibration: 4.2,
      rulHours: 350,
      failureProbability: 30.0,
      aiDiagnosis: "Diverter motor coupling rubber damper wear.",
      aiRecommendation: "Replace diverter motor flexible shaft coupling insert.",
    },
    maintenanceHistory: [
      { id: "WO-SCHN-708", date: "2026-03-15", type: "Preventive", technician: "K. Meier", cost: "€250", details: "Diverter servo encoder test & flexible coupling check." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 42.5,
      vibration: 0.8,
      health: 96,
    })),
  },
];

export const schneiderConveyorData = {
  id: "SCHN-CONV-SORT",
  name: "Schneider Conveyor & Sorting System",
  category: "Conveyors & Sorting",
  location: "Logistics Hub - Line B",
  manufacturer: "Schneider",
  plant: "Berlin",
  serialNumber: "SCHN-CONV-8820",
  status: "Running",
  healthScore: 89,
  runningHours: 8900,
  lastMaintenance: "2026-02-18",
  nextMaintenance: "2026-08-18",
  criticalAlerts: 0,
  components: schneiderConveyorComponents,
  sensors: {
    temperature: { value: 45.0, unit: "°C", baseline: 42.0, status: "NOMINAL" },
    rpm: { value: 1200, unit: "RPM", nominal: 1200, status: "NOMINAL" },
    vibration: { value: 1.8, unit: "mm/s", baseline: 1.5, status: "NOMINAL" },
    voltage: { value: 400.0, unit: "V AC", nominal: 400.0, status: "NOMINAL" },
    current: { value: 34.0, unit: "A", status: "NOMINAL" },
    power: { value: 18.5, unit: "kW", status: "NOMINAL" },
    pressure: { value: "4.0 bar", status: "NOMINAL" },
    efficiency: { value: 93.4, unit: "%", status: "NOMINAL" },
    rulHours: 8900,
    healthScore: 89,
  },
  aiDiagnosis: {
    summary: "Conveyor & Sorting System operating smooth. Diverter arm sorting throughput 4800 pkgs/h with 99.9% barcode read rate.",
    recommendation: "Inspect drive sprocket teeth wear and check flanged pillow block greasing at next scheduled maintenance.",
    confidence: 96.8,
  },
  hotspots: [
    { id: "sorting-belt", name: "High-Speed Sorting Belt", status: "HEALTHY", temp: "45.0°C", vibration: "1.8 mm/s", position3d: [0, 0, 0] },
    { id: "diverter-arm", name: "Pneumatic Diverter Arms", status: "HEALTHY", temp: "38.0°C", vibration: "1.1 mm/s", position3d: [1.2, 0.4, 0] },
    { id: "vfd-drive", name: "Variable Frequency Drive VFD", status: "HEALTHY", temp: "42.0°C", vibration: "0.4 mm/s", position3d: [2.2, 0.6, 0.8] },
    { id: "package-scanner", name: "Package Barcode Scanner", status: "HEALTHY", temp: "30.0°C", vibration: "0.1 mm/s", position3d: [0, 1.6, 0] },
  ],
  maintenanceHistory: [
    { id: "WO-SCHN-701", date: "2026-02-18", type: "Preventive", technician: "Schneider Ops", cost: "€450", details: "Modular belt pin replacement & drive sprocket alignment." },
    { id: "WO-SCHN-704", date: "2026-01-20", type: "Firmware", technician: "Schneider Field Ops", cost: "€420", details: "Altivar ATV930 firmware patch update & thermal test." },
  ],
  documents: [
    { id: "DOC-SCHN-801", title: "Schneider Logistics Conveyor & Diverter System Manual", fileType: "PDF", size: "16.4 MB" },
    { id: "DOC-SCHN-802", title: "Altivar Process ATV930 Drive Troubleshooting Guide", fileType: "PDF", size: "9.2 MB" },
  ],
};
