// Siemens Unit 2 Industrial Packaging Machine Configuration

export const siemensUnit2Components = [
  {
    id: "conveyor-belt",
    name: "High-Speed Belt Conveyor",
    subsystem: "Packaging Infeed Transport System",
    partNumber: "SIEM-PKG-CONV-200 Variable Belt Conveyor",
    healthScore: 98,
    status: "HEALTHY",
    temperature: 38.4,
    pressure: "N/A",
    rpm: "1,200 RPM",
    vibration: 0.8,
    current: "22.5 A",
    rulHours: 18500,
    failureProbability: 0.5,
    lastMaintenanceDate: "2026-04-10",
    nextMaintenanceDate: "2026-10-10",
    maintenanceStatus: "Conveyor Belt Tension & Tracking Centered",
    position3d: [-2.5, 0.2, 0],
    cameraOffset: [-1.8, 1.0, 2.5],
    explodedOffset: [-4.0, 0.2, 0],
    aiDiagnosis: "Infeed conveyor belt linear velocity 2.2 m/s verified with zero slip.",
    aiRecommendation: "Perform routine belt tracking sensor lens wipe.",
    failureState: {
      healthScore: 48,
      status: "CRITICAL",
      temperature: 76.0,
      vibration: 6.8,
      current: "38.0 A",
      rulHours: 60,
      failureProbability: 70.0,
      aiDiagnosis: "Conveyor drive motor gear reducer oil starvation causing thermal overload.",
      aiRecommendation: "Check gear reducer oil level and inspect drive belt pulley alignment.",
    },
    maintenanceHistory: [
      { id: "WO-PKG-101", date: "2026-04-10", type: "Preventive", technician: "L. Weber", cost: "€350", details: "Conveyor belt tensioning & drive pulley lubrication." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 38.4,
      vibration: 0.8,
      health: 98,
    })),
  },
  {
    id: "packaging-arm",
    name: "Robotic Packaging Arm",
    subsystem: "Pick & Place Cartoning Mechanism",
    partNumber: "SIEM-ROB-ARM-4Axis High Dynamic Pick & Place",
    healthScore: 95,
    status: "HEALTHY",
    temperature: 42.1,
    pressure: "6.2 bar",
    rpm: "2,200 RPM",
    vibration: 1.1,
    current: "45.0 A",
    rulHours: 14200,
    failureProbability: 1.2,
    lastMaintenanceDate: "2026-03-15",
    nextMaintenanceDate: "2026-09-15",
    maintenanceStatus: "Vacuum Cup Gripper Nominal",
    position3d: [-1.2, 0.8, 0],
    cameraOffset: [-0.4, 1.4, 2.4],
    explodedOffset: [-1.8, 1.8, 0],
    aiDiagnosis: "Packaging arm cycle speed 120 cartons/min with 99.8% pick accuracy.",
    aiRecommendation: "Inspect vacuum suction cup wear pads in 60 days.",
    failureState: {
      healthScore: 42,
      status: "CRITICAL",
      temperature: 84.5,
      vibration: 7.6,
      rulHours: 42,
      failureProbability: 78.0,
      aiDiagnosis: "Vacuum ejector pressure drop causing dropped product packs during high acceleration.",
      aiRecommendation: "Replace vacuum venturi generator filter element and check suction lip.",
    },
    maintenanceHistory: [
      { id: "WO-PKG-102", date: "2026-03-15", type: "Preventive", technician: "H. Schmidt", cost: "€480", details: "Vacuum suction cup replacement & axis 2 backlash test." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 42.1,
      vibration: 1.1,
      health: 95,
    })),
  },
  {
    id: "carton-loader",
    name: "Automated Carton Loader",
    subsystem: "Carton Blank Feeder & Erector",
    partNumber: "SIEM-CARTON-ERECT-500 High-Speed Feeder",
    healthScore: 94,
    status: "HEALTHY",
    temperature: 39.5,
    pressure: "5.5 bar",
    rpm: "1,800 RPM",
    vibration: 0.9,
    current: "28.0 A",
    rulHours: 16000,
    failureProbability: 1.4,
    lastMaintenanceDate: "2026-02-20",
    nextMaintenanceDate: "2026-08-20",
    maintenanceStatus: "Carton Magazine Feeder Full",
    position3d: [0, 0.4, 0],
    cameraOffset: [0.8, 1.2, 2.4],
    explodedOffset: [0, 1.2, 0],
    aiDiagnosis: "Carton blank erector timing synchronized with packaging arm release.",
    aiRecommendation: "Clean carton magazine guide rails during weekend maintenance.",
    failureState: {
      healthScore: 52,
      status: "WARNING",
      temperature: 68.0,
      vibration: 5.2,
      rulHours: 120,
      failureProbability: 45.0,
      aiDiagnosis: "Carton feeder pneumatic stripper pin misfeed causing occasional magazine jam.",
      aiRecommendation: "Inspect pneumatic feeder pin solenoid valve & clean paper dust buildup.",
    },
    maintenanceHistory: [
      { id: "WO-PKG-103", date: "2026-02-20", type: "Preventive", technician: "L. Weber", cost: "€320", details: "Carton guide rail alignment & pneumatic pin lubricated." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 39.5,
      vibration: 0.9,
      health: 94,
    })),
  },
  {
    id: "servo-axis",
    name: "Multi-Axis Servo Drive",
    subsystem: "SINAMICS S120 Multi-Axis Servo System",
    partNumber: "SIEM-S120-SERVO 4-Axis Synchronous Drive",
    healthScore: 97,
    status: "HEALTHY",
    temperature: 44.0,
    pressure: "N/A",
    rpm: "3,000 RPM",
    vibration: 0.7,
    current: "34.0 A",
    rulHours: 21000,
    failureProbability: 0.6,
    lastMaintenanceDate: "2026-01-12",
    nextMaintenanceDate: "2027-01-12",
    maintenanceStatus: "DC Link Voltage Nominal (600V)",
    position3d: [1.2, 0, 0],
    cameraOffset: [1.8, 0.8, 2.2],
    explodedOffset: [1.8, -0.6, 0],
    aiDiagnosis: "SINAMICS multi-axis servo positioning deviation under 0.01 mm.",
    aiRecommendation: "Zero-point encoder reference check verified clean.",
    failureState: {
      healthScore: 60,
      status: "WARNING",
      temperature: 78.0,
      vibration: 4.8,
      rulHours: 320,
      failureProbability: 35.0,
      aiDiagnosis: "Servo motor axis 3 thermal expansion causing harmonic ripple under high load.",
      aiRecommendation: "Recalibrate SINAMICS S120 current controller gain parameters.",
    },
    maintenanceHistory: [
      { id: "WO-PKG-104", date: "2026-01-12", type: "Inspection", technician: "Siemens Automation", cost: "€620", details: "Servo drive firmware flash & DC link capacitor test." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 44.0,
      vibration: 0.7,
      health: 97,
    })),
  },
  {
    id: "pneumatic-cylinder",
    name: "Pneumatic Cylinder Pusher",
    subsystem: "Carton Transfer & Discharge Actuator",
    partNumber: "FESTO-DSBC-80 ISO Cylinder Pusher",
    healthScore: 93,
    status: "HEALTHY",
    temperature: 36.0,
    pressure: "6.2 bar",
    rpm: "N/A",
    vibration: 1.0,
    current: "6.0 A",
    rulHours: 13000,
    failureProbability: 1.5,
    lastMaintenanceDate: "2026-05-02",
    nextMaintenanceDate: "2026-11-02",
    maintenanceStatus: "Cylinder Cushioning Set",
    position3d: [2.0, 0.4, 0],
    cameraOffset: [2.6, 1.0, 2.2],
    explodedOffset: [2.8, 0.4, 0],
    aiDiagnosis: "FESTO pneumatic cylinder end-position magnetic reed switch signals nominal.",
    aiRecommendation: "Inspect cylinder rod seal lip for air micro-leakage.",
    failureState: {
      healthScore: 50,
      status: "CRITICAL",
      temperature: 65.0,
      vibration: 5.8,
      pressure: "3.2 bar",
      rulHours: 72,
      failureProbability: 65.0,
      aiDiagnosis: "Pneumatic cylinder piston seal blow-by causing slow pusher return stroke.",
      aiRecommendation: "Replace FESTO DSBC-80 piston seal kit & clean exhaust muffler.",
    },
    maintenanceHistory: [
      { id: "WO-PKG-105", date: "2026-05-02", type: "Preventive", technician: "A. Wagner", cost: "€210", details: "Pneumatic cylinder seal lube & magnetic switch adjustment." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 36.0,
      vibration: 1.0,
      health: 93,
    })),
  },
  {
    id: "vision-camera",
    name: "Vision Inspection Camera",
    subsystem: "Smart Quality Control & Label Verification",
    partNumber: "COGNEX-IN-SIGHT-7800 Industrial Camera",
    healthScore: 99,
    status: "HEALTHY",
    temperature: 31.0,
    pressure: "N/A",
    rpm: "N/A",
    vibration: 0.1,
    current: "2.5 A",
    rulHours: 25000,
    failureProbability: 0.1,
    lastMaintenanceDate: "2025-09-10",
    nextMaintenanceDate: "2026-09-10",
    maintenanceStatus: "Camera Lens Optical Calibration Verified",
    position3d: [0, 1.6, 0.8],
    cameraOffset: [0.6, 2.2, 2.2],
    explodedOffset: [0, 2.8, 1.2],
    aiDiagnosis: "Cognex smart camera 5MP resolution package inspection 100% pass rate.",
    aiRecommendation: "Clean LED ring light illumination diffuser swab.",
    failureState: {
      healthScore: 82,
      status: "WARNING",
      temperature: 48.0,
      vibration: 1.2,
      rulHours: 800,
      failureProbability: 18.0,
      aiDiagnosis: "Camera protective lens cover dust buildup causing 0.4% false label reject rate.",
      aiRecommendation: "Wipe optical glass cover with lint-free microfiber lens tissue.",
    },
    maintenanceHistory: [
      { id: "WO-PKG-106", date: "2025-09-10", type: "Calibration", technician: "Siemens Field Ops", cost: "€450", details: "Cognex vision camera pattern matching calibration." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 31.0,
      vibration: 0.1,
      health: 99,
    })),
  },
  {
    id: "barcode-scanner",
    name: "Barcode & QR Scanner",
    subsystem: "High-Speed Laser Substrate Scanner",
    partNumber: "DATALOGIC-MATRIX-320 Laser Scanner",
    healthScore: 98,
    status: "HEALTHY",
    temperature: 32.5,
    pressure: "N/A",
    rpm: "N/A",
    vibration: 0.2,
    current: "1.8 A",
    rulHours: 24000,
    failureProbability: 0.2,
    lastMaintenanceDate: "2025-10-05",
    nextMaintenanceDate: "2026-10-05",
    maintenanceStatus: "Barcode Decode Latency 2 ms",
    position3d: [-1.2, 1.4, 0.6],
    cameraOffset: [-0.6, 2.0, 2.0],
    explodedOffset: [-1.8, 2.4, 0.8],
    aiDiagnosis: "Matrix barcode reader 1D/2D code read rate 100% on fast moving cartons.",
    aiRecommendation: "No maintenance required.",
    failureState: {
      healthScore: 85,
      status: "WARNING",
      temperature: 45.0,
      vibration: 1.0,
      rulHours: 950,
      failureProbability: 15.0,
      aiDiagnosis: "Barcode scanner window smudge causing barcode retry attempts.",
      aiRecommendation: "Clean laser scanner window with optical isopropyl wipe.",
    },
    maintenanceHistory: [
      { id: "WO-PKG-107", date: "2025-10-05", type: "Inspection", technician: "K. Meier", cost: "€180", details: "Barcode scanner window cleaning & trigger sensor test." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 32.5,
      vibration: 0.2,
      health: 98,
    })),
  },
  {
    id: "sealing-unit",
    name: "Heat Sealing Unit",
    subsystem: "Thermostatic Box Sealing Mechanism",
    partNumber: "SIEM-SEAL-BAR-180C Thermal Sealer",
    healthScore: 92,
    status: "HEALTHY",
    temperature: 182.0,
    pressure: "4.5 bar",
    rpm: "N/A",
    vibration: 0.6,
    current: "18.5 A",
    rulHours: 11500,
    failureProbability: 2.0,
    lastMaintenanceDate: "2026-04-18",
    nextMaintenanceDate: "2026-10-18",
    maintenanceStatus: "Sealing Temperature 182°C Nominal",
    position3d: [3.0, 0.4, 0],
    cameraOffset: [3.6, 1.0, 2.2],
    explodedOffset: [4.2, 0.4, 0],
    aiDiagnosis: "Heat sealing bar PID temperature control steady at 182°C ± 1.5°C.",
    aiRecommendation: "Inspect Teflon tape cover on sealing bar every 30 days.",
    failureState: {
      healthScore: 54,
      status: "WARNING",
      temperature: 215.0,
      vibration: 3.2,
      current: "28.0 A",
      rulHours: 160,
      failureProbability: 42.0,
      aiDiagnosis: "Solid state relay thermal runaway causing sealing bar over-temperature.",
      aiRecommendation: "Replace SSR heating relay module & inspect thermocouple wiring.",
    },
    maintenanceHistory: [
      { id: "WO-PKG-108", date: "2026-04-18", type: "Preventive", technician: "H. Schmidt", cost: "€290", details: "Sealing bar Teflon tape replacement & PID autotune." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 182.0,
      vibration: 0.6,
      health: 92,
    })),
  },
];

export const siemensUnit2Data = {
  id: "SIEM-UNIT2-PKG",
  name: "Siemens Unit 2 Industrial Packaging Machine",
  category: "Packaging & Cartoning",
  location: "Packaging Bay 2 - Station Unit 2",
  manufacturer: "Siemens",
  plant: "Munich",
  serialNumber: "SN-99801-PKG-2025",
  status: "Running",
  healthScore: 95,
  runningHours: 8420,
  lastMaintenance: "2026-04-10",
  nextMaintenance: "2026-09-15",
  criticalAlerts: 0,
  components: siemensUnit2Components,
  sensors: {
    temperature: { value: 42.1, unit: "°C", baseline: 40.0, status: "NOMINAL" },
    rpm: { value: 2200, unit: "RPM", nominal: 2200, status: "NOMINAL" },
    vibration: { value: 1.1, unit: "mm/s", baseline: 1.0, status: "NOMINAL" },
    voltage: { value: 400.0, unit: "V AC", nominal: 400.0, status: "NOMINAL" },
    current: { value: 45.0, unit: "A", status: "NOMINAL" },
    power: { value: 32.0, unit: "kW", status: "NOMINAL" },
    pressure: { value: "6.2 bar", status: "NOMINAL" },
    efficiency: { value: 97.8, unit: "%", status: "OPTIMAL" },
    rulHours: 14200,
    healthScore: 95,
  },
  aiDiagnosis: {
    summary: "Servo Packaging Line operating optimal. Vacuum cup pickup accuracy 99.8%, carton sealing temp nominal.",
    recommendation: "Routine inspection of vacuum cups and sealing bar Teflon tape during next scheduled maintenance window.",
    confidence: 98.2,
  },
  hotspots: [
    { id: "conveyor-belt", name: "High-Speed Belt Conveyor", status: "HEALTHY", temp: "38.4°C", vibration: "0.8 mm/s", position3d: [-2.5, 0.2, 0] },
    { id: "packaging-arm", name: "Robotic Packaging Arm", status: "HEALTHY", temp: "42.1°C", vibration: "1.1 mm/s", position3d: [-1.2, 0.8, 0] },
    { id: "carton-loader", name: "Automated Carton Loader", status: "HEALTHY", temp: "39.5°C", vibration: "0.9 mm/s", position3d: [0, 0.4, 0] },
    { id: "pneumatic-cylinder", name: "Pneumatic Cylinder Pusher", status: "HEALTHY", temp: "36.0°C", vibration: "1.0 mm/s", position3d: [2.0, 0.4, 0] },
    { id: "sealing-unit", name: "Heat Sealing Unit", status: "HEALTHY", temp: "182.0°C", vibration: "0.6 mm/s", position3d: [3.0, 0.4, 0] },
  ],
  maintenanceHistory: [
    { id: "WO-PKG-101", date: "2026-04-10", type: "Preventive", technician: "L. Weber", cost: "€350", details: "Conveyor belt tensioning & drive pulley lubrication." },
    { id: "WO-PKG-102", date: "2026-03-15", type: "Preventive", technician: "H. Schmidt", cost: "€480", details: "Vacuum suction cup replacement & axis 2 backlash test." },
  ],
  documents: [
    { id: "DOC-PKG-201", title: "Siemens Servo Packaging Line Unit 2 Maintenance Manual", fileType: "PDF", size: "18.5 MB" },
    { id: "DOC-PKG-202", title: "FESTO Pneumatic Actuator Troubleshooting SOP-PKG-02", fileType: "PDF", size: "4.2 MB" },
  ],
};
