// Siemens Unit 1 Industrial Web Converting & Processing Machine Configuration

export const siemensUnit1Components = [
  {
    id: "main-drive-motor",
    name: "Main Drive Motor",
    subsystem: "Primary Spindle Drive Assembly",
    partNumber: "SIEM-1LE5-45KW Heavy Duty Induction Motor",
    healthScore: 97,
    status: "HEALTHY",
    temperature: 54.2,
    pressure: "N/A",
    rpm: "1,450 RPM",
    vibration: 1.1,
    current: "68.5 A",
    rulHours: 16400,
    failureProbability: 0.8,
    lastMaintenanceDate: "2026-03-10",
    nextMaintenanceDate: "2027-03-10",
    maintenanceStatus: "Spindle Alignment Nominal",
    position3d: [-2.2, 0.4, 0],
    cameraOffset: [-1.4, 1.2, 2.8],
    explodedOffset: [-3.8, 0.4, 0],
    aiDiagnosis: "45kW Main drive motor thermal dissipation and current draw within Grade A spec.",
    aiRecommendation: "Perform routine bearing insulation check during next quarterly shutdown.",
    failureState: {
      healthScore: 44,
      status: "CRITICAL",
      temperature: 92.4,
      vibration: 8.2,
      current: "94.0 A",
      rulHours: 36,
      failureProbability: 82.0,
      aiDiagnosis: "Stator winding thermal breakdown causing phase current imbalance on Main Drive Motor.",
      aiRecommendation: "Inspect drive motor L1/L2 phase resistance and verify cooling blower fan rotation.",
    },
    maintenanceHistory: [
      { id: "WO-9010", date: "2026-03-10", type: "Preventive", technician: "M. Bauer", cost: "€420", details: "Drive motor winding insulation check & greasing." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: Number((54.0 + Math.sin(i * 0.2) * 0.4).toFixed(1)),
      vibration: Number((1.1 + Math.cos(i * 0.3) * 0.05).toFixed(2)),
      health: 97,
    })),
  },
  {
    id: "chrome-web-rollers",
    name: "Chrome Web Rollers",
    subsystem: "Web Path Intake & Guidance Rollers",
    partNumber: "SIEM-WST-ROTOR Mirror Chrome Web Rollers",
    healthScore: 94,
    status: "HEALTHY",
    temperature: 46.2,
    pressure: "N/A",
    rpm: "1,450 RPM",
    vibration: 1.1,
    current: "N/A",
    rulHours: 15200,
    failureProbability: 1.8,
    lastMaintenanceDate: "2025-11-20",
    nextMaintenanceDate: "2026-11-20",
    maintenanceStatus: "Chrome Mirror Surface Intact",
    position3d: [-1.2, 0.4, 0],
    cameraOffset: [-0.4, 1.2, 2.8],
    explodedOffset: [-2.2, 0.4, 0],
    aiDiagnosis: "Overhead 6-roller web path rotation smooth. Surface roughness Ra 0.05 um.",
    aiRecommendation: "Wipe down chrome surface using isopropyl solvent at shift change.",
    failureState: {
      healthScore: 40,
      status: "CRITICAL",
      temperature: 88.0,
      vibration: 8.8,
      rulHours: 24,
      failureProbability: 85.0,
      aiDiagnosis: "Roller shaft dynamic imbalance anomaly detected under high web line speed.",
      aiRecommendation: "Re-balance chrome roller assembly and check end pillow-block bearings.",
    },
    maintenanceHistory: [
      { id: "WO-8210", date: "2025-11-20", type: "Overhaul", technician: "Siemens Field Ops", cost: "€2,800", details: "Chrome roller surface refinish and dynamic balancing." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: Number((45.8 + i * 0.1).toFixed(1)),
      vibration: Number((1.0 + Math.cos(i) * 0.1).toFixed(2)),
      health: 94,
    })),
  },
  {
    id: "web-tension-system",
    name: "Web Tension System",
    subsystem: "Closed-Loop Pneumatic Tension Control",
    partNumber: "SIEM-TENS-CTRL Pneumatic Dancer & Load Cells",
    healthScore: 92,
    status: "HEALTHY",
    temperature: 41.5,
    pressure: "4.8 bar",
    rpm: "N/A",
    vibration: 0.8,
    current: "14.2 A",
    rulHours: 12800,
    failureProbability: 2.1,
    lastMaintenanceDate: "2026-04-12",
    nextMaintenanceDate: "2026-10-12",
    maintenanceStatus: "Tension Load Cell Calibrated",
    position3d: [-0.2, 1.2, 0],
    cameraOffset: [0.6, 1.8, 2.8],
    explodedOffset: [-0.2, 2.4, 0],
    aiDiagnosis: "Closed-loop dancer tension feedback steady at 450 N ± 2 N.",
    aiRecommendation: "Zero-point strain gauge recalibration recommended in 120 days.",
    failureState: {
      healthScore: 48,
      status: "CRITICAL",
      temperature: 78.4,
      vibration: 6.2,
      pressure: "2.1 bar",
      rulHours: 48,
      failureProbability: 72.0,
      aiDiagnosis: "Pneumatic dancer cylinder pressure leakage causing web tension oscillation & fluttering.",
      aiRecommendation: "Replace pneumatic cylinder rod seal and recalibrate strain gauge transmitter.",
    },
    maintenanceHistory: [
      { id: "WO-8910", date: "2026-04-12", type: "Preventive", technician: "K. Meier", cost: "€540", details: "Load cell zero-point calibration & dancer brake pad inspection." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 41.5,
      vibration: 0.8,
      health: 92,
    })),
  },
  {
    id: "servo-motors",
    name: "Servo Motors",
    subsystem: "1FT7 High-Dynamic Synchronous Servo Axis",
    partNumber: "SIEM-1FT7-SERVO 22kW Brushless Motor",
    healthScore: 95,
    status: "HEALTHY",
    temperature: 52.8,
    pressure: "N/A",
    rpm: "2,400 RPM",
    vibration: 1.2,
    current: "54.0 A",
    rulHours: 13500,
    failureProbability: 1.6,
    lastMaintenanceDate: "2026-01-18",
    nextMaintenanceDate: "2027-01-18",
    maintenanceStatus: "SINAMICS S120 Inverter Synced",
    position3d: [0.8, 0, 0],
    cameraOffset: [1.6, 0.8, 2.4],
    explodedOffset: [1.8, 0, 0],
    aiDiagnosis: "Servo encoder resolution 24-bit absolute feedback verified clear.",
    aiRecommendation: "Servo motor winding insulation resistance exceeds 100 Mohm.",
    failureState: {
      healthScore: 42,
      status: "CRITICAL",
      temperature: 91.5,
      vibration: 8.1,
      current: "76.0 A",
      rulHours: 36,
      failureProbability: 76.0,
      aiDiagnosis: "Servo inverter phase current imbalance causing secondary harmonic vibration.",
      aiRecommendation: "Recalibrate SINAMICS S120 inverter drive current loops.",
    },
    maintenanceHistory: [
      { id: "WO-8510", date: "2026-01-18", type: "Inspection", technician: "H. Schmidt", cost: "€650", details: "Servo drive encoder alignment & thermal test." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: Number((52.0 + i * 0.1).toFixed(1)),
      vibration: 1.2,
      health: 95,
    })),
  },
  {
    id: "helical-gearbox",
    name: "Helical Gearbox",
    subsystem: "Flender Helical Speed Reducer",
    partNumber: "FLENDER-H3SH07 Triple Reduction Transmission",
    healthScore: 91,
    status: "HEALTHY",
    temperature: 56.4,
    pressure: "5.8 bar",
    rpm: "1,450 RPM",
    vibration: 1.5,
    current: "44.0 A",
    rulHours: 12000,
    failureProbability: 2.5,
    lastMaintenanceDate: "2026-02-15",
    nextMaintenanceDate: "2027-02-15",
    maintenanceStatus: "Helical Gear Mesh Nominal",
    position3d: [1.8, 0, 0],
    cameraOffset: [2.5, 0.8, 2.4],
    explodedOffset: [3.2, 0, 0],
    aiDiagnosis: "Gear mesh backlash 0.7 arcmin. ISO VG 320 oil clear.",
    aiRecommendation: "Oil level sight glass normal. Magnetic drain plug particulate zero.",
    failureState: {
      healthScore: 48,
      status: "CRITICAL",
      temperature: 89.2,
      vibration: 7.8,
      rulHours: 54,
      failureProbability: 66.0,
      aiDiagnosis: "Pinion gear tooth surface pitting causing 420 Hz gear mesh harmonics.",
      aiRecommendation: "Sample gearbox oil for ferrography particle count.",
    },
    maintenanceHistory: [
      { id: "WO-8640", date: "2026-02-15", type: "Preventive", technician: "H. Schmidt", cost: "€820", details: "Gear oil change & magnetic plug check." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 56.4,
      vibration: 1.5,
      health: 91,
    })),
  },
  {
    id: "rotary-cutter",
    name: "Rotary Web Cutter",
    subsystem: "High-Speed Shear Knife Assembly",
    partNumber: "SIEM-CUT-400 Carbide Tipped Rotary Knife",
    healthScore: 96,
    status: "HEALTHY",
    temperature: 48.0,
    pressure: "N/A",
    rpm: "1,450 RPM",
    vibration: 1.0,
    current: "28.0 A",
    rulHours: 14800,
    failureProbability: 1.1,
    lastMaintenanceDate: "2026-05-01",
    nextMaintenanceDate: "2026-11-01",
    maintenanceStatus: "Knife Blade Sharpness Nominal",
    position3d: [2.8, 0.4, 0],
    cameraOffset: [3.4, 1.0, 2.4],
    explodedOffset: [4.2, 0.4, 0],
    aiDiagnosis: "Rotary knife edge clearance set at 0.02 mm. Zero web burr detected.",
    aiRecommendation: "Inspect carbide knife anvil counter-blade during monthly maintenance.",
    failureState: {
      healthScore: 56,
      status: "WARNING",
      temperature: 74.0,
      vibration: 5.4,
      rulHours: 180,
      failureProbability: 40.0,
      aiDiagnosis: "Knife edge micro-chipping causing edge tearing on web substrate.",
      aiRecommendation: "Regrind carbide rotary knife edge or swap knife cassette unit.",
    },
    maintenanceHistory: [
      { id: "WO-9080", date: "2026-05-01", type: "Corrective", technician: "A. Wagner", cost: "€920", details: "Carbide rotary knife blade gap calibration." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 48.0,
      vibration: 1.0,
      health: 96,
    })),
  },
  {
    id: "electrical-cabinet",
    name: "Electrical Cabinet",
    subsystem: "Unit 1 Siemens SIMATIC S7-1500 Controller",
    partNumber: "SIEMENS SIMATIC HMI & S7-1500 PLC Rack",
    healthScore: 98,
    status: "HEALTHY",
    temperature: 34.8,
    pressure: "N/A",
    rpm: "N/A",
    vibration: 0.3,
    current: "16.4 A",
    rulHours: 22000,
    failureProbability: 0.2,
    lastMaintenanceDate: "2026-01-08",
    nextMaintenanceDate: "2027-01-08",
    maintenanceStatus: "Siemens HMI WinCC v17 Active",
    position3d: [3.8, 0.4, 0.8],
    cameraOffset: [4.4, 1.2, 2.4],
    explodedOffset: [5.0, 0.4, 1.5],
    aiDiagnosis: "Control cabinet internal temperature 34.8°C. Profinet cycle time 1.0 ms.",
    aiRecommendation: "Clean cabinet dust filter mat during routine scheduled shift.",
    failureState: {
      healthScore: 80,
      status: "WARNING",
      temperature: 56.0,
      vibration: 1.6,
      current: "24.0 A",
      rulHours: 750,
      failureProbability: 20.0,
      aiDiagnosis: "Control cabinet internal cooling fan dust filter restriction.",
      aiRecommendation: "Clean SIMATIC cabinet dust filter mat and check 24V DC supply.",
    },
    maintenanceHistory: [
      { id: "WO-8480", date: "2026-01-08", type: "Firmware", technician: "Siemens Automation", cost: "€580", details: "SIMATIC HMI firmware update to v17." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 34.8,
      vibration: 0.3,
      health: 98,
    })),
  },
];

export const siemensUnit1Data = {
  id: "SIEM-UNIT1-2026",
  name: "Siemens Unit 1 Industrial Web Converting & Processing Machine",
  category: "Converting & Web Processing",
  location: "Assembly Line 3 - Station Unit 1",
  manufacturer: "Siemens",
  plant: "Munich",
  serialNumber: "SN-99800-UNIT1-2024",
  status: "Running",
  healthScore: 94,
  runningHours: 14280,
  lastMaintenance: "2026-05-14",
  nextMaintenance: "2026-07-28",
  criticalAlerts: 1,
  components: siemensUnit1Components,
  sensors: {
    temperature: { value: 64.8, unit: "°C", baseline: 55.0, status: "WARNING" },
    rpm: { value: 1450, unit: "RPM", nominal: 1450, status: "NOMINAL" },
    vibration: { value: 3.8, unit: "mm/s", baseline: 1.2, status: "ELEVATED" },
    voltage: { value: 400.0, unit: "V AC", nominal: 400.0, status: "NOMINAL" },
    current: { value: 68.5, unit: "A", status: "NOMINAL" },
    power: { value: 42.5, unit: "kW", status: "NOMINAL" },
    pressure: { value: "4.8 bar", status: "NOMINAL" },
    efficiency: { value: 94.2, unit: "%", status: "DEGRADED" },
    rulHours: 168,
    healthScore: 94,
  },
  aiDiagnosis: {
    summary: "Web tension friction drag on overhead intake roller assembly causing 206 Hz bearing harmonic vibration.",
    recommendation: "Inspect Front Bearing SKF 6314-2Z outer race and replenish Klüberplex BEQ synthetic grease within 48h.",
    confidence: 96.4,
  },
  hotspots: [
    { id: "main-drive-motor", name: "Main Drive Motor", status: "HEALTHY", temp: "54.2°C", vibration: "1.1 mm/s", position3d: [-2.2, 0.4, 0] },
    { id: "chrome-web-rollers", name: "Chrome Web Rollers", status: "HEALTHY", temp: "46.2°C", vibration: "1.1 mm/s", position3d: [-1.2, 0.4, 0] },
    { id: "web-tension-system", name: "Web Tension System", status: "HEALTHY", temp: "41.5°C", vibration: "0.8 mm/s", position3d: [-0.2, 1.2, 0] },
    { id: "helical-gearbox", name: "Helical Gearbox", status: "HEALTHY", temp: "56.4°C", vibration: "1.5 mm/s", position3d: [1.8, 0, 0] },
    { id: "electrical-cabinet", name: "Electrical Cabinet", status: "HEALTHY", temp: "34.8°C", vibration: "0.3 mm/s", position3d: [3.8, 0.4, 0.8] },
  ],
  maintenanceHistory: [
    { id: "WO-9104", date: "2026-05-14", type: "Corrective", technician: "K. Meier", cost: "€1,240", details: "Front bearing grease purge & vibration baseline recalibration." },
    { id: "WO-8640", date: "2026-02-15", type: "Preventive", technician: "H. Schmidt", cost: "€820", details: "Flender helical gear oil change & magnetic plug check." },
    { id: "WO-8210", date: "2025-11-20", type: "Overhaul", technician: "Siemens Field Ops", cost: "€2,800", details: "Chrome roller surface refinish and dynamic balancing." },
  ],
  documents: [
    { id: "DOC-SIEM-101", title: "Siemens Web Converting Machine Unit 1 Operation Manual", fileType: "PDF", size: "14.2 MB" },
    { id: "DOC-SIEM-102", title: "SKF Bearing Replacement & Greasing SOP-SIEM-04", fileType: "PDF", size: "3.8 MB" },
  ],
};
