// Siemens CNC Machining Center Configuration

export const siemensCncComponents = [
  {
    id: "spindle-head",
    name: "High-Speed 12,000 RPM Spindle",
    subsystem: "SINUMERIK Electro-Spindle Cartridge",
    partNumber: "SIEM-SPINDLE-12K 55kW Direct Drive Spindle",
    healthScore: 78,
    status: "WARNING",
    temperature: 68.2,
    pressure: "12.5 bar",
    rpm: "12,000 RPM",
    vibration: 3.4,
    current: "72.0 A",
    rulHours: 320,
    failureProbability: 32.5,
    lastMaintenanceDate: "2026-06-15",
    nextMaintenanceDate: "2026-07-25",
    maintenanceStatus: "Spindle Vibration Harmonic Elevated (3.4 mm/s)",
    position3d: [0, 0.8, 0],
    cameraOffset: [0.8, 1.4, 2.4],
    explodedOffset: [0, 2.0, 0],
    aiDiagnosis: "12,000 RPM main spindle ceramic ball bearing outer race wear causing 3.4 mm/s vibration peak at 200 Hz.",
    aiRecommendation: "Schedule spindle cartridge replacement and check high-pressure coolant through-spindle seal within 72 hours.",
    failureState: {
      healthScore: 38,
      status: "CRITICAL",
      temperature: 96.0,
      vibration: 9.2,
      current: "98.0 A",
      rulHours: 24,
      failureProbability: 88.0,
      aiDiagnosis: "Spindle bearing thermal seizure causing automatic emergency feed hold.",
      aiRecommendation: "URGENT: Replace electro-spindle cartridge assembly & verify coolant chiller unit.",
    },
    maintenanceHistory: [
      { id: "WO-CNC-801", date: "2026-06-15", type: "Corrective", technician: "Siemens Field Ops", cost: "€1,850", details: "Spindle taper regrind & ceramic bearing vibration baseline test." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: Number((64.0 + i * 0.42).toFixed(1)),
      vibration: Number((2.8 + i * 0.06).toFixed(2)),
      health: Math.max(50, 88 - i * 1.0),
    })),
  },
  {
    id: "rotary-table",
    name: "5-Axis Rotary Trunnion Table",
    subsystem: "B & C Axis Torque Motor Rotary Table",
    partNumber: "SIEM-TRUNNION-500 Direct Drive Rotary Table",
    healthScore: 94,
    status: "HEALTHY",
    temperature: 42.0,
    pressure: "N/A",
    rpm: "100 RPM",
    vibration: 0.8,
    current: "24.0 A",
    rulHours: 15000,
    failureProbability: 1.2,
    lastMaintenanceDate: "2026-03-10",
    nextMaintenanceDate: "2026-09-10",
    maintenanceStatus: "A/B Axis Angular Encoder Accuracy ±2 arcsec",
    position3d: [0, -0.4, 0],
    cameraOffset: [0.8, 0.4, 2.2],
    explodedOffset: [0, -1.4, 0],
    aiDiagnosis: "5-Axis trunnion rotary table direct drive torque motor temperature 42.0°C nominal.",
    aiRecommendation: "Inspect rotary table hydraulic clamp pressure.",
    failureState: {
      healthScore: 58,
      status: "WARNING",
      temperature: 66.0,
      vibration: 4.2,
      rulHours: 250,
      failureProbability: 36.0,
      aiDiagnosis: "Rotary table C-axis direct drive encoder glass scale contamination.",
      aiRecommendation: "Clean C-axis optical encoder glass scale with isopropyl alcohol swab.",
    },
    maintenanceHistory: [
      { id: "WO-CNC-802", date: "2026-03-10", type: "Preventive", technician: "K. Meier", cost: "€620", details: "5-Axis rotary table encoder zero check & hydraulic brake test." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 42.0,
      vibration: 0.8,
      health: 94,
    })),
  },
  {
    id: "tool-magazine",
    name: "30-Tool Automatic Tool Changer",
    subsystem: "ATC Drum Magazine & Twin-Arm Gripper",
    partNumber: "SIEM-ATC-30 HSK-A63 Tool Carousel",
    healthScore: 96,
    status: "HEALTHY",
    temperature: 36.0,
    pressure: "6.0 bar",
    rpm: "N/A",
    vibration: 0.9,
    current: "12.0 A",
    rulHours: 17500,
    failureProbability: 0.8,
    lastMaintenanceDate: "2026-04-18",
    nextMaintenanceDate: "2026-10-18",
    maintenanceStatus: "Tool Change Time 1.2 sec Nominal",
    position3d: [-1.8, 0.8, 0],
    cameraOffset: [-1.0, 1.4, 2.4],
    explodedOffset: [-3.0, 0.8, 0],
    aiDiagnosis: "HSK-A63 30-tool changer carousel index speed nominal. Tool unclamp pressure 60 bar.",
    aiRecommendation: "Inspect ATC twin-arm gripper finger spring tension.",
    failureState: {
      healthScore: 52,
      status: "WARNING",
      temperature: 60.0,
      vibration: 4.8,
      rulHours: 140,
      failureProbability: 42.0,
      aiDiagnosis: "Tool unclamp hydraulic cylinder pressure drop causing ATC orientation arm delay.",
      aiRecommendation: "Replace tool unclamp cylinder seals & clean tool pot keyways.",
    },
    maintenanceHistory: [
      { id: "WO-CNC-803", date: "2026-04-18", type: "Preventive", technician: "H. Schmidt", cost: "€480", details: "ATC drum chain lube & tool unclamp cylinder seal swap." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 36.0,
      vibration: 0.9,
      health: 96,
    })),
  },
  {
    id: "coolant-pump",
    name: "High-Pressure Coolant Flush Pump",
    subsystem: "70-Bar Through-Spindle Coolant Station",
    partNumber: "BRINKMANN-TH-70 High Pressure Coolant Pump",
    healthScore: 92,
    status: "HEALTHY",
    temperature: 46.0,
    pressure: "12.5 bar",
    rpm: "2,900 RPM",
    vibration: 1.2,
    current: "18.0 A",
    rulHours: 12000,
    failureProbability: 2.0,
    lastMaintenanceDate: "2026-02-10",
    nextMaintenanceDate: "2026-08-10",
    maintenanceStatus: "Coolant Filter Bag Clean",
    position3d: [1.8, -0.4, 0.8],
    cameraOffset: [2.4, 0.4, 2.2],
    explodedOffset: [3.0, -0.8, 1.4],
    aiDiagnosis: "Through-spindle coolant pump pressure 12.5 bar. Chip wash manifold clear.",
    aiRecommendation: "Clean coolant tank fine strainer screen monthly.",
    failureState: {
      healthScore: 46,
      status: "CRITICAL",
      temperature: 78.0,
      vibration: 6.8,
      pressure: "4.2 bar",
      rulHours: 40,
      failureProbability: 76.0,
      aiDiagnosis: "Coolant pump intake strainer clogged with aluminum chips causing cavitating pressure drop.",
      aiRecommendation: "Clean coolant tank filter basket & replace 10 um paper filter bag.",
    },
    maintenanceHistory: [
      { id: "WO-CNC-804", date: "2026-02-10", type: "Preventive", technician: "A. Wagner", cost: "€320", details: "Coolant tank filter bag replacement & pump pressure gauge check." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 46.0,
      vibration: 1.2,
      health: 92,
    })),
  },
  {
    id: "guide-rails",
    name: "Linear Motion Guide Rails",
    subsystem: "X/Y/Z Axis Roller Guide Rails",
    partNumber: "THK-SRG-45 Heavy Load Roller Guides",
    healthScore: 95,
    status: "HEALTHY",
    temperature: 38.0,
    pressure: "N/A",
    rpm: "N/A",
    vibration: 0.6,
    current: "N/A",
    rulHours: 19000,
    failureProbability: 0.6,
    lastMaintenanceDate: "2026-01-15",
    nextMaintenanceDate: "2027-01-15",
    maintenanceStatus: "Central Lube Auto-Pulse Active",
    position3d: [0, 0, -0.8],
    cameraOffset: [0.8, 0.6, 2.2],
    explodedOffset: [0, 0, -1.8],
    aiDiagnosis: "X/Y/Z linear roller guide block friction linear coefficient nominal.",
    aiRecommendation: "Inspect central greasing metering valves every 6 months.",
    failureState: {
      healthScore: 62,
      status: "WARNING",
      temperature: 58.0,
      vibration: 4.0,
      rulHours: 350,
      failureProbability: 30.0,
      aiDiagnosis: "Z-axis linear guide block wiper seal degradation causing fine chip ingress.",
      aiRecommendation: "Replace Z-axis linear guide block wipers & flush guide oil.",
    },
    maintenanceHistory: [
      { id: "WO-CNC-805", date: "2026-01-15", type: "Preventive", technician: "L. Weber", cost: "€580", details: "Linear guide block wiper replacement & central lube purge." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 38.0,
      vibration: 0.6,
      health: 95,
    })),
  },
  {
    id: "chip-conveyor",
    name: "Automated Chip Conveyor",
    subsystem: "Hinged Belt Metal Chip Removal System",
    partNumber: "KABELSCHLEPP-CHIP 500mm Conveyor",
    healthScore: 93,
    status: "HEALTHY",
    temperature: 34.0,
    pressure: "N/A",
    rpm: "30 RPM",
    vibration: 1.1,
    current: "8.5 A",
    rulHours: 14000,
    failureProbability: 1.5,
    lastMaintenanceDate: "2026-05-10",
    nextMaintenanceDate: "2026-11-10",
    maintenanceStatus: "Hinged Belt Tension Nominal",
    position3d: [2.2, -0.8, 0],
    cameraOffset: [2.8, -0.2, 2.2],
    explodedOffset: [3.4, -1.4, 0],
    aiDiagnosis: "Hinged steel belt chip conveyor discharge nominal.",
    aiRecommendation: "Clean chip hopper discharge chute.",
    failureState: {
      healthScore: 56,
      status: "WARNING",
      temperature: 54.0,
      vibration: 4.8,
      rulHours: 160,
      failureProbability: 38.0,
      aiDiagnosis: "Chip conveyor drive chain jam due to stringy metal swarf.",
      aiRecommendation: "Clear chip conveyor jam & re-tension drive chain.",
    },
    maintenanceHistory: [
      { id: "WO-CNC-806", date: "2026-05-10", type: "Preventive", technician: "K. Meier", cost: "€240", details: "Chip conveyor chain drive lube & torque limiter check." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 34.0,
      vibration: 1.1,
      health: 93,
    })),
  },
  {
    id: "cnc-touch-panel",
    name: "SINUMERIK CNC Touch Controller",
    subsystem: "Siemens SINUMERIK ONE 19\" Touch Console",
    partNumber: "SIEMENS-SINUMERIK-ONE CNC Controller",
    healthScore: 98,
    status: "HEALTHY",
    temperature: 32.5,
    pressure: "N/A",
    rpm: "N/A",
    vibration: 0.2,
    current: "6.0 A",
    rulHours: 24000,
    failureProbability: 0.2,
    lastMaintenanceDate: "2026-01-05",
    nextMaintenanceDate: "2027-01-05",
    maintenanceStatus: "SINUMERIK Operate v4.9 Active",
    position3d: [2.2, 0.6, 1.0],
    cameraOffset: [2.8, 1.2, 2.4],
    explodedOffset: [3.4, 0.6, 1.8],
    aiDiagnosis: "SINUMERIK ONE 5-axis NCK cycle interpolation speed nominal.",
    aiRecommendation: "Inspect operator touch glass for scratches.",
    failureState: {
      healthScore: 84,
      status: "WARNING",
      temperature: 52.0,
      vibration: 1.0,
      rulHours: 850,
      failureProbability: 18.0,
      aiDiagnosis: "CNC control cabinet internal cooling fan filter dust restriction.",
      aiRecommendation: "Clean SINUMERIK cabinet air filter mat.",
    },
    maintenanceHistory: [
      { id: "WO-CNC-807", date: "2026-01-05", type: "Firmware", technician: "Siemens Automation", cost: "€650", details: "SINUMERIK NCK software update to v4.9 & PLC backup." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 32.5,
      vibration: 0.2,
      health: 98,
    })),
  },
  {
    id: "enclosure-door",
    name: "Enclosure Door & Interlock",
    subsystem: "Fully Enclosed Machine Guarding Door",
    partNumber: "SIEM-CNC-DOOR Safety Interlocked Guard",
    healthScore: 99,
    status: "HEALTHY",
    temperature: 28.0,
    pressure: "N/A",
    rpm: "N/A",
    vibration: 0.1,
    current: "0.5 A",
    rulHours: 30000,
    failureProbability: 0.0,
    lastMaintenanceDate: "2025-08-01",
    nextMaintenanceDate: "2026-08-01",
    maintenanceStatus: "Door Safety Interlock Locked",
    position3d: [0, 0.4, 1.4],
    cameraOffset: [0.8, 1.0, 3.0],
    explodedOffset: [0, 0.4, 2.6],
    aiDiagnosis: "CNC splash enclosure door safety interlock circuit dual loop closed.",
    aiRecommendation: "No maintenance required.",
    failureState: {
      healthScore: 85,
      status: "WARNING",
      temperature: 34.0,
      vibration: 0.8,
      rulHours: 1200,
      failureProbability: 12.0,
      aiDiagnosis: "Door interlock RFID key mechanical alignment drift.",
      aiRecommendation: "Re-align door RFID interlock catch pin.",
    },
    maintenanceHistory: [
      { id: "WO-CNC-808", date: "2025-08-01", type: "Safety", technician: "Safety Dept", cost: "€180", details: "Door safety interlock switch test & door seal inspection." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 28.0,
      vibration: 0.1,
      health: 99,
    })),
  },
];

export const siemensCncData = {
  id: "SIEM-CNC-5AXIS",
  name: "Siemens CNC Machining Center",
  category: "CNC Machining",
  location: "Precision Machining Shop - Cell 3",
  manufacturer: "Siemens",
  plant: "Leipzig",
  serialNumber: "SIEM-CNC-5X-9942",
  status: "Warning",
  healthScore: 78,
  runningHours: 9320,
  lastMaintenance: "2026-06-15",
  nextMaintenance: "2026-07-25",
  criticalAlerts: 2,
  components: siemensCncComponents,
  sensors: {
    temperature: { value: 68.2, unit: "°C", baseline: 52.0, status: "WARNING" },
    rpm: { value: 12000, unit: "RPM", nominal: 12000, status: "NOMINAL" },
    vibration: { value: 3.4, unit: "mm/s", baseline: 1.2, status: "ELEVATED" },
    voltage: { value: 400.0, unit: "V AC", nominal: 400.0, status: "NOMINAL" },
    current: { value: 72.0, unit: "A", status: "NOMINAL" },
    power: { value: 55.0, unit: "kW", status: "NOMINAL" },
    pressure: { value: "12.5 bar", status: "DEGRADED" },
    efficiency: { value: 91.2, unit: "%", status: "DEGRADED" },
    rulHours: 320,
    healthScore: 78,
  },
  aiDiagnosis: {
    summary: "12,000 RPM 5-Axis CNC Spindle ceramic ball bearing exhibiting outer-race micro-wiping causing 3.4 mm/s vibration peak at 200 Hz.",
    recommendation: "Schedule electro-spindle cartridge replacement within 72 hours and inspect 70-bar through-spindle coolant flush seal.",
    confidence: 95.8,
  },
  hotspots: [
    { id: "spindle-head", name: "High-Speed 12,000 RPM Spindle", status: "WARNING", temp: "68.2°C", vibration: "3.4 mm/s", position3d: [0, 0.8, 0] },
    { id: "rotary-table", name: "5-Axis Rotary Trunnion Table", status: "HEALTHY", temp: "42.0°C", vibration: "0.8 mm/s", position3d: [0, -0.4, 0] },
    { id: "tool-magazine", name: "30-Tool Automatic Tool Changer", status: "HEALTHY", temp: "36.0°C", vibration: "0.9 mm/s", position3d: [-1.8, 0.8, 0] },
    { id: "coolant-pump", name: "High-Pressure Coolant Flush Pump", status: "HEALTHY", temp: "46.0°C", vibration: "1.2 mm/s", position3d: [1.8, -0.4, 0.8] },
    { id: "cnc-touch-panel", name: "SINUMERIK CNC Touch Controller", status: "HEALTHY", temp: "32.5°C", vibration: "0.2 mm/s", position3d: [2.2, 0.6, 1.0] },
  ],
  maintenanceHistory: [
    { id: "WO-CNC-801", date: "2026-06-15", type: "Corrective", technician: "Siemens Field Ops", cost: "€1,850", details: "Spindle taper regrind & ceramic bearing vibration baseline test." },
    { id: "WO-CNC-803", date: "2026-04-18", type: "Preventive", technician: "H. Schmidt", cost: "€480", details: "ATC drum chain lube & tool unclamp cylinder seal swap." },
  ],
  documents: [
    { id: "DOC-CNC-901", title: "Siemens SINUMERIK 5-Axis CNC Milling Center Manual", fileType: "PDF", size: "26.8 MB" },
    { id: "DOC-CNC-902", title: "Spindle Cartridge Replacement & Runout Verification SOP", fileType: "PDF", size: "7.8 MB" },
  ],
};
