// Connected Smartphone Digital Twin Configuration (Live Socket.IO Telemetry)

export const smartphoneTwinComponents = [
  {
    id: "phone-oled-display",
    name: "6.78\" 120Hz AMOLED Display & Digitizer",
    subsystem: "Ultra-HD Capacitive Multi-Touch Panel",
    partNumber: "VIVO-AMOLED-E6-120HZ",
    healthScore: 98,
    status: "HEALTHY",
    temperature: 31.2,
    pressure: "N/A",
    rpm: "120 Hz Refresh",
    vibration: 0.1,
    current: "0.45 A",
    rulHours: 24000,
    failureProbability: 0.5,
    lastMaintenanceDate: "2026-05-10",
    nextMaintenanceDate: "2027-05-10",
    maintenanceStatus: "Touch Digitizer Sample Rate 300Hz Nominal",
    position3d: [0, 0, 0.22],
    cameraOffset: [0.5, 0.4, 4.2],
    explodedOffset: [0, 0, 1.4],
    aiDiagnosis: "AMOLED panel organic emitter degradation index < 0.2%. Touch grid sensitivity 100% uniform.",
    aiRecommendation: "Maintain auto-brightness to maximize OLED blue sub-pixel longevity.",
    failureState: {
      healthScore: 45,
      status: "CRITICAL",
      temperature: 58.0,
      vibration: 2.4,
      rulHours: 80,
      failureProbability: 72.0,
      aiDiagnosis: "Display ribbon connector micro-fracture causing intermittent line flicker.",
      aiRecommendation: "Inspect flex cable ZIF socket tension & replace display assembly.",
    },
    maintenanceHistory: [
      { id: "WO-PH-001", date: "2026-05-10", type: "Inspection", technician: "Quality QA", cost: "$0", details: "Display color calibration & multi-touch latency audit." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: Number((28.0 + i * 0.3).toFixed(1)),
      vibration: 0.1,
      health: 98,
    })),
  },
  {
    id: "phone-li-battery",
    name: "5000mAh High-Density Lithium-Polymer Battery",
    subsystem: "Dual-Cell Fast Charging Energy Storage",
    partNumber: "VIVO-B-S8-5000MAH-LIPO",
    healthScore: 94,
    status: "HEALTHY",
    temperature: 28.0,
    pressure: "N/A",
    rpm: "80W FlashCharge",
    vibration: 0.1,
    current: "3.2 A",
    rulHours: 18000,
    failureProbability: 1.8,
    lastMaintenanceDate: "2026-04-12",
    nextMaintenanceDate: "2026-10-12",
    maintenanceStatus: "Cycle Count 142 / 1200 Cycles (Health: 96%)",
    position3d: [0, -0.4, 0.0],
    cameraOffset: [0.6, -0.2, 4.2],
    explodedOffset: [0, -0.4, -0.9],
    aiDiagnosis: "Lithium-ion electrochemical impedance spectroscopy shows optimal internal resistance (18 mΩ).",
    aiRecommendation: "Thermal management system nominal. Safe fast charging envelope active.",
    failureState: {
      healthScore: 32,
      status: "CRITICAL",
      temperature: 54.0,
      vibration: 0.8,
      current: "6.5 A",
      rulHours: 12,
      failureProbability: 92.0,
      aiDiagnosis: "Battery cell thermal runaway risk detected during high-voltage flash charging.",
      aiRecommendation: "EMERGENCY: Throttle charge current to 5W & cool device immediately.",
    },
    maintenanceHistory: [
      { id: "WO-PH-002", date: "2026-04-12", type: "Diagnostics", technician: "Battery Lab", cost: "$0", details: "Battery impedance test & Coulomb counter calibration." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 28.0,
      vibration: 0.1,
      health: 94,
    })),
  },
  {
    id: "phone-soc-motherboard",
    name: "Octa-Core 4nm AI SoC & Mainboard",
    subsystem: "MediaTek Dimensity 9300 / Snapdragon 8 Gen",
    partNumber: "SOC-4NM-OCTACORE-AI-NPU",
    healthScore: 92,
    status: "HEALTHY",
    temperature: 34.5,
    pressure: "N/A",
    rpm: "3.25 GHz Peak",
    vibration: 0.2,
    current: "1.8 A",
    rulHours: 28000,
    failureProbability: 1.2,
    lastMaintenanceDate: "2026-03-01",
    nextMaintenanceDate: "2027-03-01",
    maintenanceStatus: "All 8 CPU Cores & APU 790 Online",
    position3d: [0, 0.8, 0.0],
    cameraOffset: [0.6, 0.9, 4.2],
    explodedOffset: [0, 1.2, 0.7],
    aiDiagnosis: "SoC dynamic voltage and frequency scaling (DVFS) operating within thermal headroom.",
    aiRecommendation: "Background process scheduler optimal.",
    failureState: {
      healthScore: 48,
      status: "WARNING",
      temperature: 68.0,
      vibration: 0.4,
      rulHours: 120,
      failureProbability: 55.0,
      aiDiagnosis: "Sustained high CPU throttling due to background thread lock.",
      aiRecommendation: "Terminate rogue background processes and allow SoC cool-down.",
    },
    maintenanceHistory: [
      { id: "WO-PH-003", date: "2026-03-01", type: "Firmware", technician: "OS Kernel Team", cost: "$0", details: "Kernel scheduler patch & GPU driver update." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 34.5,
      vibration: 0.2,
      health: 92,
    })),
  },
  {
    id: "phone-camera-module",
    name: "50MP Sony IMX920 Triple Camera & OIS",
    subsystem: "VCS Bionic Optical Image Stabilization Array",
    partNumber: "SONY-IMX920-50MP-OIS",
    healthScore: 99,
    status: "HEALTHY",
    temperature: 29.0,
    pressure: "N/A",
    rpm: "60 FPS 4K HDR",
    vibration: 0.2,
    current: "0.35 A",
    rulHours: 32000,
    failureProbability: 0.3,
    lastMaintenanceDate: "2026-02-15",
    nextMaintenanceDate: "2027-02-15",
    maintenanceStatus: "OIS Voice Coil Motor (VCM) Center Lock Nominal",
    position3d: [-0.38, 0.9, -0.16],
    cameraOffset: [-0.5, 0.9, 4.2],
    explodedOffset: [-0.9, 1.4, -1.3],
    aiDiagnosis: "Optical elements laser centered. Sensor noise ratio 68 dB nominal.",
    aiRecommendation: "Keep sapphire lens protector clean with microfiber cloth.",
    failureState: {
      healthScore: 50,
      status: "WARNING",
      temperature: 44.0,
      vibration: 3.8,
      rulHours: 160,
      failureProbability: 40.0,
      aiDiagnosis: "OIS voice coil motor suspension spring bent from physical drop shock.",
      aiRecommendation: "Replace primary 50MP camera sensor module.",
    },
    maintenanceHistory: [
      { id: "WO-PH-004", date: "2026-02-15", type: "Calibration", technician: "Optics QA", cost: "$0", details: "OIS Gyro drift zero calibration." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 29.0,
      vibration: 0.2,
      health: 99,
    })),
  },
  {
    id: "phone-vapor-chamber",
    name: "3000mm² Liquid Cooling Vapor Chamber",
    subsystem: "Ultra-Thin Multi-Layer Graphite & Copper Heat Pipe",
    partNumber: "VC-COOL-3000MM2-COPPER",
    healthScore: 97,
    status: "HEALTHY",
    temperature: 28.5,
    pressure: "0.05 bar (Vacuum)",
    rpm: "Passive Phase Change",
    vibration: 0.0,
    current: "0.0 A",
    rulHours: 50000,
    failureProbability: 0.2,
    lastMaintenanceDate: "2026-01-10",
    nextMaintenanceDate: "2028-01-10",
    maintenanceStatus: "Capillary Wick Thermal Conductivity 450 W/mK",
    position3d: [0, 0.2, 0.06],
    cameraOffset: [0.5, 0.3, 4.2],
    explodedOffset: [0, 0.2, 0.5],
    aiDiagnosis: "Vapor chamber fluid phase change cycle operating at 100% thermodynamic efficiency.",
    aiRecommendation: "Ensure rear glass thermal contact paste remains intact.",
    failureState: {
      healthScore: 55,
      status: "WARNING",
      temperature: 64.0,
      vibration: 0.0,
      rulHours: 200,
      failureProbability: 38.0,
      aiDiagnosis: "Vapor chamber micro-leak causing vacuum loss and reduced heat dissipation.",
      aiRecommendation: "Replace thermal dissipation copper heat spreader.",
    },
    maintenanceHistory: [
      { id: "WO-PH-005", date: "2026-01-10", type: "Thermal Test", technician: "Thermal Engineering", cost: "$0", details: "Infrared thermal dissipation baseline scan." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 28.5,
      vibration: 0.0,
      health: 97,
    })),
  },
  {
    id: "phone-5g-antennas",
    name: "5G Sub-6GHz & Wi-Fi 6 MIMO Antenna Array",
    subsystem: "RF Front-End Transceiver & LNA Filters",
    partNumber: "RF-MIMO-5G-WIFI6-ARRAY",
    healthScore: 96,
    status: "HEALTHY",
    temperature: 30.0,
    pressure: "N/A",
    rpm: "3.5 Gbps Max",
    vibration: 0.1,
    current: "0.6 A",
    rulHours: 35000,
    failureProbability: 0.8,
    lastMaintenanceDate: "2026-03-20",
    nextMaintenanceDate: "2027-03-20",
    maintenanceStatus: "Wi-Fi RSSI -42 dBm (Excellent Signal)",
    position3d: [0, 1.48, -0.05],
    cameraOffset: [0.5, 1.4, 4.2],
    explodedOffset: [0, 1.9, -0.7],
    aiDiagnosis: "4x4 MIMO antenna beamforming active. Packet loss 0.001%.",
    aiRecommendation: "Maintain unobstructed top and bottom bezel antenna apertures.",
    failureState: {
      healthScore: 52,
      status: "WARNING",
      temperature: 46.0,
      vibration: 0.2,
      rulHours: 220,
      failureProbability: 45.0,
      aiDiagnosis: "Antenna impedance mismatch from physical frame grounding fault.",
      aiRecommendation: "Inspect RF coaxial pigtail connectors & replace antenna gasket.",
    },
    maintenanceHistory: [
      { id: "WO-PH-006", date: "2026-03-20", type: "RF Sweep", technician: "Telecom Lab", cost: "$0", details: "SAR test & Wi-Fi 6 throughput benchmarking." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 30.0,
      vibration: 0.1,
      health: 96,
    })),
  },
  {
    id: "phone-haptic-speaker",
    name: "X-Axis Linear Haptic Motor & Dual Stereo Speakers",
    subsystem: "Precision Resonant Vibration Actuator",
    partNumber: "HAPTIC-X-AXIS-ACTUATOR-1012",
    healthScore: 98,
    status: "HEALTHY",
    temperature: 27.5,
    pressure: "N/A",
    rpm: "170 Hz Resonance",
    vibration: 1.2,
    current: "0.25 A",
    rulHours: 40000,
    failureProbability: 0.4,
    lastMaintenanceDate: "2026-04-05",
    nextMaintenanceDate: "2027-04-05",
    maintenanceStatus: "Haptic Acceleration 1.8G Nominal",
    position3d: [0.4, -1.25, -0.05],
    cameraOffset: [0.6, -1.2, 4.2],
    explodedOffset: [0.9, -1.7, -0.7],
    aiDiagnosis: "Linear resonant actuator magnetic gap clean. Speaker acoustic chamber sealed.",
    aiRecommendation: "Keep bottom speaker acoustic mesh clear of dust.",
    failureState: {
      healthScore: 42,
      status: "CRITICAL",
      temperature: 40.0,
      vibration: 6.5,
      rulHours: 50,
      failureProbability: 68.0,
      aiDiagnosis: "Haptic voice coil winding short causing distorted buzzing.",
      aiRecommendation: "Replace bottom haptic vibration module & speaker box.",
    },
    maintenanceHistory: [
      { id: "WO-PH-007", date: "2026-04-05", type: "Acoustic Test", technician: "Audio QA", cost: "$0", details: "Frequency response curve & THD sweep." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 27.5,
      vibration: 1.2,
      health: 98,
    })),
  },
  {
    id: "phone-chassis",
    name: "Aerospace Aluminum Unibody & 3D Glass Frame",
    subsystem: "Structural Midframe & IP68 Dust/Water Shield",
    partNumber: "CHASSIS-ALUM-7000-IP68",
    healthScore: 99,
    status: "HEALTHY",
    temperature: 28.0,
    pressure: "1.0 atm",
    rpm: "IP68 Certified",
    vibration: 0.1,
    current: "N/A",
    rulHours: 60000,
    failureProbability: 0.1,
    lastMaintenanceDate: "2026-05-15",
    nextMaintenanceDate: "2027-05-15",
    maintenanceStatus: "Chassis Rigidity & Waterproof Seals 100% Intact",
    position3d: [0, 0, -0.12],
    cameraOffset: [0.6, 0, 4.5],
    explodedOffset: [0, 0, -1.8],
    aiDiagnosis: "7000-series aluminum structural frame deflection 0.00 mm. Waterproof gasket pressure tight.",
    aiRecommendation: "Avoid exposing phone to salt water or solvents.",
    failureState: {
      healthScore: 60,
      status: "WARNING",
      temperature: 35.0,
      vibration: 0.5,
      rulHours: 300,
      failureProbability: 35.0,
      aiDiagnosis: "Back glass micro-fracture compromising IP68 water resistance seal.",
      aiRecommendation: "Replace rear curved AG glass panel and adhesive perimeter gasket.",
    },
    maintenanceHistory: [
      { id: "WO-PH-008", date: "2026-05-15", type: "Pressure Test", technician: "IP68 Chamber", cost: "$0", details: "Barometric seal integrity & IP68 submersion test." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 28.0,
      vibration: 0.1,
      health: 99,
    })),
  },
];

export const smartphoneTwinData = {
  id: "MOBILE_001",
  name: "Vivo V2336 (Connected Smartphone Twin)",
  category: "IoT-Connected Mobile Smartphone Digital Twin",
  location: "Live IoT Stream - Client Socket.IO",
  manufacturer: "Vivo Mobile Communications Co.",
  serialNumber: "SN-VIVO-V2336-LIVE",
  status: "HEALTHY",
  healthScore: 96,
  temperature: 28.0,
  pressure: "N/A",
  vibration: 0.1,
  rpm: "120 Hz AMOLED",
  current: "1.45 A",
  power: "5.8 W",
  efficiency: "98.2%",
  rulHours: 18000,
  components: smartphoneTwinComponents,
};
