// Steam Boiler System Configuration

export const steamBoilerComponents = [
  {
    id: "burner-unit",
    name: "High-Efficiency Dual-Fuel Burner",
    subsystem: "Thermal Energy Generation Burner Assembly",
    partNumber: "CB-NATGAS-500HP Dual-Fuel Industrial Burner",
    healthScore: 96,
    status: "HEALTHY",
    temperature: 184.0,
    pressure: "24.0 bar",
    rpm: "1,450 RPM",
    vibration: 0.8,
    current: "48.0 A",
    rulHours: 18200,
    failureProbability: 0.9,
    lastMaintenanceDate: "2026-01-30",
    nextMaintenanceDate: "2026-07-30",
    maintenanceStatus: "Combustion Air-Fuel Ratio 14.7:1 Nominal",
    position3d: [-2.2, 0.4, 0],
    cameraOffset: [-1.4, 1.2, 2.6],
    explodedOffset: [-3.6, 0.4, 0],
    aiDiagnosis: "Dual-fuel burner combustion efficiency 96.2%. Flue O2 concentration 3.2%.",
    aiRecommendation: "Perform annual burner nozzle cleaning and flame scanner test.",
    failureState: {
      healthScore: 46,
      status: "CRITICAL",
      temperature: 245.0,
      vibration: 6.8,
      rulHours: 30,
      failureProbability: 80.0,
      aiDiagnosis: "Burner nozzle carbon deposits causing uneven flame geometry & O2 imbalance.",
      aiRecommendation: "LOTO natural gas supply line & clean burner nozzle orifice.",
    },
    maintenanceHistory: [
      { id: "WO-BOIL-401", date: "2026-01-30", type: "Preventive", technician: "Cleaver Field Ops", cost: "€1,200", details: "Burner flame scanner calibration & fuel valve seal kit." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 184.0,
      vibration: 0.8,
      health: 96,
    })),
  },
  {
    id: "water-drum",
    name: "Water Drum Assembly",
    subsystem: "Lower Mud & Water Recirculation Drum",
    partNumber: "CB-DRUM-LOW Heavy Gauge Pressure Vessel",
    healthScore: 97,
    status: "HEALTHY",
    temperature: 165.0,
    pressure: "22.5 bar",
    rpm: "N/A",
    vibration: 0.4,
    current: "N/A",
    rulHours: 24000,
    failureProbability: 0.3,
    lastMaintenanceDate: "2025-11-15",
    nextMaintenanceDate: "2026-11-15",
    maintenanceStatus: "Ultrasonic Wall Thickness 22 mm Intact",
    position3d: [-0.8, -0.6, 0],
    cameraOffset: [0, 0.2, 2.6],
    explodedOffset: [-0.8, -1.8, 0],
    aiDiagnosis: "Lower water drum blowdown valve cycling nominal. Sludge accumulation zero.",
    aiRecommendation: "Perform automatic daily blowdown cycle check.",
    failureState: {
      healthScore: 65,
      status: "WARNING",
      temperature: 195.0,
      vibration: 3.2,
      rulHours: 400,
      failureProbability: 28.0,
      aiDiagnosis: "Water drum bottom blowdown valve seating leak.",
      aiRecommendation: "Overhaul lower blowdown seat valve gasket.",
    },
    maintenanceHistory: [
      { id: "WO-BOIL-402", date: "2025-11-15", type: "Inspection", technician: "TÜV Rheinland", cost: "€2,400", details: "Ultrasonic wall thickness NDT audit & hydro test." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 165.0,
      vibration: 0.4,
      health: 97,
    })),
  },
  {
    id: "steam-drum",
    name: "Steam Drum Vessel",
    subsystem: "Upper High-Pressure Steam Separation Drum",
    partNumber: "CB-DRUM-HIGH Boiler Steam Separator",
    healthScore: 98,
    status: "HEALTHY",
    temperature: 198.0,
    pressure: "24.0 bar",
    rpm: "N/A",
    vibration: 0.3,
    current: "N/A",
    rulHours: 26000,
    failureProbability: 0.2,
    lastMaintenanceDate: "2025-11-15",
    nextMaintenanceDate: "2026-11-15",
    maintenanceStatus: "Steam Quality 99.5% Dry Saturated",
    position3d: [-0.8, 1.2, 0],
    cameraOffset: [0, 1.8, 2.6],
    explodedOffset: [-0.8, 2.4, 0],
    aiDiagnosis: "Steam drum internal chevron mist eliminator dry steam separation 99.5%.",
    aiRecommendation: "Check boiler water chemical dosing alkalinity level.",
    failureState: {
      healthScore: 68,
      status: "WARNING",
      temperature: 220.0,
      vibration: 3.5,
      rulHours: 450,
      failureProbability: 25.0,
      aiDiagnosis: "High water level carryover risk due to foaming in steam drum.",
      aiRecommendation: "Dose anti-foaming chemical agent & perform surface blowdown.",
    },
    maintenanceHistory: [
      { id: "WO-BOIL-403", date: "2025-11-15", type: "Inspection", technician: "TÜV Rheinland", cost: "€1,800", details: "Steam drum internal chevron separator inspection." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 198.0,
      vibration: 0.3,
      health: 98,
    })),
  },
  {
    id: "feed-pump",
    name: "Multi-Stage Feed Water Pump",
    subsystem: "Boiler Feed Water High-Pressure Booster",
    partNumber: "GRUNDFOS-CRN-45 Multi-Stage Feed Pump",
    healthScore: 93,
    status: "HEALTHY",
    temperature: 62.0,
    pressure: "28.0 bar",
    rpm: "2,900 RPM",
    vibration: 1.6,
    current: "56.0 A",
    rulHours: 12500,
    failureProbability: 1.8,
    lastMaintenanceDate: "2026-03-12",
    nextMaintenanceDate: "2026-09-12",
    maintenanceStatus: "Pump Discharge Pressure 28 bar Nominal",
    position3d: [0.8, -0.4, 0.8],
    cameraOffset: [1.6, 0.4, 2.4],
    explodedOffset: [1.8, -1.2, 1.4],
    aiDiagnosis: "Feed water pump mechanical seal flush flow clear. Head pressure 28.0 bar.",
    aiRecommendation: "Inspect feed pump discharge check valve in 90 days.",
    failureState: {
      healthScore: 44,
      status: "CRITICAL",
      temperature: 92.0,
      vibration: 7.8,
      rulHours: 36,
      failureProbability: 82.0,
      aiDiagnosis: "Feed water pump cavitation due to deaerator tank low water level.",
      aiRecommendation: "Verify deaerator tank level control valve and check pump suction strainer.",
    },
    maintenanceHistory: [
      { id: "WO-BOIL-404", date: "2026-03-12", type: "Preventive", technician: "H. Schmidt", cost: "€650", details: "Feed pump mechanical seal replacement & coupling alignment." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 62.0,
      vibration: 1.6,
      health: 93,
    })),
  },
  {
    id: "safety-valve",
    name: "Safety Pressure Relief Valve",
    subsystem: "ASME Certified Boiler Safety Relief Cluster",
    partNumber: "LESER-441-ASME High-Capacity Safety Valve",
    healthScore: 99,
    status: "HEALTHY",
    temperature: 190.0,
    pressure: "24.0 bar",
    rpm: "N/A",
    vibration: 0.1,
    current: "N/A",
    rulHours: 30000,
    failureProbability: 0.1,
    lastMaintenanceDate: "2025-10-10",
    nextMaintenanceDate: "2026-10-10",
    maintenanceStatus: "Set Pressure 26.5 bar Certified",
    position3d: [-0.8, 2.0, 0],
    cameraOffset: [0, 2.6, 2.4],
    explodedOffset: [-0.8, 3.2, 0],
    aiDiagnosis: "ASME certified safety valve seal tight. Pop test set pressure 26.5 bar verified.",
    aiRecommendation: "Perform annual manual lever test during boiler inspection.",
    failureState: {
      healthScore: 50,
      status: "CRITICAL",
      temperature: 210.0,
      vibration: 5.4,
      rulHours: 24,
      failureProbability: 85.0,
      aiDiagnosis: "Safety valve seat weeping steam due to particulate scale under valve disc.",
      aiRecommendation: "Manually exercise safety valve test lever under pressure to clear scale.",
    },
    maintenanceHistory: [
      { id: "WO-BOIL-405", date: "2025-10-10", type: "Safety", technician: "TÜV Inspector", cost: "€890", details: "ASME pop pressure test & valve seat lapping." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 190.0,
      vibration: 0.1,
      health: 99,
    })),
  },
  {
    id: "pressure-gauge",
    name: "Dual Pressure & Temp Gauges",
    subsystem: "Local Dial Instrumentation & Transmitter Rack",
    partNumber: "WIKA-232.50 Stainless Pressure Gauges",
    healthScore: 98,
    status: "HEALTHY",
    temperature: 184.0,
    pressure: "24.0 bar",
    rpm: "N/A",
    vibration: 0.2,
    current: "2.0 A",
    rulHours: 25000,
    failureProbability: 0.2,
    lastMaintenanceDate: "2026-02-05",
    nextMaintenanceDate: "2027-02-05",
    maintenanceStatus: "Calibration Certified ± 0.25%",
    position3d: [0.8, 1.2, 0.8],
    cameraOffset: [1.4, 1.8, 2.2],
    explodedOffset: [1.8, 1.8, 1.4],
    aiDiagnosis: "WIKA pressure gauge and 4-20mA pressure transmitter readings match within 0.1 bar.",
    aiRecommendation: "No maintenance required.",
    failureState: {
      healthScore: 84,
      status: "WARNING",
      temperature: 200.0,
      vibration: 1.2,
      rulHours: 800,
      failureProbability: 18.0,
      aiDiagnosis: "Pressure transmitter impulse line slight blockage causing slow response.",
      aiRecommendation: "Blow out pressure transmitter siphon loop impulse pipe.",
    },
    maintenanceHistory: [
      { id: "WO-BOIL-406", date: "2026-02-05", type: "Calibration", technician: "K. Meier", cost: "€280", details: "Deadweight tester pressure gauge calibration." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 184.0,
      vibration: 0.2,
      health: 98,
    })),
  },
  {
    id: "economizer",
    name: "Exhaust Flue Economizer",
    subsystem: "Flue Gas Waste Heat Recovery Heat Exchanger",
    partNumber: "CB-ECO-FIN Finned Tube Economizer",
    healthScore: 94,
    status: "HEALTHY",
    temperature: 142.0,
    pressure: "26.0 bar",
    rpm: "N/A",
    vibration: 0.5,
    current: "N/A",
    rulHours: 16000,
    failureProbability: 1.2,
    lastMaintenanceDate: "2025-12-01",
    nextMaintenanceDate: "2026-12-01",
    maintenanceStatus: "Economizer Heat Recovery Efficiency 8.5%",
    position3d: [1.8, 1.6, -0.6],
    cameraOffset: [2.4, 2.2, 1.8],
    explodedOffset: [3.0, 2.4, -1.2],
    aiDiagnosis: "Flue gas inlet temp 240°C, exit temp 142°C. Feed water preheated by +35°C.",
    aiRecommendation: "Inspect economizer finned tubes for soot accumulation.",
    failureState: {
      healthScore: 60,
      status: "WARNING",
      temperature: 190.0,
      vibration: 2.8,
      rulHours: 300,
      failureProbability: 35.0,
      aiDiagnosis: "Economizer finned tube soot fouling reducing heat recovery efficiency.",
      aiRecommendation: "Activate soot blower cycle & wash economizer finned tubes.",
    },
    maintenanceHistory: [
      { id: "WO-BOIL-407", date: "2025-12-01", type: "Preventive", technician: "Cleaver Field Ops", cost: "€750", details: "Economizer soot blowdown & tube leak pressure check." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 142.0,
      vibration: 0.5,
      health: 94,
    })),
  },
  {
    id: "heat-exchanger",
    name: "Tubular Heat Exchanger",
    subsystem: "Blowdown Heat Recovery Exchanger",
    partNumber: "ALFA-LAVAL-SHELL Tubular Heat Exchanger",
    healthScore: 95,
    status: "HEALTHY",
    temperature: 88.0,
    pressure: "6.0 bar",
    rpm: "N/A",
    vibration: 0.4,
    current: "N/A",
    rulHours: 19000,
    failureProbability: 0.8,
    lastMaintenanceDate: "2026-04-02",
    nextMaintenanceDate: "2026-10-02",
    maintenanceStatus: "Shell & Tube Delta T Nominal",
    position3d: [2.2, 0.2, -0.6],
    cameraOffset: [2.8, 0.8, 1.8],
    explodedOffset: [3.4, -0.4, -1.2],
    aiDiagnosis: "Blowdown heat exchanger thermal transfer coefficient nominal.",
    aiRecommendation: "Perform chemical descaling annually.",
    failureState: {
      healthScore: 72,
      status: "WARNING",
      temperature: 115.0,
      vibration: 1.8,
      rulHours: 500,
      failureProbability: 25.0,
      aiDiagnosis: "Heat exchanger tube scale fouling causing reduced thermal transfer.",
      aiRecommendation: "Circulate weak acid descaling solution through tube side.",
    },
    maintenanceHistory: [
      { id: "WO-BOIL-408", date: "2026-04-02", type: "Preventive", technician: "A. Wagner", cost: "€420", details: "Heat exchanger chemical CIP descaling & gasket swap." },
    ],
    timelineData: Array.from({ length: 10 }, (_, i) => ({
      time: `-${(9 - i) * 5}m`,
      temperature: 88.0,
      vibration: 0.4,
      health: 95,
    })),
  },
];

export const steamBoilerData = {
  id: "CLEAVER-BOILER-500",
  name: "Steam Boiler System",
  category: "Thermal Systems",
  location: "Thermal Energy Plant - Boiler Room",
  manufacturer: "Cleaver-Brooks",
  plant: "Cologne",
  serialNumber: "CB-BOILER-500HP",
  status: "Running",
  healthScore: 96,
  runningHours: 18200,
  lastMaintenance: "2026-01-30",
  nextMaintenance: "2026-07-30",
  criticalAlerts: 0,
  components: steamBoilerComponents,
  sensors: {
    temperature: { value: 184.0, unit: "°C", baseline: 180.0, status: "NOMINAL" },
    rpm: { value: 1450, unit: "RPM", nominal: 1450, status: "NOMINAL" },
    vibration: { value: 0.8, unit: "mm/s", baseline: 0.7, status: "NOMINAL" },
    voltage: { value: 400.0, unit: "V AC", nominal: 400.0, status: "NOMINAL" },
    current: { value: 48.0, unit: "A", status: "NOMINAL" },
    power: { value: 350.0, unit: "kW", status: "NOMINAL" },
    pressure: { value: "24.0 bar", status: "NOMINAL" },
    efficiency: { value: 96.2, unit: "%", status: "OPTIMAL" },
    rulHours: 18200,
    healthScore: 96,
  },
  aiDiagnosis: {
    summary: "High-Pressure Steam Boiler System operating at 96.2% combustion efficiency. Flue gas eco-recovery active.",
    recommendation: "Perform routine burner nozzle cleaning and flame scanner test during scheduled shutdown window.",
    confidence: 98.6,
  },
  hotspots: [
    { id: "burner-unit", name: "High-Efficiency Dual-Fuel Burner", status: "HEALTHY", temp: "184.0°C", vibration: "0.8 mm/s", position3d: [-2.2, 0.4, 0] },
    { id: "steam-drum", name: "Steam Drum Vessel", status: "HEALTHY", temp: "198.0°C", vibration: "0.3 mm/s", position3d: [-0.8, 1.2, 0] },
    { id: "feed-pump", name: "Multi-Stage Feed Water Pump", status: "HEALTHY", temp: "62.0°C", vibration: "1.6 mm/s", position3d: [0.8, -0.4, 0.8] },
    { id: "safety-valve", name: "Safety Pressure Relief Valve", status: "HEALTHY", temp: "190.0°C", vibration: "0.1 mm/s", position3d: [-0.8, 2.0, 0] },
    { id: "economizer", name: "Exhaust Flue Economizer", status: "HEALTHY", temp: "142.0°C", vibration: "0.5 mm/s", position3d: [1.8, 1.6, -0.6] },
  ],
  maintenanceHistory: [
    { id: "WO-BOIL-401", date: "2026-01-30", type: "Preventive", technician: "Cleaver Field Ops", cost: "€1,200", details: "Burner flame scanner calibration & fuel valve seal kit." },
    { id: "WO-BOIL-405", date: "2025-10-10", type: "Safety", technician: "TÜV Inspector", cost: "€890", details: "ASME pop pressure test & valve seat lapping." },
  ],
  documents: [
    { id: "DOC-BOIL-501", title: "Cleaver-Brooks 500HP Water-Tube Steam Boiler Technical Manual", fileType: "PDF", size: "32.1 MB" },
    { id: "DOC-BOIL-502", title: "ASME Section I Boiler Inspection & Safety SOP", fileType: "PDF", size: "14.5 MB" },
  ],
};
